### ISSUE TITLE
Issue with NuGet package prerelease version containing "-"

### ISSUE THREAD

**Issue by domaslasauskas** [fsprojects/Paket#841] opened 2015-05-27 14:35 UTC
Paket on Windows omits version after and including second "-" in prerelease version number. This results in issue when trying to update from `3.0.0-alpha-0008` to `3.0.0-alpha-0009` as Paket finds `MyPackage.3.0.0-alpha.nupkg` in cache and just restores previous version instead of new one.

This is was I get in the log when restoring package:

    Downloading MyPackage 3.0.0-alpha-0008 to C:\Users\username\AppData\Local\NuGet\Cache\MyPackage.3.0.0-alpha.nupkg

Paket should maintain whole version when storing downloaded packages in cache.

**Comment by domaslasauskas** [comment] 2015-05-27 14:40
Having hyphen (actually minus) in pre-release version part is allowed according to SemVer and not forbidden anywhere in NuSpec that I could find. From SemVer:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-].

**Comment by domaslasauskas** [comment] 2015-05-27 14:42
Issue seems to be originating here: https://github.com/fsprojects/Paket/blob/0f590df7c81cf8023259633dda3f510c62e53173/src/Paket.Bootstrapper/NugetDownloadStrategy.cs#L87

**Comment by domaslasauskas** [comment] 2015-05-27 14:56
As a workaround one could use `paket restore --force`.

**Comment by forki** [comment] 2015-05-27 14:59
No that's the bootstrapper. The issue is probably in similar code in
Paket.Core project

**Comment by domaslasauskas** [comment] 2015-05-27 16:04
Sorry, here is the code from Paket.Core: https://github.com/fsprojects/Paket/blob/8a6bbb5387a249ca36f54dd27b348991704c29a2/src/Paket.Core/SemVer.fs#L132

**Comment by forki** [comment] 2015-05-28 08:16
should be fixed. could you please retry?

**Closed** 2015-05-28 08:15 UTC
Labels: bug

**Comment by domaslasauskas** [comment] 2015-05-29 16:04
Now it works fine. Cheers!
