### ISSUE TITLE
Paket keeps a lock on nuget files after an update

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#941] opened 2015-07-24 16:40 UTC
I have a FAKE script that repeatedly calls Paket.Update (via the Paket nuget package) on a specific package (before doing a host of other things).

So imagine that I have a dependencies file that contains e.g. FSharp.Core. I have a set of targets, which sequentially do:

1. ```Paket.Update FSharp.Core "4.0.0.1"``` -> then do other stuff
2. ```Paket.Update FSharp.Core "3.1.2.5"``` -> then do other stuff
3. ```Paket.Update FSharp.Core "3.1.2.1"``` -> then do other stuff
4. ```Paket.Update FSharp.Core "3.0.2"``` -> then do other stuff

The problem is that immedately after the first call to Paket.Update, FSI.exe retains a lock on all the DLLs inside the FSharp.Core folder, so subsequent calls to Paket.Update fail because the files are in use, so it can't clean the folder up.

![fsc](https://cloud.githubusercontent.com/assets/1781813/8879705/fefdd756-322a-11e5-805c-a94937261d97.png)

**Comment by forki** [comment] 2015-07-27 14:24
do you have a repro sample? I tried:

        open System
        open System.IO
 
        Environment.CurrentDirectory <- __SOURCE_DIRECTORY__
 
        #I @"packages\Paket.Core\lib\net45"
        #r "Paket.Core.dll"

        Paket.Dependencies.Install """
            source https://nuget.org/api/v2
            nuget Paket.Core
            nuget FSharp.Core 4.0.0.1
            nuget FAKE
        """;;

        let deps = Paket.Dependencies.Locate()

        deps.UpdatePackage("FSharp.Core", Some "3.1.2.5", false, false);;

but I get `error FS0192: internal error: convMethodRef: could not bind to method` which might be an issue because of ILRepack?

**Comment by isaacabraham** [comment] 2015-07-27 15:40
Which version of VS are you using? I noticed some issues running Paket through code on VS2013 - I moved over to 2015 and the issue went away.

**Comment by isaacabraham** [comment] 2015-07-27 15:40
I'll try create a sample repro.

**Comment by forki** [comment] 2015-07-27 15:48
I assume my issue is caused by .NET 4.6 /F# 4.0 install.

**Comment by forki** [comment] 2016-04-06 07:52
closing since we don't have a repro

**Closed by forki** 2016-04-06 07:52 UTC
Labels: needs-repro
