### ISSUE TITLE
Cannot fetch FsCheck

### ISSUE THREAD

**Issue by haf** [fsprojects/Paket#497] opened 2015-01-01 15:32 UTC
For suave, trying to upgrade Fuchu plus deps:

```
Error in resolution.
  Resolved:
    - Fuchu-suave >= 0.6 < 1.0
    - Fuchu-suave.FsCheck >= 0.6 < 1.0
    - RazorEngine 3.4.2
    - Microsoft.AspNet.Razor 3.2.2
    - NuGet.CommandLine 2.8.3
    - FsPickler 1.0.6
    - openssl.redist 1.0.1.25
    - FSharp.Charting 0.90.8
    - Fuchu-suave.PerfUtil 0.6.0
    - PerfUtil 0.1.8
    - FSharp.Core >= 3.1.2.1
       - from Fuchu-suave 0.6.0
  Can't resolve:
    - FsCheck >= 1.0.4
       - from Fuchu-suave.FsCheck 0.6.0
 Please try to relax some conditions.
```

paket.dependencies:

```
source https://nuget.org/api/v2

nuget FSharp.Charting
nuget FSharp.Core
nuget RazorEngine
nuget NuGet.CommandLine
nuget FsPickler
nuget Fuchu-suave ~> 0.6
nuget Fuchu-suave.FsCheck ~> 0.6
nuget Fuchu-suave.PerfUtil ~> 0.6
nuget PerfUtil
nuget openssl.redist
```

1.0.4 exists: https://www.nuget.org/packages/FsCheck/

Repro at this point: https://github.com/SuaveIO/suave/tree/feature/libs at 2202588740a3d5bb1bcb2c71a091c98cf413788b

**Comment by haf** [comment] 2015-01-01 15:56
Same with 0.20.7

**Comment by forki** [comment] 2015-01-01 15:57
Yep. I can reproduce and try to investigate

**Comment by haf** [comment] 2015-01-01 15:57
@forki thank you =)

**Comment by forki** [comment] 2015-01-01 16:00
Looks the version is not reported on the Web API:

**Comment by forki** [comment] 2015-01-01 16:01
Looks the version is not reported on the NuGet WebAPI:
![image](https://cloud.githubusercontent.com/assets/57396/5592599/a538834a-91d7-11e4-8de6-ca38df8707f4.png)

Is this a eventual inconsistency issue!?

will have to dig deeper.

**Comment by forki** [comment] 2015-01-01 16:06
yep I can confirm:

Package is only listed in NuGet v2 API. v3 gives:

    {"@context":{"@vocab":"http://schema.nuget.org/schema#"},"totalHits":15,"timeTakenInMs":1,"index":"ng-v3search-nov13-2014","data":["0.7.1","0.8.0","0.8.1","0.8.2","0.8.3","0.9.0","0.9.0.1","0.9.1","0.9.2","0.9.3","0.9.4","1.0.0","1.0.1","1.0.2","1.0.3"],"answeredBy":"nuget-prod-0-v3search_IN0-search"}

/cc @jeffhandley

**Comment by forki** [comment] 2015-01-01 16:34
Still no update - v3 seems to be unreliable right now.
Will release a hotfix which just uses v2 for now

**Comment by forki** [comment] 2015-01-01 16:43
Fixed by disabling NuGet v3 - ;-(

**Closed by forki** 2015-01-01 16:43 UTC
