### ISSUE TITLE
Version 5.87.0 breaking some 3rd part dependencies 

### ISSUE THREAD

**Issue by pmiossec** [fsprojects/Paket#2656] opened 2017-08-24 10:48 UTC
### Description

Version 5.87.0 (verified!) of paket introduced a regression and remove 3rd part dependencies. They are removed of the `paket.lock`file and of the csproj files preventing to build. 

### Repro steps

1. Create a console project (c#) and convert to paket

2. With Paket >=5.87.0, add the nuget packages`Common.Logging` to the project

3. Add the line `ILog logger = LogManager.GetLogger("test");` and `using Common.Logging;`in the only cs file. 

4. Verify that you can't build. The interface ILog is not recognised. And the dependency `Common.Logging.Core` is missing. 

5. Delete the `paket.lock` and do a `paket install`with an older version of paket. You can build and the dependency is here in the lock file and the csproj.

**Comment by forki** [comment] 2017-08-24 11:36
@matthid any ideas?

**Comment by forki** [comment] 2017-08-24 11:43
@pmiossec can you please upload a dependencies file that shows this?

**Comment by matthid** [comment] 2017-08-24 11:44
Can you change to the v2 url of the nuget feed? This is probably a duplicate of https://github.com/fsprojects/Paket/issues/2652.

But please provide the required info to be absolutely sure.

**Closed by matthid** 2017-08-24 11:44 UTC

**Comment by forki** [comment] 2017-08-24 12:18
V2

**Comment by pmiossec** [comment] 2017-08-24 12:55
I'm off until Monday that's why I would like to report the bug before (very sorry for that) . I will try to do that as soon as possible but at least on Monday... 

Thanks a lot for the quick diagnosis...

**Comment by forki** [comment] 2017-08-24 13:05
I hope on monday you go to work and everything is already fixed ;-)

**Comment by forki** [comment] 2017-08-24 14:51
ok I pushed a temporary workaround which automatically uses v2 feed. This gives us a bit time until we do the correct fix. you may need to use -f to invalidate the cache.

**Comment by pmiossec** [comment] 2017-08-24 15:31
I have tested the new version and the workaround works.

No need I provide some file or repository any more?

**Comment by forki** [comment] 2017-08-24 15:32
No. It's fine. We have a repro and we understood the root cause. It's
"just" a matter of providing a proper fix now..
Thanks for reporting and confirmation

Am 24.08.2017 5:31 nachm. schrieb "Philippe Miossec" <
notifications@github.com>:

**Comment by pmiossec** [comment] 2017-08-24 15:50
Ok. Thanks a lot.
