### ISSUE TITLE
Generate references mixes up scripts for groups

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#1839] opened 2016-07-29 16:20 UTC
I have the following dependencies file

```
group Main
source https://www.nuget.org/api/v2
framework net40
nuget Accord.MachineLearning
nuget Accord.Math
nuget FredsImageMagickScripts.TextCleaner
nuget Magick.NET-Q16-AnyCPU
nuget tesseract
nuget FSharp.Azure.StorageTypeProvider

group Automapper
source https://www.nuget.org/api/v2
framework net45
nuget Automapper
```

When I call `generate include scripts`, I would only expect to see a script in the net45 folder for Automapper. Instead I see scripts for all the packages in both net40 and net45.

**Comment by smoothdeveloper** [comment] 2016-07-29 18:28
@isaacabraham I'm not sure this is an issue, what would you expect to see calling `paket generate-include-scripts framework net46`?

With current implementation you get scripts for all valid frameworks and all packages for relevant groups, but nothing forces you to use those scripts, they are there for convenience.

I personally have use for generating scripts for arbitrary frameworks or for all framework found in paket.dependencies despite they might not be referenced in project files.

What is a bug though is that for net40, automapper shouldn't have a file since there is no valid assembly.

**Comment by isaacabraham** [comment] 2016-07-29 22:16
@smoothdeveloper I expected to only see generated reference scripts for the appropriate frameworks as specified by the groups. You're right - perhaps this is a more complex situation than just that as net40 libraries can run on e.g. net45 etc..

**Comment by matthid** [comment] 2016-07-30 09:35
I think this is related to: https://github.com/fsprojects/Paket/issues/1681
Note that you might still want to have other include scripts, the assemblies are downloaded anyway. Scenario:
- Develop for a new framework and restrict in paket.dependencies.
- Work with an older/other fsi build for a different framework and need include scripts...

**Comment by enricosada** [comment] 2018-01-24 11:12
Closing, by design

**Closed by enricosada** 2018-01-24 11:12 UTC
