### ISSUE TITLE
[Feature Request] Ability to pull git repositories into custom directory, not only paket-files

### ISSUE THREAD

**Issue by LendaVadym** [fsprojects/Paket#2076] opened 2016-12-13 22:18 UTC
It would be good if a developer would have a possibility to customize the directory where to pull the git repository that project depend on.
It will allow more flexibility to build projects directory structure. F.e. if one needs some kind of strict structure.

**Comment by forki** [comment] 2016-12-14 07:16
You can always add a custom step in your build script if you want to move things.

**Comment by LendaVadym** [comment] 2016-12-15 12:04
yep, right, but it would be good and much more clear if one can do it declaratively in paket.dependencies file. I would like to implement this feature if you don't mind.

**Comment by forki** [comment] 2016-12-15 12:20
Ok, but be warned. there are lot's of corner cases here

**Comment by kruncher** [comment] 2017-02-11 21:32
Is there already a way to simply override the path entirely?

i.e. I want the following project directory structure:
```
/
|--Assets/
|--|--Packages/
|--|--|--FooFromGithub/
|--|--|--BarFromBitbucket/
|--paket.dependencies
|--...
```

**Comment by enricosada** [comment] 2018-01-24 09:47
Closing, dupe of https://github.com/fsprojects/Paket/issues/1780

**Closed by enricosada** 2018-01-24 09:47 UTC
Labels: up-for-grabs
