### ISSUE TITLE
Include hashes in lock file, for NuGet packages too?

### ISSUE THREAD

**Issue by epsitec** [fsprojects/Paket#1287] opened 2015-12-03 20:54 UTC
I am wondering if I am the only person who'd like to make sure that the packages that get restored after a clean checkout from source control are indeed the ones that were used when the lock file was commited.

I feel incomfortable at the idea that somehow, somebody could hack the NuGet repository and that I would end up with other NuGet packages as what I used when I tested my code (e.g. when switching from testing to production, and rebuilding the code before it gets into the customer's hands).

I have the same issue with NPM... but maybe I am just paranoid?

**Comment by forki** [comment] 2015-12-03 20:55
Why would we want to do this?

**Comment by epsitec** [comment] 2015-12-03 21:00
To avoid poisoning a build system, and having paket detect that there is a mismatch between the binaries which were used when the lock file was commited, and when the product finally got built.

**Comment by forki** [comment] 2015-12-03 21:02
Mhm, yeah there are build system which do this. It's probably not a bad
idea.
I'm not completely against it.

**Comment by cdrnet** [comment] 2015-12-03 21:11
Wasn't there the problem that at least in the public NuGet gallery, NuGet packages could actually change their hashes over time (since some metadata was changeable)?

**Comment by forki** [comment] 2015-12-03 21:13
The issue was that we can't trust the hash that was given from the api. But
in theory we could hash the zip locally and pin that hash.

**Comment by epsitec** [comment] 2015-12-04 04:00
Computing a local hash and pinning it would be a great feature indeed.

**Comment by mlidbom** [comment] 2016-01-13 12:31
Doing this by default could cause very significant friction in some cases. 

An example: 
Developer works on Project A and B. Project B references A through a nuget package. 
Developer locally(on his machine) bumps project A and updates the package reference in project B. 
Developer's local version of A.nupkg is hashed and set as correct in the lock file.
Developer pushes the new version of A and B.
The CI server builds A and publishes the new version of A.nupkg.
The CI server tries to build B but fails since the hash of A.nupkg built by the CI server does not match the hash in the lock file.

**Comment by bacar** [comment] 2016-04-21 00:02
Isn't that an example of Paket doing _exactly_ the right thing; it _should_ complain because the downloaded package _isn't_ the one that was used at the time - ensuring you get the right dependency seems to be exactly the goal of Paket. 

I think this will become more important with Paket 3 network share caches as espoused here: https://fsprojects.github.io/Paket/caches.html
For this to be useful I basically have to grant everybody write access to the network share, which means anybody could come and stuff up existing cached packages.

**Comment by isaacabraham** [comment] 2016-04-21 00:05
You could also use a local / network cache to provide a trusted repository of your nuget dependencies.

**Comment by smoothdeveloper** [comment] 2016-04-21 00:09
If this is a feature added, it should be optional (and easy to discard for testing / practical purpose in development environment) and not the default, I'm not too much into huge lock file :smile: and extra cost on day to day workflow using paket.

I also sometimes just erase assemblies with arbitrary changes and know that paket don't get too much in the way by default when I'm testing out something.

It seems that if the concern is stringent security, relying on external nuget repository is a no-go.

`paket.hash`?

**Comment by bacar** [comment] 2016-04-21 00:10
For it to be "trusted", I would need the hashes in my .lock file. (Assume only my team can write to my lock file, but my whole organisation wishes to share the cache).

**Comment by bacar** [comment] 2016-04-21 00:11
My concern is repeatability, not security.

**Comment by bacar** [comment] 2016-04-21 00:12
Agree that it should be optional, but feel it ought to be opt-out if you want looser safety...

**Comment by smoothdeveloper** [comment] 2016-04-21 00:52
@bacar: about safety do you ship strongly named assemblies / only depend on strong named assemblies?

It easy to defeat the point of checking packages against hash if the binaries aren't strong named.

I'm backing off the topic anyways, great if a PR comes along to implement this and it can be put as an option (enabled by default I guess).

**Comment by bacar** [comment] 2016-04-22 23:07
When I say "safety", I'm talking about confidence that I have good repeatability - not security.

**Comment by llehn** [comment] 2016-09-01 14:44
This is symptom-fixing. If you don't trust your nuget server, then even a packaga with a valid hash could be malicious, lets say it could contain code which would wait 5 weeks and then do bad things. You can never know. 

The solution is not adding hashes but making sure nobody can overwrite nuget packages and all packages are safe. So get your own nuget server, disallow package overwriting for packages created by your organization. Only add packages from the nuget.org repository to your repository when they meet your security criteria. You can't have "a bit" of paranoia, either you trust your nuget server for all packages, or you don't for any. Thats how security works.

Doing that locally on _every_ developer's PC is an absolutely wrong approach. It's like implementing security in a web application on the client side - you end up in a total mess, which is still flawed.

**Comment by bacar** [comment] 2016-09-01 21:59
Again, I raise the matter of network share caches used as a source. By (Paket) design, these need to be writable by users of Paket to be useful, which leaves them wide open to accidental, misguided or malicious misuse. Paket supports and encourages use of something that *cannot* (usually) easily be remedied by "the Nuget server".


This has nothing to do with security or maliciousness. It's purely about repeatability. (From my perspective).

**Comment by llehn** [comment] 2016-09-01 22:48
I was not aware of that network share caching. And I don't think this function is a good idea. You can either set the permissions to prevent modifications if existing files. Or spend about 5 minutes to install the free version of proget which will cache the packages for you. Klondike will do the same and it's OSS. I would suggest to stop using that network share cache functionality. It's broken by design, from security point of view. It's a convenience feature, as most convenience features it's insecure. And network shares are a bad idea in most cases.

Dropping security aspect seems wrong, since repeatability does require security. 

But the main point is does same version mean same content? It could, but that's entirely up to you. Or me. Or him. 

I could imagine that information as a hint (dude! package changed), not as a part of normal workflow, maybe as an extra command. Or an extra tool which validates the build, for the very paranoid ones.

From a practical point of view, it takes sooo much less time to setup a nuget server or fix share permissions than to add a whole bunch of complexity to Paket for a very questionable feature, which would just burn CPU cycles for nothing for 99.99% of users.

**Comment by bacar** [comment] 2016-09-01 22:55
Working environments differ. There are myriad corporations where getting hold of server hardware or getting software approved to run on it is painful and complex. Some environments have strong technical, legal or regulatory requirements regarding the repeatability of their builds. There is no absolute truth that getting proget is easier or better than caching or hashing.

I think we can safely conclude that some people would find this feature tremendously useful, and others would not, but I don't think having it as an option, at least, is harmful.

**Comment by llehn** [comment] 2016-09-01 23:08
I agree with having it wouldn't be harmful as an option. I do think that repeatable builds should be handled by build systems. I see the point of different working environments but I don't think this justifies adding complexity just in case people can't get their hands on proper tools for the job. For those cases hacking a hash checker would be appropriate. But those are just my opinions, which, as working environments, differ from others.

**Comment by matthid** [comment] 2017-09-03 12:20
In principle I agree with @llehn. But I don't see it as security feature at all. 

There are several caches throughout the the place and a hash could detect errors in your workflow or in your usage of `paket.local` or paket bugs writing the wrong stuff into the wrong cache. So yeah it is more about predictability and consistency and finding issues easier. I also would suggest this to be a warning by default - probably with an option to make it an error.

**Comment by enricosada** [comment] 2018-01-24 13:57
Closing. Dupe of https://github.com/fsprojects/Paket/issues/1546

**Closed by enricosada** 2018-01-24 13:57 UTC
Labels: enhancement, up-for-grabs
