### ISSUE TITLE
Paket should not rewrite everything (*sproj, *.config)

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#2408] opened 2017-06-10 11:22 UTC
### Description

Paket is just recursively rewriting everything it finds ("fsproj", "app.config", "web.config")

for example: https://github.com/fsprojects/Paket/issues/678

To be honest I never liked this behavior, maybe we should just limit operations to locations where we can find a `paket.references` (and arguably subfolders in depth 1) ...

This has come up several times over the years and I don't like doing a blacklisting strategy as supposed in #678 (the `node_modules` folder in that case). Instead I'm opening this issue to discuss (and probably implement) the feature.

It might be a breaking change for some projects depending on this.

**Comment by 0x53A** [comment] 2017-06-10 11:34
You can add an empty paket.dependencies file, then it will ignore that folder and any subfolders.

**Comment by matthid** [comment] 2017-06-10 11:43
So we tell people to an empty file to all folders they don't want paket to touch. (I guess you mean `paket.references` correct?).
The folder might be controlled by some other tooling which cannot handle a `paket.references` file in there?

**Comment by 0x53A** [comment] 2017-06-10 18:07
> So we tell people to an empty file to all folders they don't want paket to touch. 

That's what I am doing at the moment. I didn't mean that there is nothing to do - just wanted to point out what is possible at the moment.

> I guess you mean paket.references correct?

No, paket.dependencies.  Because paket then thinks that directory tree is controlled by a different dependency list and skips it. Maybe paket.references also works? No idea.

-------

One option may be to pass a solution to the install process? It would then search for a paket.dependencies (first same directory, then up), parse the sln file and work on only these projects?

That would mean that projects not contained in the solution would not be touched - but if you want that, you can fall back to folder based install.

**Comment by enricosada** [comment] 2018-01-24 09:55
Closing, dupe of https://github.com/fsprojects/Paket/issues/2054

**Closed by enricosada** 2018-01-24 09:55 UTC
Labels: bug
