### ISSUE TITLE
Add support for license property in paket.template file

### ISSUE THREAD

**Issue by Kiryushin-Andrey** [fsprojects/Paket#3564] opened 2019-04-30 16:23 UTC
The licenseUrl attribute in nuspec files is being [deprecated ](https://github.com/NuGet/Announcements/issues/32) by Microsoft. Paket needs to support the proposed alternative - a [license](https://docs.microsoft.com/en-us/nuget/reference/nuspec#license) attribute. So we should be able to add license attribute to paket template file and get it built into the resulting nuspec in the package.

**Comment by forki** [comment] 2019-05-01 07:57
We would love to see a pull request here

**Comment by cdrnet** [comment] 2019-05-01 10:59
Related: #3475

**Comment by cartermp** [comment] 2019-11-10 06:13
I think we can close #3475 as a duplicate of this. I'd be happy to take a crack at this along with #3707. Is there a best place to look?

**Closed** 2019-11-10 07:17 UTC
Labels: up-for-grabs
