### ISSUE TITLE
5.87.0 and upwards removes needed csproj assembly references

### ISSUE THREAD

**Issue by Allon-Guralnek** [fsprojects/Paket#2657] opened 2017-08-24 14:13 UTC
### Description

When using `paket update` with a version above 5.86.1, such as versions 5.87.0, 5.89.0 and 5.89.1, it removes certain assembly references that are required which cause compilation errors. Reverting to 5.86.1 and running `paket update` resolved those issues.

### Repro steps

I'm hoping included logs from each `paket update` run, the dependency files and the before and after lock files might help diagnose the problem. If it doesn't I can try to create a reproduction, but it may involve a lot of work.

Here is a zip files:

[PaketIssue.zip](https://github.com/fsprojects/Paket/files/1249067/PaketIssue.zip)

It includes:
* paket.dependencies
* paket.references of the two projects that failed to compile with the latest Paket (`Gator` and `Gator.FunctionalTests`)
* Before and after files of:
    - The paket.lock file
    - The csproj of both projects
    - The log when running `paket update`

In `Gator.csproj`, compilation fails because `Microsoft.Framework.OptionsModel` and `Microsoft.Framework.Caching.Abstractions` references are missing.

In `Gator.FunctionalTests.csproj`, compilation fails because `System.Reactive.Core` is missing.

### Known workarounds

Revert to Paket version 5.86.1.

**Comment by forki** [comment] 2017-08-24 14:16
I believe this is a duplicate of #2652. We are already working on a solution. If you use v2 nuget url in your paket.dependencies file then it should work as temporary workaround. In any case thanks for reporting. We hope to provide a fix soon

**Closed by forki** 2017-08-24 14:16 UTC

**Comment by forki** [comment] 2017-08-24 14:51
ok I pushed a temporary workaround which automatically uses v2 feed. This gives us a bit time until we do the correct fix. you may need to use -f to invalidate the cache.
