### ISSUE TITLE
Why doesn't restore fail on out of sync?

### ISSUE THREAD

**Issue by sarudak** [fsprojects/Paket#1957] opened 2016-10-11 00:01 UTC
When I run paket restore after a change to the paket.dependencies file I get 'paket.dependencies and paket.lock are out of sync' and it suggests I do an install or update. However the packet restore proceeds normally and does not fail. Is there a reason it behaves like this? It seems failure would be the desired behavior unless you specified otherwise however there's no option to force a failure when the lock file is out of sync. This is problematic for us because it allows forgetful developers to commit mismatched files that don't fail locally and don't fail the build but don't necessarily have the expected behavior.

**Comment by forki** [comment] 2016-10-11 06:42
This is by design. We always restore exactly the stuff that's given in the lock file.

**Comment by forki** [comment] 2016-10-11 06:43
That said, I think a special command line parameter that fails the build in such a situation would be accepted.

**Comment by sarudak** [comment] 2016-10-13 18:03
https://github.com/fsprojects/Paket/pull/1963

**Comment by sarudak** [comment] 2016-10-13 23:26
I seem to be having integration tests failing on linux but not on windows and I haven't been able to replicate locally.

**Comment by enricosada** [comment] 2018-01-24 10:47
Closing, added by @sarudak as `--fail-on-checks`

**Closed by enricosada** 2018-01-24 10:47 UTC
