### ISSUE TITLE
dotnet restore on solutions slow

### ISSUE THREAD

**Issue by seanamosw** [fsprojects/Paket#2595] opened 2017-08-10 00:52 UTC
### Description

Running `dotnet restore` on .sln files with a few projects becomes very slow.
This is a result of paket running individual restores for each project sequentially. As the amount of projects in the solution grows, the restore time increases.
The restore target also seems to run twice per project.

This has a heavy impact on projects where the workflow involves frequently running the build script, which in turn will often run a `dotnet restore`.

Example restore output from a .sln with 6 projects:
```
dotnet "restore"
  Paket version 5.84.3
  The profile 'portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81' is not a known profile. Please tell the package author.
  Performance:
   - Disk IO: 275 milliseconds
   - Runtime: 2 seconds
  Paket version 5.84.3
  The profile 'portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81' is not a known profile. Please tell the package author.
  Performance:
   - Disk IO: 419 milliseconds
   - Runtime: 2 seconds
  Paket version 5.84.3
  The profile 'portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81' is not a known profile. Please tell the package author.
  Performance:
   - Disk IO: 274 milliseconds
   - Runtime: 2 seconds
  Paket version 5.84.3
  The profile 'portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81' is not a known profile. Please tell the package author.
  Performance:
   - Disk IO: 266 milliseconds
   - Runtime: 2 seconds
  Paket version 5.84.3
  The profile 'portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81' is not a known profile. Please tell the package author.
  Performance:
   - Disk IO: 280 milliseconds
   - Runtime: 2 seconds
  Paket version 5.84.3
  The profile 'portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81' is not a known profile. Please tell the package author.
  Performance:
   - Disk IO: 292 milliseconds
   - Runtime: 2 seconds
  Paket version 5.84.3
  The profile 'portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81' is not a known profile. Please tell the package author.
  Performance:
   - Disk IO: 298 milliseconds
   - Runtime: 2 seconds
  Paket version 5.84.3
  The profile 'portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81' is not a known profile. Please tell the package author.
  Performance:
   - Disk IO: 348 milliseconds
   - Runtime: 2 seconds
  Paket version 5.84.3
  The profile 'portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81' is not a known profile. Please tell the package author.
  Performance:
   - Disk IO: 369 milliseconds
   - Runtime: 2 seconds
  Paket version 5.84.3
  The profile 'portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81' is not a known profile. Please tell the package author.
  Performance:
   - Disk IO: 296 milliseconds
   - Runtime: 2 seconds
  Paket version 5.84.3
  The profile 'portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81' is not a known profile. Please tell the package author.
  Performance:
   - Runtime: 1 second
```

### Expected behavior

Ideally restore time should not increase per project added. At least not significantly.
Restore time without paket and multiple projects remains fast.

### Actual behavior

Restore time increases significantly with each new project.

**Comment by matthid** [comment] 2017-08-10 05:15
We are playing around with the idea of having a single restore for all projects and some hash or file to detect changes on the lockfile (to make second restore a noop).

A PR would be highly appreciated at this time, as there are some other things to take care of first...

**Comment by forki** [comment] 2017-08-10 05:16
Duplicate of https://github.com/fsprojects/Paket/issues/2578

**Closed by forki** 2017-08-10 05:16 UTC
