### ISSUE TITLE
Pinning a version does not seem to work anymore

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [fsprojects/Paket#1450] opened 2016-02-02 17:10 UTC
In my _packet.dependencies_ file, I have:

```
nuget EnterpriseLibrary.SemanticLogging ~> 2
```

But I keep being offered this:

```
Outdated packages found:
  Group: Main
    * EnterpriseLibrary.SemanticLogging 2.0.1406.1 -> 6.0.1302
```

This used to work. I think it started misbehaving about 2 weeks ago.

As background, there was once a version [6.0.1302](https://libraries.io/nuget/EnterpriseLibrary.SemanticLogging/6.0.1302), but then they changed their numbering and [2.0.1406.1](https://www.nuget.org/packages/EnterpriseLibrary.SemanticLogging/) is now the latest. To work around this anomaly, I've been pinning this package using `~> 2` for some time, and this used to work fine, but now it doesn't.

My complete _packet.dependencies_ file is:

```
redirects: on

source https://api.nuget.org/v3/index.json
source https://www.nuget.org/api/v2

framework: net461

nuget WindowsAzure.Storage

# Not sure what this one is for, or whether I even need it.
nuget Nuget.CommandLine

nuget FSharp.Azure.Storage
nuget FSharp.Collections.ParallelSeq
nuget FSharp.Quotations.Evaluator
nuget FSharpx.Extras

nuget Newtonsoft.Json

nuget Microsoft.Owin.SelfHost
nuget Microsoft.Owin.StaticFiles

nuget Mono.Cecil
nuget WebSharper
nuget WebSharper.GlMatrix
nuget WebSharper.Owin
nuget WebSharper.UI.Next

nuget EnterpriseLibrary.SemanticLogging ~> 2
nuget EnterpriseLibrary.SemanticLogging.EventSourceAnalyzer
```

**Comment by forki** [comment] 2016-02-02 17:23
will take a look tomorrow

**Comment by forki** [comment] 2016-02-02 17:25
to make things easier: can you try to use older version and find the first version that breaks it? thx

**Comment by forki** [comment] 2016-02-02 19:28
mhm I can't reproduce:

![image](https://cloud.githubusercontent.com/assets/57396/12761451/576f895e-c9eb-11e5-8fae-b533274c5b83.png)

Btw: removing one of the sources will speed things up for you. (we automatically convert to v3 internally so removing `source https://api.nuget.org/v3/index.json` is fine)

**Comment by Bananas-Are-Yellow** [comment] 2016-02-03 08:31
Forgot to mention that I'm using Paket for Visual Studio, rather than command line paket.

Anyway, if I use command line paket (`paket outdated` command), it works, and I get the same output as you. However if I use Paket for Visual Studio, it does not work, _but_ if I remove `source https://api.nuget.org/v3/index.json`, then it _does_ work, although the output is slightly different from yours (note the two lines about `EnterpriseLibrary.SemanticLogging`):

```
Resolving packages for group Main:
 - EnterpriseLibrary.SemanticLogging 6.0.1302
 - EnterpriseLibrary.SemanticLogging 2.0.1406.1
 - EnterpriseLibrary.SemanticLogging.EventSourceAnalyzer 2.0.1406.1
 - FSharp.Azure.Storage 2.1.0
 - FSharp.Collections.ParallelSeq 1.0.2
 - FSharp.Quotations.Evaluator 1.0.7
 - FSharpx.Extras 1.10.3
 - Microsoft.Owin.SelfHost 3.0.1
 - Microsoft.Owin.StaticFiles 3.0.1
 - Mono.Cecil 0.9.6.1
 - Newtonsoft.Json 8.0.2
 - Nuget.CommandLine 3.3.0
 - WebSharper 3.6.7.227
 - WebSharper.GlMatrix 3.6.6.252
 - WebSharper.Owin 3.6.5.120
 - WebSharper.UI.Next 3.6.6.202
 - WindowsAzure.Storage 6.2.0
 - Microsoft.Data.OData 5.7.0
 - Microsoft.Data.Services.Client 5.7.0
 - Microsoft.Owin 3.0.1
 - Microsoft.Owin.Diagnostics 3.0.1
 - Microsoft.Owin.FileSystems 3.0.1
 - Microsoft.Owin.Host.HttpListener 3.0.1
 - Microsoft.Owin.Hosting 3.0.1
 - FSPowerPack.Linq.Community 3.0.0
 - FSharpx.Async 1.12.0
 - FSharpx.Collections 1.13.4
 - Microsoft.Azure.KeyVault.Core 1.0.0
 - Owin 1.0.0
 - Microsoft.Data.Edm 5.7.0
 - System.Spatial 5.7.0
 - FSharp.Core 4.0.0.1
 - FSharp.Control.AsyncSeq 2.0.3
 - FSPowerPack.Core.Community 3.0.0
No outdated packages found.
Ready
```

So I've removed `source https://api.nuget.org/v3/index.json` and all is well.

Thanks.

**Comment by forki** [comment] 2016-02-03 08:52
can you send me your paket.lock file?

**Comment by Bananas-Are-Yellow** [comment] 2016-02-03 09:00
Renamed to `paket.txt` in order to upload it:

[paket.txt](https://github.com/fsprojects/Paket/files/115347/paket.txt)

**Comment by forki** [comment] 2016-02-03 09:10
are you on the latest plugin?

**Comment by Bananas-Are-Yellow** [comment] 2016-02-03 09:22
Yes I think this is the latest version:

![image](https://cloud.githubusercontent.com/assets/5648989/12777829/2ebe5456-ca57-11e5-9887-0ad75ed472f9.png)

But the paket.lock file shows a 'Date modified' of 14-Jan-2016.

I'm trying to remember the exact sequence today. If I remember correctly, I tried `paket outdated` and it said there was an error in the lock file. Then I ran `paket.bootstrap.exe`, which downloaded 2.48.1.0 (although if I have the latest plugin, perhaps I already had this version?). Then I ran `paket outdated` and it ran. In any case, the lock file hasn't been updated, because there haven't been any new packages to download since 14-Jan-2016.

**Comment by Bananas-Are-Yellow** [comment] 2016-02-15 19:02
It's happening again.

![image](https://cloud.githubusercontent.com/assets/5648989/13057767/3c1cc7cc-d416-11e5-934f-62865f6d8f3b.png)

```
Resolving packages for group Main:
 - EnterpriseLibrary.SemanticLogging 6.0.1302
 - EnterpriseLibrary.SemanticLogging.EventSourceAnalyzer 2.0.1406.1
 - FSharp.Azure.Storage 2.1.0
 - FSharp.Collections.ParallelSeq 1.0.2
 - FSharp.Quotations.Evaluator 1.0.7
 - FSharpx.Extras 1.10.3
 - Microsoft.Owin.SelfHost 3.0.1
 - Microsoft.Owin.StaticFiles 3.0.1
 - Mono.Cecil 0.9.6.1
 - Newtonsoft.Json 8.0.2
 - Nuget.CommandLine 3.3.0
 - WebSharper 3.6.10.230
 - WebSharper.GlMatrix 3.6.8.254
 - WebSharper.Owin 3.6.9.124
 - WebSharper.UI.Next 3.6.8.204
 - WindowsAzure.Storage 6.2.0
 - Microsoft.Data.OData 5.7.0
 - Microsoft.Data.Services.Client 5.7.0
 - EnterpriseLibrary.WindowsAzure.TransientFaultHandling 5.1.1212
 - Microsoft.Owin 3.0.1
 - Microsoft.Owin.Diagnostics 3.0.1
 - Microsoft.Owin.FileSystems 3.0.1
 - Microsoft.Owin.Host.HttpListener 3.0.1
 - Microsoft.Owin.Hosting 3.0.1
 - FSPowerPack.Linq.Community 3.0.0
 - FSharpx.Async 1.12.0
 - FSharpx.Collections 1.14.0
 - Microsoft.Azure.KeyVault.Core 1.0.0
 - Owin 1.0.0
 - Microsoft.Data.Edm 5.7.0
 - System.Spatial 5.7.0
 - TransientFaultHandling.Core 5.1.1209.1
 - EnterpriseLibrary.Common 6.0.1304
 - FSharp.Core 4.0.0.1
 - FSharp.Control.AsyncSeq 2.0.3
 - FSPowerPack.Core.Community 3.0.0
Outdated packages found:
  Group: Main
    * EnterpriseLibrary.SemanticLogging 2.0.1406.1 -> 6.0.1302
Ready
```

[paket.txt](https://github.com/fsprojects/Paket/files/131273/paket.txt)

I've not done anything with the command line paket. It might be that running ```paket.bootstrap.exe``` will fix it, but in case you want me to experiment first, I'll not run that for now.

**Comment by forki** [comment] 2016-03-02 13:22
is there a way for me to reproduce?

**Comment by Bananas-Are-Yellow** [comment] 2016-03-02 14:10
It works today. I noticed that Paket for VS was updated today.

I have a hunch that there might be something random about this. If it happens again, I'll let you know.

**Comment by enricosada** [comment] 2018-01-24 13:41
> It works today. I noticed that Paket for VS was updated today.

Closing

**Closed by enricosada** 2018-01-24 13:41 UTC
Labels: needs-repro
