### ISSUE TITLE
Paket pack with symbols fails for \**\* wildcard (Recursive folders)

### ISSUE THREAD

**Issue by franknarf8** [fsprojects/Paket#1462] opened 2016-02-05 19:42 UTC
Hello,

Follow up to the following issue : https://github.com/fsprojects/Paket/issues/1396 @pms1969
It works for the use cases described in issue 1396, but now, I think it now fails to compute the
`%(RecursiveDir)` macro.

```
<Compile Include="GENERATED_CS_LINKED\**\*.cs">
      <Link>GENERATED_CS_LINKED\%(RecursiveDir)%(FileName).cs</Link>
</Compile>
```

Thanks again!

**Comment by franknarf8** [comment] 2016-02-05 19:47
Actually, I've just tried the following it fails with `Illegal characters in path.` :
```
<Compile Include="GENERATED_CS\**\*.cs" />
```
So I guess it is related with the `\**\*` wildcard.

**Comment by pms1969** [comment] 2016-02-05 20:32
I didn't design/code it with globbing in mind.  As far as I could tell, VS
doesn't support it, tho, I'm happy to stand corrected.  I wasn't sure about
providing functionality that is so far out of scope for the idea, but I can
see that it would be useful if you weren't in VS entirely.

**Comment by franknarf8** [comment] 2016-02-05 20:36
Yeah, this some kind of edge case. Those files do not appear in the VS Solution Explorer, but they are compiled during a VS build.

**Comment by enricosada** [comment] 2018-01-24 13:38
Closing, dupe of https://github.com/fsprojects/Paket/issues/2889

**Closed by enricosada** 2018-01-24 13:38 UTC
