### ISSUE TITLE
Unable to find the file 'Newtonsoft.Json.dll' is being thrown when running inside an official fsharp docker container.

### ISSUE THREAD

**Issue by vladkosarev** [fsprojects/Paket#1620] opened 2016-04-18 19:03 UTC
### Description

Unable to find the file 'Newtonsoft.Json.dll' is being thrown when running inside an official fsharp docker container.
### Repro steps

Here is the image - https://hub.docker.com/r/vkosarev/suave/
Here is the app - https://github.com/vladkosarev/docker-suave/blob/5cf674ba213cb26b572b171106450f13ad7817e5/app.fsx

Line 34 is what fails (#r "paket.exe")

app.fsx works fine on both mac and pc but does not seem to work with official fsharp docker container.
### Expected behavior

fsharpi app.fsx should start a web server.
It works fine on mac and windows.
### Actual behavior

mbp:docker-suave vlad$ docker run vkosarev/suave
/app/app.fsx(34,1): error FS0078: Unable to find the file 'Newtonsoft.Json.dll' in any of
 /usr/lib/mono/4.5
 /app
 /usr/lib/mono/4.5/
mbp:docker-suave vlad$

**Comment by forki** [comment] 2016-04-18 19:07
But paket.exe shouldn't depend on newtonsoft.json. We ilmerge that thing.
/cc @henrikfeldt

**Comment by vladkosarev** [comment] 2016-04-18 19:19
That's what @smoothdeveloper told me on gitter but you are welcome to run this and see for yourself.

**Comment by forki** [comment] 2016-04-18 19:21
What if you put the paket.exe into docker image? I think @haf did that in
the official suave image.

**Comment by vladkosarev** [comment] 2016-04-18 19:23
If I remove all of that 'dynamic' paket magic in the script things work just fine (with paket.exe and dependencies). I just wanted to have a full 1 script file docker web server. This isn't a huge issue, just an annoyance.

**Comment by forki** [comment] 2016-04-18 19:24
Yeah it's actually really really strange. I did similar thing like a
million times. But never inside docker.

**Comment by vladkosarev** [comment] 2016-04-18 19:25
Yea, works fine in windows and macos.

**Comment by forki** [comment] 2016-04-18 19:28
Is there a way to analyze the dependencies of that downloaded file to
understand why it's trying to load that? Also are you sure it's not later
when fsharp.data or something gets used?

**Comment by vladkosarev** [comment] 2016-04-18 19:43
I am not sure on dependency analysis.

As for that line throwing I am sure. I removed everything past that line and the same issue. I just copy/pasted the snippet from paket docs to make sure. That snippet fails with the same error inside docker container.

**Comment by forki** [comment] 2016-04-18 19:55
That is so weird. I have no idea.

**Comment by haf** [comment] 2016-04-18 20:23
You could try running https://github.com/mikehadlow/AsmSpy before line 34 on the downloaded exe file.

The container is built from this commit: https://github.com/fsprojects/docker-fsharp/commit/cdbab855f3fce8a0fc4ccdf23efbc88c96b2bcd1

I have never been able to make original packaging with ilmerge or ilrepack on mono work myself. You'll find my issues scattered in their respective repos.

**Comment by forki** [comment] 2016-04-19 07:10
hey @gluck, did you hear about such issues with IL-Repack before (not saying it is a IL-Repack issue). But somehow the mono inside of docker seems to thick it's not completely packaged.

**Comment by gluck** [comment] 2016-04-19 11:14
no clue, I checked the latest paket build (https://github.com/fsprojects/Paket/releases/download/2.62.1/paket.exe) and peverify raises no missing ref, neither does pedump, and monodis disassembly shows no reference to NS.Json lib.

At this point I'd check whether this is actually the file being used within docker (and not some other version - do you remember ever shipping a version referencing NS.Json ?).

Other than that, the managed resources `FSharpOptimizationData` & `FSharpSignatureData` still retain some reference to the unmerged assemblies, but I don't know how/when/if they are used (`--nointerfacedata` may help ?)

**Comment by smoothdeveloper** [comment] 2016-04-19 11:37
Sounds dumb but is there any code which would attempt to load that assembly by name in merged code?

@vladkosarev do you have actual complete stack trace? maybe using `--verbose`?

**Comment by gluck** [comment] 2016-04-19 12:34
I checked string references as well (in `paket.exe`), used only as trace source parameter (shouldn't trigger a DLL load AFAIK), and nothing else.

**Comment by vladkosarev** [comment] 2016-04-19 12:54
@gluck About the file version - I actually tried specifically referencing the version from 2.62.1 link and it was the same issue. Also, I tried a much older version of paket and that worked as far as referencing paket (it didn't work for some nuget stuff so I switched to latest).

**Comment by Indy9000** [comment] 2016-05-17 11:14
Noticed this issue couple of days ago with a fresh mono/fsharp/ etc. install.
https://pbs.twimg.com/media/CiibDWsWsAExWxg.jpg

**Comment by haf** [comment] 2016-05-17 13:15
I would suggest paket to migrate over to Chiron from Newtonsoft and take a dependency on it as a file, like Logary does it.

**Comment by forki** [comment] 2016-05-17 13:20
we can't easilly use file dependencies since the bootsprapper (and that one is hard to switch over the full ecosystem) is only downloading paket.exe - so in order to not break everybody we need to ilmerge/ilrepack the stuff. we also have other inlined dependencies.

**Comment by smoothdeveloper** [comment] 2016-05-17 13:31
As far as I remember, `#r "paket.exe"` also fails on windows (or rather it doesn't compile), the way to do this is to `#r "Paket.Core.dll"` which is a separate nuget package.

**Comment by gluck** [comment] 2016-05-17 13:31
FTR I looked at this issue some time ago, and it was easily reproducible on docker. Unfortunately it was also impossible to troubleshoot (no stack details) and I didn't find how to compile paket (or any fsproj project) with `--nointerfacedata` to give it a try.

@Indy9000 reproduces it outside of docker (AFAICT), so it might _simply_ be related to the version of mono/fsharp being used.

**Comment by haf** [comment] 2016-05-17 13:34
@forki Can't you just copy and paste the two files then?

**Comment by forki** [comment] 2016-05-17 13:34
@haf what do you mean?

**Comment by haf** [comment] 2016-05-17 13:35
I mean that you can internalise the source code rather than ilmerging it and when it comes to namespaces shared in the GAC, move them to your own namespaces.

**Comment by forki** [comment] 2016-05-17 13:39
yeah we used chessie in such a way (by using paket's file dependency feature), but that gave issues when others wanted to use Paket.Core.

**Comment by haf** [comment] 2016-05-17 13:39
I rewrite the namespaces too, then it's not an issue.

**Comment by forki** [comment] 2016-05-17 13:40
it is for chessie since paket.core is returning Chessie's Result type

**Comment by smoothdeveloper** [comment] 2016-05-17 13:41
Can we change the sample to actually call paket.exe to download Paket.Core, then run `paket generate-include-scripts`, then `#load "include.paket.core.fsx"`?

I know this is more involved than initially, but it could work out of the box (given using paket 3).

**Comment by forki** [comment] 2016-05-17 13:45
but @Indy9000 has issue with paket.exe right? It doesn't work for him because it's complaing the missing newtonsoft

**Comment by smoothdeveloper** [comment] 2016-05-17 13:47
@forki my idea would rely on starting a System.Diagnostic.Process to run paket.exe.

I know this is annoying and would make the bootstrapping process way more verbose than what we initially had.

This is in the meantime we figure out the issue with ilmerge.

**Comment by forki** [comment] 2016-05-17 13:50
@smoothdeveloper I think @Indy9000 can't use paket at all anymore.

**Comment by Indy9000** [comment] 2016-05-17 16:32
I'm *guessing* paket is broken for all new installs (with fresh Mono/.Net & F#) at the mo, unless you have a preferred installer which installs json dependency first. But it's convenient to bootstrap and get going with a code fragment at the top of the script as I've done. It's minimal and deployable where ever you have the basics (Mono/.Net & F#).

**Comment by forki** [comment] 2016-05-17 16:42
Can you please provide your repro steps?

**Comment by Indy9000** [comment] 2016-05-17 17:08
ubuntu 16.04 LTS - didn't have mono or fsharp installed

followed the steps here to install Mono:
http://fsharp.org/use/linux/
http://www.mono-project.com/docs/getting-started/install/linux/
which basically add the mono repo to apt-get 
and then
sudo apt-get update && sudo apt-get install mono-complete fsharp

and the script fragment found here: ( change the \ to / on the paket path)
https://github.com/Indy9000/twitter-local/blob/master/twitter-local.fsx

**Comment by forki** [comment] 2016-05-17 17:13
Ok so it's only from within a script? But calling it from command line
works?

**Comment by Indy9000** [comment] 2016-05-17 17:44
yes after chmod +x
version 2.64.3.0

**Comment by nickbabcock** [comment] 2016-06-30 17:07
I fixed the issue by using the [current master branch of the fsharp repo](https://github.com/fsharp/fsharp/tree/d518f91418ef43a61875a5d932147b97fd0f47f3) with Mono 4.4.1 (not sure if Mono version matters, thought I'd include it for completeness)

The one minor thing I had to change is to switch `#r "paket.exe"` to `#r "paket.dll"` as:

> error FS0226: The file extension of 'paket.exe' is not recognized. Source files must have extension .fs, .fsi, .fsx, .fsscript, .ml or .mli.

This is the cross-platform solution that I have come up with:

```fsharp
open System
open System.IO

Environment.CurrentDirectory <- __SOURCE_DIRECTORY__

if not (File.Exists "paket.dll") then
    let url = "https://github.com/fsprojects/Paket/releases/download/3.3.6/paket.exe"
    use wc = new Net.WebClient()
    wc.DownloadFile(url, "paket.dll")

#r "paket.dll"

Paket.Dependencies.Install """
source https://nuget.org/api/v2
nuget Suave
""";;
```

**Comment by forki** [comment] 2016-06-30 18:40
So can we close this?

**Comment by nickbabcock** [comment] 2016-06-30 20:51
I think we can tentatively close this. It's not an ideal solution, as the F# out of the box in the Ubuntu `mono-complete` package can't reference paket in interactive mode, but it *is a* solution to this issue.

**Comment by forki** [comment] 2016-07-01 07:50
so can we fix the container?!

**Comment by nickbabcock** [comment] 2016-07-01 17:42
Possibly. Through testing I've found that [fsharp 4.0.1.1](https://github.com/fsharp/fsharp/releases/tag/4.0.1.1) fixes the referencing issue (see https://github.com/fsharp/fsharp/issues/483). Bumping the [fsharp dockerfile](https://github.com/fsprojects/docker-fsharp/blob/master/4.0.0.4/Dockerfile) to 4.0.1.1 caused an infinite loop on [`Install`](https://github.com/fsprojects/Paket/blob/be14185e65004077d7b10e6c70eae62c94e22442/src/Paket.Core/PublicAPI.fs#L153-153)

```fsharp
(* snip downloading/referencing paket) *)
open Paket
let dependencies = Dependencies.Locate(__SOURCE_DIRECTORY__)
dependencies.Add "Suave"
dependencies.Install false
```
Varying mono versions did not affect behavior.

paket.lock and paket.dependencies are generated fine. Even executing `mono paket.exe install` hangs :confused:

**Comment by Indy9000** [comment] 2016-11-20 23:17
Seems like this problem still persists, even with the workarounds proposed above.

```
open System
open System.IO

Environment.CurrentDirectory <- __SOURCE_DIRECTORY__
//Bootstrap paket
let dst = ".paket/paket.dll"
if not (File.Exists dst) then
    let urlRef = @"https://fsprojects.github.io/Paket/stable"
    use wc = new Net.WebClient()
    let url = wc.DownloadString(urlRef)
    let tmp = Path.GetTempFileName()
    wc.DownloadFile(url, tmp)
    Directory.CreateDirectory(".paket") |> ignore
    File.Move(tmp, dst)
 
//Resolve and install the packages
 
#r ".paket/paket.dll"

Paket.Dependencies.Install """
source https://nuget.org/api/v2
nuget FsLab
"""

```


results in 

> /home/indy9000/dev/fable/rl-bot/temp.fsx(19,1): error FS007
> 8: Unable to find the file 'Newtonsoft.Json.dll' in any of
>  /usr/lib/mono/4.5
>  /home/indy9000/dev/fable/rl-bot
>  /usr/lib/cli/fsharp/

**Comment by forki** [comment] 2016-11-21 07:31
https://github.com/fsharp/FAKE/issues/1423 is it related?

**Comment by Indy9000** [comment] 2016-11-21 08:43
Unlikely, this was without Fake being used at all.

**Comment by enricosada** [comment] 2018-01-24 11:46
Closing, fixed. 

Please open another bug if issue happen again

**Closed by enricosada** 2018-01-24 11:46 UTC
