### ISSUE TITLE
Paket doesn't add .NET Standard 2.0 library reference to .NET Framework 4.6.1 .csproj

### ISSUE THREAD

**Issue by smolyakoff** [fsprojects/Paket#2722] opened 2017-09-04 19:00 UTC
### Description

Paket doesn't add reference to `Microsoft.Extensions.Configuration` when I add it to paket.references file of the .NET Framework console application project.

### Repro steps

[PaketReferencesIssue2.zip](https://github.com/fsprojects/Paket/files/1275359/PaketReferencesIssue2.zip)

- Create new solution in Visual Studio 2015 with a single console Windows app (not .NET core)
- Initialize paket in a root directory
- Add `Microsoft.Extensions.Configuration` to the paket.dependencies
- Add paket.references file to console project with `Microsoft.Extensions.Configuration`
- Run `paket install`

### Expected behavior

Paket adds a reference to csproj file and it can be observed from Visual Studio.

### Actual behavior

Reference is not added

![devenv_2017-09-04_21-58-55](https://user-images.githubusercontent.com/1292603/30036466-489fdf6a-91bc-11e7-8239-433a6973c5a5.png)

**Comment by matthid** [comment] 2017-09-04 19:12
Duplicate of https://github.com/fsprojects/Paket/issues/2705

**Closed by matthid** 2017-09-04 19:12 UTC
