### ISSUE TITLE
Incorrect warning that dependencies + lock files are out of date

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#2682] opened 2017-08-28 14:16 UTC
## Issue Description

Using a dependencies + lock file created using a paket version < 5.91.0, but restoring using 5.91.0, leads to warnings that settings have changed for your dependencies and the recommendation that you call install or update.

However, even after calling update, the warning still persists.

## Expected Behaviour
* I would not expect a warning that the lock / deps files are out of sync when they are not. This will lead to users unnecessarily having to update packages.
* The warning should not appear after calling install or update.

**Comment by matthid** [comment] 2017-08-28 18:02
@isaacabraham I cannot reproduce. Can you provide the depsfile? All I can do is improve the message to show which setting has changed.

**Comment by matthid** [comment] 2017-08-29 22:19
Fix is in #2687 thanks for reporting this.

**Closed by matthid** 2017-08-29 22:19 UTC
