### ISSUE TITLE
paket.lock beautification for HTTP specs

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/Paket#553] opened 2015-01-15 14:14 UTC
When my `paket.references` looks like this:
```
http http://www.frijters.net/ikvmbin-8.0.5449.0.zip
http http://nlp.stanford.edu/software/stanford-corenlp-full-2014-10-31.zip
http http://nlp.stanford.edu/software/stanford-ner-2014-10-26.zip
http http://nlp.stanford.edu/software/stanford-parser-full-2014-10-31.zip
http http://nlp.stanford.edu/software/stanford-postagger-full-2014-10-26.zip
http http://nlp.stanford.edu/software/stanford-segmenter-2014-10-26.zip
```
I get following `paket.lock` file:
```
HTTP
  remote: http://www.frijters.net/ikvmbin-8.0.5449.0.zip
  specs:
    ikvmbin-8.0.5449.0.zip
  remote: http://nlp.stanford.edu/software/stanford-corenlp-full-2014-10-31.zip
  specs:
    stanford-corenlp-full-2014-10-31.zip
  remote: http://nlp.stanford.edu/software/stanford-ner-2014-10-26.zip
  specs:
    stanford-ner-2014-10-26.zip
  remote: http://nlp.stanford.edu/software/stanford-parser-full-2014-10-31.zip
  specs:
    stanford-parser-full-2014-10-31.zip
  remote: http://nlp.stanford.edu/software/stanford-postagger-full-2014-10-26.zip
  specs:
    stanford-postagger-full-2014-10-26.zip
  remote: http://nlp.stanford.edu/software/stanford-segmenter-2014-10-26.zip
  specs:
    stanford-segmenter-2014-10-26.zip
```
but IMHO would be nice to have something like this:
```
HTTP
  remote: http://www.frijters.net/
  specs:
    ikvmbin-8.0.5449.0.zip
  remote: http://nlp.stanford.edu/software/
  specs:
    stanford-corenlp-full-2014-10-31.zip
    stanford-ner-2014-10-26.zip
    stanford-parser-full-2014-10-31.zip
    stanford-postagger-full-2014-10-26.zip
    stanford-segmenter-2014-10-26.zip
```

@forki @agross Your thoughts?

**Comment by forki** [comment] 2015-01-15 14:20
yes that looks much nicer. Are you interested in implemented this?

**Comment by sergey-tihon** [comment] 2015-01-15 20:50
Yes, I could try to look at this when finish migration [Stanford.NLP.NET](https://github.com/sergey-tihon/Stanford.NLP.NET) to paket.

Latest thought: leave only host name in the remote.
```
HTTP
  remote: http://www.frijters.net
  specs:
    /ikvmbin-8.0.5449.0.zip
  remote: http://nlp.stanford.edu
  specs:
    /software/stanford-corenlp-full-2014-10-31.zip
    /software/stanford-ner-2014-10-26.zip
    /software/stanford-parser-full-2014-10-31.zip
    /software/stanford-postagger-full-2014-10-26.zip
    /software/stanford-segmenter-2014-10-26.zip
```

**Comment by sergey-tihon** [comment] 2015-01-23 20:11
I see the small problem here: 
We allow to rename files from `http` sources in `paket.dependencies` file:
```
http http://www.fssnip.net/raw/1M test1.fs
http http://www.fssnip.net/raw/1M/1 src/test2.fs
```
now corresponding `paket.lock` file looks like this
```
HTTP
  remote: http://www.fssnip.net/raw/1M
  specs:
    test1.fs
  remote: http://www.fssnip.net/raw/1M/1
  specs:
    src/test2.fs
```

but it should be like this...
```
HTTP
  remote: http://www.fssnip.net
  specs:
    /raw/1M test1.fs
    /raw/1M/1 src/test2.fs
```
but in this case we are losing backward compatibility :disappointed: 
We will not be able to parse existing `paket.lock` files that use renaming feature

**Comment by forki** [comment] 2015-01-23 20:18
Don't care too much about backwards camp here. Just make clear where you break it.

**Comment by sergey-tihon** [comment] 2015-01-27 06:03
Why we have this test? 
https://github.com/fsprojects/Paket/blob/master/tests/Paket.Tests/Resolver/ConflictSourcesSpecs.fs#L41-L68
`config2` looks like a valid dependency file, all target file names are distinct, so we are able to download. What is the goal for fail in this case?

**Comment by mexx** [comment] 2015-01-28 07:53
@sergey-tihon The root cause why the test was added was that when downloading source files there will be a file `paket.version` written which contains the hash of the commit downloaded. This file is written per referenced repository and not per file. I had problems with the restore process and restricted the functionality.

**Comment by ledbutter** [comment] 2015-01-31 02:28
@sergey-tihon since your PR for this was merged into master, shouldn't this issue be closed?

**Closed** 2015-01-31 07:39 UTC
Labels: cosmetics, up-for-grabs
