### ISSUE TITLE
Override Source Server on Restore

### ISSUE THREAD

**Issue by ArmonA** [fsprojects/Paket#1548] opened 2016-03-24 14:49 UTC
Hi,

I came across a need to override the source server defined in the paket files during restore operation. It seems like there is no way of doing it right now, NuGet does allow it by using the source argument on the [restore](https://docs.nuget.org/consume/command-line-reference#restore-command) command.

I would like to suggest it as a possible enhancement.

**Comment by forki** [comment] 2016-03-24 14:58
duplicate of #1386

**Closed by forki** 2016-03-24 14:58 UTC
