### ISSUE TITLE
StackOverflowException resolving NuGet package without version constraint from large paket.dependencies

### ISSUE THREAD

**Issue by viktor-svub** [fsprojects/Paket#1392] opened 2016-01-15 12:04 UTC
StackOverflowException resolving "our.proprietary.component"
* Paket.exe 2.44.1, version 2.21 works but does not handle prereleases
* paket.dependencies NuGet, declared without any version constraint
* there are about 180 declared dependencies, all NuGet, all custom feeds
* probably also transitive dependency of some of the other component/s
* SO is thrown in \src\Paket.Core\Domain.fs, line 30, ckeckout cf9c622
  (this.GetCompareString().CompareTo(that.GetCompareString()))
* stack trace @ https://gist.github.com/viktor-svub/c1563f0c2b98562f67ee

**Comment by forki** [comment] 2016-01-15 12:33
can you please try to find the last working version?

**Comment by viktor-svub** [comment] 2016-01-15 13:53
OK, the issue appears between 2.40.14 (latest working) and 2.40.15 (throws SO). 
* the full command crashing with exception is `paket.exe update --no-install`
* we have 4 custom NuGet feeds, often containing different versions of same packages
* majority of the 180 immediate dependencies are `prerelease`
* majority of all the dependencies are using `@~>` resolution
* the generated `paket.lock` is about 360 lines long

**Comment by forki** [comment] 2016-01-15 13:56
diff --git a/src/Paket.Core/SemVer.fs b/src/Paket.Core/SemVer.fs
index 444e688..d466672 100644
--- a/src/Paket.Core/SemVer.fs
+++ b/src/Paket.Core/SemVer.fs
@@ -144,6 +144,8 @@ interface System.IComparable with
                     | None, None -> 0
                     | Some p, None -> -1
                     | None, Some p -> 1
+                    | Some p, _ when p.ToString() = "prerelease" -> -1
+                    | _, Some p when p.ToString() = "prerelease" -> 1
                     | Some left, Some right -> compare left right
 
             | _ -> invalidArg "yobj" "cannot compare values of different types"


that's the only change. weird

**Comment by forki** [comment] 2016-01-15 13:57
but I assume the real issue is that our resolver algorithm is still recursive. Need to implement BFS qith a queue...

**Comment by forki** [comment] 2016-01-15 15:28
@viktor-svub in the latest version I inline the tryToImprove function. This will "free" halve of the stack in your sample and should help to process significantly larger graphs. Does this work for you?

@mrinaldi do you see a chance that we can remove the recursive step function and turn it into something that manages a queue or a stack internally?

**Comment by mrinaldi** [comment] 2016-01-16 00:14
IIRC yes.
I'm on vacation right now, though. I'm not sure when I'll have time to look at it.
Maybe sometime next week.

**Comment by gpomykala** [comment] 2016-01-18 08:41
I noticed the same problem (SO during paket update --no-install). The last working version is 2.40.14, 2.44.5 still fails

**Comment by forki** [comment] 2016-01-18 08:44
can any of you reproduce with a dependencies file that can be made public?

**Comment by gpomykala** [comment] 2016-01-22 10:33
We were not able to reproduce it using public packages only yet. it's a mix of public libs and internal libs

**Comment by forki** [comment] 2016-01-22 10:36
maybe exclude the internal stuff and add public packages until it breaks again?

**Comment by forki** [comment] 2016-02-11 16:09
This fixed in 2.50.3

**Closed by forki** 2016-02-11 16:09 UTC
