### ISSUE TITLE
Uninformative warning message

### ISSUE THREAD

**Issue by lexarchik** [fsprojects/Paket#2458] opened 2017-06-22 10:35 UTC
1. call `paket init` in empty folder
2. add `nuget nunit 3.4.1` in paket.dependencies file
3. call `paket install` 

Paket write warning like:
`The profile 'portable-net45+monoandroid+monotouch+xamarinios+xamarinmac+win8+wp8+wpa81' is not a known profile. Please tell the package author.`.

Warning message does not contains information about package that cause problem.

Workaround: use `verbose` flag: in that case warning appears right after `libraries found...` for package with problem.

**Comment by matthid** [comment] 2017-06-22 11:14
Duplicate of https://github.com/fsprojects/Paket/issues/2443

**Closed by matthid** 2017-06-22 11:14 UTC
