### ISSUE TITLE
Question: How to specify target folder for Git dependency?

### ISSUE THREAD

**Issue by konste** [fsprojects/Paket#1884] opened 2016-08-24 21:09 UTC
I'm trying to make use of the new and shiny "Git dependency" feature. Files from my Git repo are copied to under paket-files folder, but the problem is that Paket creates really deep folder structure there. So deep really that it is close to hit Windows 260 characters path limit. 
I wonder if there is a way to specify explicitly where the repo should be copied to. Something like what FileSpec does for HTTP dependencies. 
Do we have such option for Git dependencies? If not it looks like we better do.
Note: I'm looking for a way to specify the path relative to paket.dependencies location.

Thank you!
Konstantin

**Comment by forki** [comment] 2016-08-25 13:23
nope I don't think we have this.

**Comment by enricosada** [comment] 2018-01-24 09:43
Closing. dupe of https://github.com/fsprojects/Paket/issues/1780

**Closed by enricosada** 2018-01-24 09:43 UTC
