### ISSUE TITLE
Problems with more than one feed

### ISSUE THREAD

**Issue by dzendras** [fsprojects/Paket#814] opened 2015-05-05 17:05 UTC
I'm having problems with one of the latest paket binaries (1.3.8). It seems that 0.4.2 doesn't show those problems.
1. BUG1 and BUG2 may be inappropriate usages of paket or bugs (I'm not sure).
2. WEBAPI fixes the problem (encountered by BUG1 and BUG2) by clearing paket.dependencies file.
3. BUG3 scenario seems to be a bug.
3a. SANITYCHECK confirms that Newtonsoft.Json is available on the internal feed.

Unfortuantely I am not able to send you a repro because of the internal feed involved.

**BUG1**

Given:
paket.references EMPTY
paket.dependencies with one line (source https://nuget.org/api/v2)
paket.lock EMPTY
When:
paket add nuget Microsoft.AspNet.WebApi project PaketSandbox
Then:

Paket version 1.3.8.0
Adding Microsoft.AspNet.WebApi to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\paket.dependencies
Resolving packages:
Paket failed with:
        Could not find versions for package Microsoft.AspNet.WebApi in any of the sources in [].

**BUG2**
Given:
paket.references EMPTY
paket.dependencies with one line (source https://nuget.org/api/v2)
paket.lock ABSENT
When:
paket add nuget Microsoft.AspNet.WebApi project PaketSandbox
Then:
Paket version 1.3.8.0
Adding Microsoft.AspNet.WebApi to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\paket.dependencies
Resolving packages:
Paket failed with:
        Could not find versions for package Microsoft.AspNet.WebApi in any of the sources in [].

**WEBAPI**
Given:
paket.references EMPTY
paket.dependencies EMPTY
paket.lock EMPTY
When:
paket add nuget Microsoft.AspNet.WebApi project PaketSandbox
Then:
Paket version 1.3.8.0
Adding Microsoft.AspNet.WebApi to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\paket.dependencies
Resolving packages:
 - Microsoft.AspNet.WebApi 5.2.3
 - Microsoft.AspNet.WebApi.WebHost 5.2.3
 - Microsoft.AspNet.WebApi.Core 5.2.3
 - Microsoft.AspNet.WebApi.Client 5.2.3
 - Newtonsoft.Json 6.0.8
 - Microsoft.Net.Http 2.2.29
 - Microsoft.Bcl 1.1.10
 - Microsoft.Bcl.Build 1.0.21
Locked version resolutions written to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\paket.lock
Dependencies files saved to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\paket.dependencies
Adding Microsoft.AspNet.WebApi to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\PaketSandbox\paket.references
References file saved to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\PaketSandbox\paket.references
4 seconds - ready.

**BUG3**
Given:
1. WEBAPI performed successfully
2. Modify paket.dependencies so it looks like this:
source http://internalfeed/NugetWebFeed/nuget //Add this line (internalfeed contains Newtonsoft.Json)

nuget log4net 1.2.0 //Add this line (internalfeed contains log4net)

source https://nuget.org/api/v2 //Created by WEBAPI

nuget Microsoft.AspNet.WebApi //Created by WEBAPI

When:
paket add nuget log4net project PaketSandbox
Then:
Paket version 1.3.8.0
C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\paket.dependencies contains package log4net already. ==> Ignored
Resolving packages:
 - Newtonsoft.Json 6.0.8
Paket failed with:
        Couldn't get package details for package Newtonsoft.Json on any of ["http://internalfeed/NugetWebFeed/nuget"].

**SANITYCHECK**
Given:
paket.references EMPTY
paket.lock EMPTY
paket.dependencies:
source http://internalfeed/NugetWebFeed/nuget //(feed contains Newtonsoft.Json)

nuget Newtonsoft.Json

When:
paket add nuget Newtonsoft.Json project PaketSandbox
Then:
Paket version 1.3.8.0
C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\paket.dependencies contains package Newtonsoft.Json already. ==> Ignored
Resolving packages:
 - Newtonsoft.Json 6.0.6
Locked version resolutions written to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\paket.lock
Dependencies files saved to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\paket.dependencies
Adding Newtonsoft.Json to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\PaketSandbox\paket.references
References file saved to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\PaketSandbox\paket.references
Newtonsoft.Json 6.0.6 unzipped to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\packages\Newtonsoft.Json
1 second - ready.

paket.lock:

NUGET
  remote: http://internalfeed/NugetWebFeed/nuget
  specs:
    Newtonsoft.Json (6.0.6)

**Comment by forki** [comment] 2015-05-06 06:42
BUG1, BUG2 are confirmed as bugs and resolved in current version.

Is there any chance for me to get private access to your internal feed?

**Comment by dzendras** [comment] 2015-05-06 08:04
I am afraid it's not possible. It's an internal company feed.

However I can provide a sample that was the reason why I decided to make a repro:

**BUG4**
Given:
paket.references: A lot of them filled with various entries
paket.lock:

NUGET
  remote: http://internalfeed/NugetWebFeed/nuget
  specs:
	Internal_1
      Newtonsoft.Json (>= 6.0.0 < 6.1.0)
    log4net (1.2.10)
    Newtonsoft.Json (6.0.6)
  remote: https://www.nuget.org/api/v2
  specs:
    Microsoft.AspNet.WebApi (5.2.3)
      Microsoft.AspNet.WebApi.WebHost (>= 5.2.3 < 5.3.0)
    Microsoft.AspNet.WebApi.Client (5.2.3)
      Microsoft.Net.Http (>= 2.2.22) - framework: portable-wp80+win+net45+wp81+wpa81
      Newtonsoft.Json (>= 6.0.4) - framework: portable-wp80+win+net45+wp81+wpa81, >= net45
    Microsoft.AspNet.WebApi.Core (5.2.3)
      Microsoft.AspNet.WebApi.Client (>= 5.2.3)
    Microsoft.AspNet.WebApi.WebHost (5.2.3)
      Microsoft.AspNet.WebApi.Core (>= 5.2.3 < 5.3.0)

paket.dependencies:

source http://internalfeed/NugetWebFeed/nuget

nuget Internal_1
nuget log4net 1.2.10
nuget Newtonsoft.Json

source https://www.nuget.org/api/v2

nuget Microsoft.AspNet.WebApi
nuget Microsoft.AspNet.WebApi.Core

When:
paket install
Then:
Paket version 1.3.8.0
Resolving packages:
 ...
 - Newtonsoft.Json 6.0.6
 - Microsoft.AspNet.WebApi 5.2.3
Paket failed with:
        Couldn't get package details for package Microsoft.AspNet.WebApi on any
of ["http://internalfeed/NugetWebFeed/nuget"].

**INFO1**
Given:
paket.references: Same as BUG4
paket.dependencies: Same as BUG4
paket.lock ABSENT

When:
paket install
Then:
Succeeds

**INFO2**
Given:
paket.references: Same as BUG4
paket.dependencies: Same as BUG4
paket.lock Sane as BUG4
paket version 0.4.2

When:
paket install
Then:
Succeeds

**Comment by dzendras** [comment] 2015-05-06 08:10
So the question is: Why paket tries to get package details of WebApi (official nuget) on internal_feed (which hosts WebApi's dependency: Newtonsoft.Json)?

**Comment by forki** [comment] 2015-05-06 08:10
could you please try to align the paket.lock correctly?

**Comment by forki** [comment] 2015-05-06 08:14
hint: use editor and insert 4 spaces before every line of your code. then copy into comment.

**Comment by dzendras** [comment] 2015-05-06 08:15
NUGET
      remote: http://internalfeed/NugetWebFeed/nuget
      specs:
	    Internal_1
          Newtonsoft.Json (>= 6.0.0 < 6.1.0)
        log4net (1.2.10)
        Newtonsoft.Json (6.0.6)
      remote: https://www.nuget.org/api/v2
      specs:
        Microsoft.AspNet.WebApi (5.2.3)
          Microsoft.AspNet.WebApi.WebHost (>= 5.2.3 < 5.3.0)
        Microsoft.AspNet.WebApi.Client (5.2.3)
          Microsoft.Net.Http (>= 2.2.22) - framework: portable-wp80+win+net45+wp81+wpa81
          Newtonsoft.Json (>= 6.0.4) - framework: portable-wp80+win+net45+wp81+wpa81, >= net45
        Microsoft.AspNet.WebApi.Core (5.2.3)
          Microsoft.AspNet.WebApi.Client (>= 5.2.3)
        Microsoft.AspNet.WebApi.WebHost (5.2.3)
          Microsoft.AspNet.WebApi.Core (>= 5.2.3 < 5.3.0)

**Comment by dzendras** [comment] 2015-05-06 08:16
Done

**Comment by forki** [comment] 2015-05-06 08:19
is there a version given after Internal_1 ?

**Comment by dzendras** [comment] 2015-05-06 08:27
Yes, there is. I updated the lock file. I also noticed that there's Internal_2 that also requires Newtonsoft.Json.

**Comment by dzendras** [comment] 2015-05-06 08:30
Please note that I haven't published the entire lock and dependencies file. Just the relevant parts (dealing with Json and WebApi)

**Comment by forki** [comment] 2015-05-06 08:31
I think I found the issue.

**Comment by dzendras** [comment] 2015-05-06 08:32
Glad to hear that :) Is it fixable? :)

**Comment by forki** [comment] 2015-05-06 08:37
sure

2015-05-06 10:32 GMT+02:00 Jedrzej Grabowski <notifications@github.com>:

**Comment by forki** [comment] 2015-05-06 08:55
please verify if the thing works now.

**Comment by dzendras** [comment] 2015-05-06 09:24
Unfortunately it doesn't... I'm going to give you some details shortly...

**Comment by dzendras** [comment] 2015-05-06 09:35
BUG3: The same error: Nothing's changed.
BUG4: There's a slight change (previously it stopped at WebApi, not WebApi.Client):

Paket version 1.3.22.0
Resolving packages:
 - Newtonsoft.Json 6.0.6
 - Microsoft.AspNet.WebApi 5.2.3
 - Microsoft.AspNet.WebApi.Client 5.2.3
Paket failed with:
        Couldn't get package details for package Microsoft.AspNet.WebApi.Client
on any of ["http://internalfeed/NugetWebFeed/nuget"].

**Comment by forki** [comment] 2015-05-06 09:36
ok I see.

**Comment by forki** [comment] 2015-05-06 09:47
sorry playing ping pong here, but since I can't access the feed it's just guessing what's wrong. Anyways there is a new version available.

**Comment by dzendras** [comment] 2015-05-06 10:13
I don't mind the ping pong :)

Still problems:
BUG3:
Paket version 1.3.23.0
Adding Newtonsoft.Json to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\paket.dependencies
Resolving packages:
 - Microsoft.AspNet.WebApi 5.2.3
 - Microsoft.AspNet.WebApi.Client 5.2.3
 - Microsoft.AspNet.WebApi.Core 5.2.3
 - Microsoft.AspNet.WebApi.WebHost 5.2.3
 - Microsoft.Net.Http 2.2.29
 - log4net 1.2.0
Paket failed with:
        Couldn't get package details for package log4net on any of ["http://internalfeed/NugetWebFeed/nuget"].

BUG4:
We've got a new actor coming to the stage: Internal_3!
Let's do a brief introduction:

paket.dependencies:
nuget Internal_3 ~> 1.0
paket.lock:
Internal_3 (1.0.071.9432) //No dependencies

Then (outcome):
Paket version 1.3.23.0
Resolving packages:
 ...
- Internal_3 1.0.071.9556
 ...
- Newtonsoft.Json 6.0.6
- Microsoft.AspNet.WebApi 5.2.3
- Microsoft.AspNet.WebApi.Client 5.2.3
- Microsoft.AspNet.WebApi.Core 5.2.3
- Microsoft.AspNet.WebApi.WebHost 5.2.3
 ...
- log4net 1.2.10
 ...
Paket failed with:
        Could not find compatible versions for top level dependency:
     "Internal_3 1.0.071.9432 (from C:\...\paket.dependencies)"
   Available versions:
     - 1.0.071.9556
   Try to relax the dependency or allow prereleases.

**Comment by dzendras** [comment] 2015-05-06 10:18
BUG4:
Neither Internal_1 nor Internal_2 depend on Internal_3.
Internal_3 has no dependencies at all.

When you delete paket.lock and run paket install, then there are no errors.

**Comment by forki** [comment] 2015-05-06 10:23
Yes it's still a bug with the "smart" install. Will try to look deeper

2015-05-06 12:18 GMT+02:00 Jedrzej Grabowski <notifications@github.com>:

**Comment by forki** [comment] 2015-05-06 10:49
Regarding Bug 3: didn't you say log4net is on the internal feed? It seems to look into the correct feed.

**Comment by dzendras** [comment] 2015-05-06 10:54
I did. So as Newtonsoft.Json (the original error). Let me run sanity check with log4net to prove that log4net is accessible from internal feed...

**Comment by dzendras** [comment] 2015-05-06 11:06
Indeed paket is not able to get the information. However when I launched NuGet (via VS's Manage NuGet Packages) with the internal feed I could install log4net successfully:

------- Installing...log4net 1.2.10 -------
Installing 'log4net 1.2.10'.
Added file 'log4net.dll' to folder 'log4net.1.2.10\lib\1.0'.
Added file 'log4net.xml' to folder 'log4net.1.2.10\lib\1.0'.
Added file 'log4net.dll' to folder 'log4net.1.2.10\lib\1.1'.
Added file 'log4net.xml' to folder 'log4net.1.2.10\lib\1.1'.
Added file 'log4net.dll' to folder 'log4net.1.2.10\lib\2.0'.
Added file 'log4net.xml' to folder 'log4net.1.2.10\lib\2.0'.
Added file 'log4net.1.2.10.nupkg' to folder 'log4net.1.2.10'.
Successfully installed 'log4net 1.2.10'.
Adding 'log4net 1.2.10' to PaketSandbox.
For adding package 'log4net 1.2.10' to project 'PaketSandbox' that targets 'net451',
>> Assembly references are being added from 'lib\2.0'
Added reference 'log4net' to project 'PaketSandbox'
Added file 'packages.config'.
Added file 'packages.config' to project 'PaketSandbox'
Successfully added 'log4net 1.2.10' to PaketSandbox.

**Comment by forki** [comment] 2015-05-06 11:11
I have no idea how to debug this one.

**Comment by dzendras** [comment] 2015-05-06 11:19
I spotted a file NuGet local cache (C:\Users\user\AppData\Local\NuGet\Cache): log4net.1.2.0.s2000701002.json.failed. Its content:

System.Exception: Could not retrieve data from http://internal_feed/NugetWebFeed/nuget/Packages(Id='log4net',Version='1.2.0')
 Message: The remote server returned an error: (404) Not Found.
   at Paket.Utils.getFromUrl@187-4.Invoke(String message)
   at Paket.Utils.getFromUrl@182-3.Invoke(Exception _arg2)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)System.Exception: Error file for log4net exists at C:\Users\user\AppData\Local\NuGet\Cache\log4net.1.2.0.s2000701002.json.failed
   at Paket.NuGetV2.getDetailsFromNuget@293-2.Invoke(String message)
   at Paket.NuGetV2.getDetailsFromNuget@292-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)System.Exception: Error file for log4net exists at C:\Users\user\AppData\Local\NuGet\Cache\log4net.1.2.0.s2000701002.json.failed
   at Paket.NuGetV2.getDetailsFromNuget@293-2.Invoke(String message)
   at Paket.NuGetV2.getDetailsFromNuget@292-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)System.Exception: Error file for log4net exists at C:\Users\user\AppData\Local\NuGet\Cache\log4net.1.2.0.s2000701002.json.failed
   at Paket.NuGetV2.getDetailsFromNuget@293-2.Invoke(String message)
   at Paket.NuGetV2.getDetailsFromNuget@292-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)System.Exception: Error file for log4net exists at C:\Users\user\AppData\Local\NuGet\Cache\log4net.1.2.0.s2000701002.json.failed
   at Paket.NuGetV2.getDetailsFromNuget@293-2.Invoke(String message)
   at Paket.NuGetV2.getDetailsFromNuget@292-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)

Does it help?

**Comment by forki** [comment] 2015-05-06 11:23
yes please delete the whole cache or retry with `-f`

**Comment by dzendras** [comment] 2015-05-06 13:34
I found the problem. My mistake.
I had invalid version in dependencies file: 1.2.0 instead of 1.2.10. Sorry for that. 

BUG3 fixed.

**Comment by dzendras** [comment] 2015-05-06 14:01
Ok all bugs mentioned in this ticket have been fixed (verified with 1.3.25.0).

Thank you very much for such a quick fix!

**Comment by forki** [comment] 2015-05-06 14:03
was a bit like:

![strange](https://cloud.githubusercontent.com/assets/57396/7494687/7426d68c-f409-11e4-9687-2dd54994f5ed.gif)

but I'm glad it works now

**Comment by dzendras** [comment] 2015-05-06 14:09
Actually I'm having a problem. I think we need to reopen this one...

Given:
BUG3 performed successfully //we have dependencies file with 2 feeds (internal first)
When:
paket add nuget Moq project PaketSandbox //Moq is NOT present on the internal feed
Then:
Paket version 1.3.25.0
Adding Moq to C:\Users\user\Documents\Visual Studio 2013\Projects\PaketSandbox\paket.dependencies
Resolving packages:
 - Newtonsoft.Json 6.0.8
 - Microsoft.AspNet.WebApi 5.2.3
 - Microsoft.AspNet.WebApi.Client 5.2.3
 - Microsoft.AspNet.WebApi.Core 5.2.3
 - Microsoft.AspNet.WebApi.WebHost 5.2.3
 - Microsoft.Net.Http 2.2.29
 - log4net 1.2.10
 - Microsoft.Bcl 1.1.10
 - Microsoft.Bcl.Build 1.0.21
Paket failed with:
        Couldn't retrieve versions for Moq.

**Comment by forki** [comment] 2015-05-06 14:11
![working](https://cloud.githubusercontent.com/assets/57396/7494855/89e0610e-f40a-11e4-8cb2-f029548f0f3b.gif)

**Comment by dzendras** [comment] 2015-05-06 14:22
![](http://tclhost.com/QsU9t4F.gif)

**Comment by forki** [comment] 2015-05-06 15:05
please try 1.3.26

**Closed** 2015-05-06 15:39 UTC
Labels: bug

**Comment by dzendras** [comment] 2015-05-06 16:56
I'll try tomorrow when I come to work and have access to the internal feed.

**Comment by dzendras** [comment] 2015-05-07 09:44
I am delighted to confirm that the above bugs have been fixed!
