### ISSUE TITLE
Usability issue with nuget creation

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket#1354] opened 2016-01-07 09:35 UTC
I have a following simple dependency

paket.dependencies
nuget Newtonsoft.Json >= 7

paket.lock
Newtonsoft.Json (8.0.1) 

As you can see in paket.dependencies it defined >=7 and in paket.lock as 8.0.1, my code is compiled against 8.0.1 and uses it features. 

When I publish a nuget with my code, I have 2 options ether to use paket.dependencies or paket.lock
If I use paket.dependencies and some one uses my nuget he will get Newtonsoft.Json of version 7.0 but my code is actually relying on version 8.0 and fail in runtime.

If I use paket.lock I making dependency too strict for my users.

That I really would like is that nuget will be created with dependency on Newtonsoft.Json >= 8.0.1

Right now the only way to achive this as far as I know is by manually updating paket.dependencies after running paket update command in case some dependency was updated.
It time consuming and fragile. 

Ideally I think pack command should merge between information in paket.dependencies and paket.lock

**Comment by forki** [comment] 2016-01-07 09:37
http://fsprojects.github.io/Paket/template-files.html#Dependencies shows you can do:

    dependencies
      Newtonsoft.JSON >= LOCKEDVERSION

**Comment by tsibelman** [comment] 2016-01-07 09:42
Thank you missed it and it looks a bit puzzling, will it will be updated in lock file when update command is executed ?

**Comment by forki** [comment] 2016-01-07 09:44
no that's in the template file. It's just a placeholder.

**Comment by tsibelman** [comment] 2016-01-07 09:46
I understand , as it looks I need to use this as minimum version for all of my dependencies

**Comment by forki** [comment] 2016-01-07 09:52
Maybe the uselockfile option for paket pack should use >=

**Comment by tsibelman** [comment] 2016-01-07 10:00
Hmm i tried it and I getting this error could not parse version range ">= LOCKEDVERSION"

**Comment by forki** [comment] 2016-01-07 10:02
Really? What about ~>

**Comment by tsibelman** [comment] 2016-01-07 10:03
Same could not parse version range "~> LOCKEDVERSION "

**Comment by forki** [comment] 2016-01-07 10:04
Mhm I think we have tests for this.
Are you sure you have correct syntax?

**Comment by tsibelman** [comment] 2016-01-07 10:06
Here the file I used
[paket.txt](https://github.com/fsprojects/Paket/files/80959/paket.txt)

**Comment by tsibelman** [comment] 2016-01-07 10:09
BTW I think ideally LOCKEDVERSION should be minimum version internaly when using pack command with paket.dependencies I think it correct behavior in majority of cases

**Comment by forki** [comment] 2016-01-07 10:09
As I said above. The LOCKEDVERSION is a setting for paket.template files.
You can't use it in paket.dependencies.

Please take a look at the docs that I referenced at the top.

**Comment by tsibelman** [comment] 2016-01-07 10:09
Sorry I misunderstood your

**Comment by tsibelman** [comment] 2016-01-07 10:10
But this means I need to write all dependencies manually in pack.template  file ?

**Comment by forki** [comment] 2016-01-07 10:12
Yes. That's what it would mean right now. But I also think that changing
the paket pack option to => might be useful.

Are you up to send a PR?

**Comment by tsibelman** [comment] 2016-01-07 10:16
I will try to look into it but I don't familiar with F# at all right now. 
But thank you, and I will close the issue

**Comment by forki** [comment] 2016-01-07 10:18
I think it's not that complicated. I assume it's a one line change. But
then there is docs,...

**Comment by tsibelman** [comment] 2016-01-07 10:39
I think it will be a breaking change for some people who used to existing behavior of lock-dependencies argument , and it will be too open for some use cases, for example the right now when I using paket.dependencie  I can limit upper version and lower version. If lock-dependencies with >= will be used it will be too open.

**Comment by forki** [comment] 2016-01-07 10:49
yes but we can make it another command line parameter...

2016-01-07 11:39 GMT+01:00 tsibelman <notifications@github.com>:

**Comment by tsibelman** [comment] 2016-01-07 10:59
It will be much more than a single line change :)

**Comment by forki** [comment] 2016-01-07 11:01
Yep with new parameter.
But compiler would guide you ;-)

**Comment by tsibelman** [comment] 2016-01-07 12:40
Sorry I tried understanding the code but it just too far from that I know.

**Comment by forki** [comment] 2016-01-07 12:49
ok I will add it to my backlog.

For nw you need to be explicit in the template file

**Comment by inosik** [comment] 2016-01-07 15:13
If you depend on `>= 8`, why do you define `>= 7` in `paket.dependencies`? Wouldn't something like `~> 8` be more appropriate?

**Comment by tsibelman** [comment] 2016-01-07 15:44
@forki thank you I think it will be great addition for many people
@inosik I started with >= 7 because it was a max available version at the time, then I run update command and got version 8 and compiled against it, it perfectly ok from my perspective because I want to be updated to current but I don't see any real reason why I should manually change the dependencies file after update.

**Comment by inosik** [comment] 2016-01-07 15:57
If you *really* need features of version 8, then you should reflect that in your `paket.dependencies`. Dependencies like `>= x` are not a good idea in most cases, anyways. More on this topic [here](http://jubianchi.github.io/semver-check#why-using-loose-constraint-is-bad). That's one of the (many) reasons why I prefer Paket over NuGet, because `>= x` is default in NuGet.

`~> 7` would have been a better choice in first place and I don't think that Paket needs something to change here. If you really want to have `>= 7`, then you should make sure not to use features of version 8.

**Comment by inosik** [comment] 2016-01-07 16:02
Remember that v9 of Newtonsoft.Json might introduce some breaking changes, which is perfectly OK according to semver, but might break your project. That's why you *have* to be more explicit with your dependencies.

**Comment by tsibelman** [comment] 2016-01-07 16:24
Paket.dependecies is declaration about what dependencies I am willing to update to. If I want to stay up to date with Newtonsoft.Json versions ~> 7 would not get me version 8, so if I use your way I would need to track it and every other dependency I have by some other tool and not by running packet commands. 

I think it not optimal way to work.

**Comment by inosik** [comment] 2016-01-07 17:04
This is where the `LOCKEDVERSION` macro comes into play and allows you to let your package depend on whatever you have resolved.

But, imagine your solution, the one where you define `nuget Newtonsoft.Json >= 7` in `paket.dependencies`. You install some other package, which depends on Newtonsoft.Json, but with version constraint of `>= 7 < 8`. Paket would resolve Newtonsoft.Json to the latest of 7.x, but this would now break your project, which **actually** is dependent on `>= 8`.

I don't know how much Newtonsoft.Json is following SemVer, but for any package which does, `>= x` would be too dangerous. And this is why Paket has the awesome `~>` operator. 

Paket is capable of recognizing such conflicts when *resolving* packages, instead of *build time*, or even worse, at *run time*.

**Comment by tsibelman** [comment] 2016-01-07 18:02
LOCKEDVERSION is good but it need to be manually inserted into every single project, even with medium number of projects it becomes hard to keep track of, in contrast to this references in project file are updated automatically and this one of the reasons paket is great. 

Both >= x and ~>x have pluses and minuses and I use both of them, but even if I use ~>x exclusively it will not solve the issue at hand.

**Comment by inosik** [comment] 2016-01-07 19:34
The question is, what works for most of the use cases, and I think that taking the version constraints from `paket.dependencies` is the best here.

What I do within our project, which produces an app and some packages, is this: When I realize that I need an external library, I look for the latest version, which is 8.0.1 for Newtonsoft.Json right now. Then I add `nuget Newtonsoft.Json ~> 8.0` to `paket.dependencies` and can use the current feature set and upcoming bugfixes. What you define here depends on how much you rely on the external library.

After some time, I create a `upgrade-packages` branch and start looking up the latest versions of the external packages. Now I can update `paket.dependencies`, for example to `nuget Newtonsoft.Json ~> 9.4`, run `paket install`, try to compile, run tests etc. If there are no errors, I got lucky and can continue with the next package. If I don't get lucky, I need to change some of my code, because the major version changed, and therefore, there might be breaking changes. When I'm done, I can merge `upgrade-dependencies` to `master`, bump my own version numbers, build and release new packages.

I agree that this involves some manual work, but I think that there is nothing what we can do about this, other than not using external packages at all.

**Comment by tsibelman** [comment] 2016-01-07 19:57
Hmm, I just suggesting to use existing LOCKEDVERSION  mechanics in more automatic way to make version from lock file to be your minimum version. Conceptually it should work like this 
definition nuget Newtonsoft.Json ~> 8.0 >= LOCKEDVERSION

**Comment by Allon-Guralnek** [comment] 2016-01-28 08:57
@inosik: Your argument is mostly based on major version changes. I agree that you should mostly depend on a specific major version, because allowing automatic updates to future major versions has a high likelihood of being incompatible due to breaking changes. But that's not really the heart of the issue at hand.

The problem is, even for SemVer-compliant packages, you might take a dependency on minor changes (e.g. bug fixes). If you added version `~> 8.0`, then later you were updated to version `8.0.3` that fixed a bug, you have a dependency on `8.0.3`, not on `~> 8.0`. Your unit tests might fail if for any reason someone uses `8.0.2`. While your intentions are to be on `8.x`, in practice you've been developing against `8.0.3` which therefore should be the *effective* dependency. This effective dependency should be the one specified in the NuGet package.

If you take this further, take a scenario where I develop against `8.0.3` on my machine, but my build server does a clean build and gets `8.0.5` then runs lengthy integration and performance tests (which I never run locally) using `8.0.5` and it passes, then publishes a NuGet (using Paket, of course). The NuGet it publishes should specify `8.0.5` because that is the minimum version that is known to pass those tests. It should not specify `>= 8.0.0` because that's completely detached from reality.

All this should happen implicitly and automatically, without requiring thought by the developer or by requiring explicit and cumbersome actions on his part (like manually maintaining metadata in the `.template` file where the tool could do this automatically). The main benefit of Paket, after all, is to simplify the developer's life by automating such things (where in contrast, the native NuGet client complicates them).

**Closed** 2016-02-04 09:41 UTC
Labels: enhancement
