### ISSUE TITLE
Paket restore hangs when used with docker build

### ISSUE THREAD

**Issue by jackmott** [fsprojects/Paket#3123] opened 2018-03-17 21:01 UTC
### Description

paket restore hangs on my project when used in a docker build. It runs very quickly when I run it outside of a docker build.  While hung the mono process is pegging 1 core. The last output of paket restore --verbose is "parsing paket.dependencies"

### Repro steps

paket.dependencies:
```source https://api.nuget.org/v3/index.json
framework >= net45

nuget DotLiquid
nuget FSharp.Data
nuget FsSql
nuget MathNet.Numerics.FSharp
nuget Newtonsoft.Json
nuget Npgsql = 3.1
nuget Octokit
nuget SQLProvider
nuget Suave >= 2.3.0-beta3
nuget Suave.DotLiquid >= 2.3.0-beta3
nuget Suave.Experimental >= 2.3.0-beta3
```

Dockerfile:
```
FROM fsharp:latest
ADD . /
WORKDIR /
RUN mono .paket/paket.bootstrapper.exe
RUN mono .paket/paket.exe restore --verbose
RUN ./build.sh
ENTRYPOINT ["mono","/root/AlphaFront/bin/Release/AlphaFront.exe"]
```
I am running docker build with a private github repo as the context

The repo is private so I am sorry I cannot provide it.

### Expected behavior

paket should work

### Actual behavior

paket hangs and pegs a cpu core

### Known workarounds

none

**Comment by forki** [comment] 2018-03-17 21:08
Yeah it's a long known issue. We have no idea what it's causing.

Jack Mott <notifications@github.com> schrieb am Sa., 17. März 2018, 22:01:

**Comment by jackmott** [comment] 2018-03-17 22:11
@forki any workarounds?

**Comment by forki** [comment] 2018-03-18 07:12
Nope. I think it's a mono bug.

Jack Mott <notifications@github.com> schrieb am Sa., 17. März 2018, 23:11:

**Comment by matthid** [comment] 2018-03-18 08:21
As long as we don’t know how to reproduce or ge it into a debugger be accident. There is not much we can do. 
Maybe some http request doesn’t timeout correctly. Or some user message pops up on the ci for some reason...

**Comment by atadi96** [comment] 2019-02-21 21:59
This is rendering me unable to create a repro for an issue with FAKE 5. What can I do in this case? Sorry if this in not the right place to ask but I'm lost.

I've also found that paket restore does **not** hang when called in a gitlab-runner instance with docker runner.

**Comment by forki** [comment] 2019-02-22 07:31
Sorry we still don't know what's going wrong here

**Comment by ajuch** [comment] 2019-11-26 09:05
I'm having the same behavior with a .net core 3.0 sdk docker image.

paket.dependencies:
```
source https://api.nuget.org/v3/index.json

storage: none
framework: netcore3.0, netstandard2.0, netstandard2.1
nuget canopy
nuget Selenium.WebDriver.ChromeDriver
```

Dockerfile:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build-env
COPY . ./
RUN dotnet tool restore
RUN dotnet paket restore -v
```

It hangs at:
```
Step 5/11 : RUN dotnet paket restore -v
 ---> Running in ace15e1382a0
Paket version 5.236.6
found: /paket.dependencies
 - /.paket/Paket.Restore.targets already up-to-date
Parsing /paket.dependencies
```

So I don't think it's a mono issue...

**Comment by forki** [comment] 2019-11-26 10:54
@ajuch cool thanks for the repro. I can actually reproduce it now

**Comment by forki** [comment] 2019-11-26 12:12
I added crazy amout of logging and here we are:

![image](https://user-images.githubusercontent.com/57396/69631567-56531380-104e-11ea-9870-1bded800d216.png)

**Comment by forki** [comment] 2019-11-26 12:16
so the problem is in https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/PaketConfigFiles/ProjectFile.fs#L1906

we are scanning all subfolders but inside the docker main folder we seem to run into an issue that we scan the whole file system. So what can we do?

**Comment by forki** [comment] 2019-11-26 13:47
this is fixed in 5.238. thanks for the repro

**Closed** 2019-11-26 13:53 UTC

**Comment by ajuch** [comment] 2019-11-26 14:30
Thank you @forki! It works!

Ah, I see what I did wrong... I should have put my app into a directory... But the funny thing is that I didn't see the recursive crawling when running `strace dotnet paket restore`.

But it doesn't matter, now it works like a charm!

**Comment by forki** [comment] 2019-11-26 14:40
I added that additional tracing in intermediate releases to understand the
bug.

Andreas Juch <notifications@github.com> schrieb am Di., 26. Nov. 2019,
15:30:
