### ISSUE TITLE
paket + msbuild /t:Pack doesn't respect development dependencies

### ISSUE THREAD

**Issue by tpluscode** [fsprojects/Paket#2925] opened 2017-12-03 13:26 UTC
### Description

I'm trying to package a multi-targeting project. I previously used `paket pack` but I understand that it doesn't work with multiple targets (#2591). A dependency prevents me from using `dotnet pack` so I'm left with `msbuild /t:Pack` which almost works.

The problem is that even though my dependencies are marked as `developmentDependency`, still the pack target includes them as dependencies in the nupkg.

### Repro steps

Please provide the steps required to reproduce the problem

1. Check out branch [net-standard of tpluscode/UriTemplateString](https://github.com/tpluscode/UriTemplateString/tree/net-standard)
1. `.paket/paket.exe restore`
1. `dotnet restore`
1. `msbuild /t:Pack UriTemplateString.sln`

### Expected behavior

The produced nupkg should have no dependencies

### Actual behavior

The nupkg has dependencies to four dependencies which are all developmentDependencies.

**Comment by forki** [comment] 2017-12-03 14:58
How would development dependencies be used in PackageReference tags? Is
there a attribute on that tag?

Am 03.12.2017 14:26 schrieb "Tomasz Pluskiewicz" <notifications@github.com>:

Description

I'm trying to package a multi-targeting project. I previously used paket
pack but I understand that it doesn't work with multiple targets (#2591
<https://github.com/fsprojects/Paket/issues/2591>). A dependency prevents
me from using dotnet pack so I'm left with msbuild /t:Pack which almost
works.

The problem is that even though my dependencies are marked as
developmentDependency, still the pack target includes them as dependencies
in the nupkg.
Repro steps

Please provide the steps required to reproduce the problem

   1. Check out branch net-standard of tpluscode/UriTemplateString
   <https://github.com/tpluscode/UriTemplateString/tree/net-standard>
   2. .paket/paket.exe restore
   3. dotnet restore
   4. msbuild /t:Pack UriTemplateString.sln

Expected behavior

The produced nupkg should have no dependencies
Actual behavior

The nupkg has dependencies to four dependencies which are all
developmentDependencies.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2925>, or mute the thread

**Comment by tpluscode** [comment] 2017-12-03 17:48
Interestingly, there seems to be a regression in `dotnet` tools in that development dependencies are not handled properly. 

I've just found NuGet/Home#4125 which is still open. According to the discussion, instilling a dev dependency package should add `<PrivateAssets>all</PrivateAssets>` under the `<PackageReference>`

Such as

``` xml
<PackageReference Include="StyleCop.Analyzers" Version="1.0.2">
  <PrivateAssets>all</PrivateAssets>
</PackageReference>
```

**Comment by forki** [comment] 2017-12-03 17:49
So what should we do exactly?

Am 03.12.2017 18:48 schrieb "Tomasz Pluskiewicz" <notifications@github.com>:

**Comment by tpluscode** [comment] 2017-12-03 17:52
`PrivateAssets` affects the `project.assets.json` file which is then used for packing, right? 

I think that installing a development dependency should have the same effect on that lock file as `PrivateAssets=all` has

**Comment by tpluscode** [comment] 2017-12-03 18:05
Here's the original lock file: [projects.assets.json](https://github.com/fsprojects/Paket/files/1525015/projects.assets.txt)

And here's what I get once I added `PrivateAssets`: [project.assets.json](https://github.com/fsprojects/Paket/files/1525016/project.assets.txt)

**Comment by enricosada** [comment] 2017-12-05 17:26
@tpluscode try with `PrivateAssets` as attribute.

like

```xml
    <PackageReference Include="SourceLink.Create.CommandLine" Version="2.1.1" PrivateAssets="all" />
```

with this, `dotnet pack` shoulnd add these to final nupkg

**Comment by tpluscode** [comment] 2017-12-05 19:19
@enricosada I've seen attribute and it probably works too. But I'm not sure how this is relevant. With Paket there is no `PackageReference` at all in the project file, which is the point here

**Comment by enricosada** [comment] 2018-01-24 14:35
@tpluscode right, paket miss that.

Closing this as dupe of https://github.com/fsprojects/Paket/issues/2370 who track adding `PrivateAssets` to paket

**Closed by enricosada** 2018-01-24 14:35 UTC
Labels: bug, nupkg spec, sdk: dotnet/sdk

**Comment by enricosada** [comment] 2018-01-24 14:37
Added also a comment about `developmentDependency`
