### ISSUE TITLE
Referencing Paket.Core / Exe problems.

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#1958] opened 2016-10-11 12:37 UTC
Referencing both Paket.Core or Paket from the NuGet feed has issues related to (I believe) the fact that we ILMerge stuff in to both versions.

With Paket.Core, you'll get errors regarding Chessie. With Paket.exe, you have issues with FSharp.Core duplicates and invalid casts.

Perhaps someone can better explain this than me :-) What's the best way to solve this though?

**Comment by forki** [comment] 2016-10-11 12:38
Would you want to have a special package? Without ILMerged stuff?

**Comment by forki** [comment] 2016-10-11 12:38
but paket.core is not ILMerged. What issue do you see with chessie?

**Comment by isaacabraham** [comment] 2016-10-11 12:50
```fsharp
#r @"packages\Paket.Core.3.23.1\lib\net45\Paket.Core.dll"
#r @"packages\Chessie.0.0.1\lib\net40\Chessie.dll"
open Paket
open Chessie
let dependenciesFile = Dependencies(@"paket.dependencies")
```
gives an error
```
error FS0074: The type referenced through 'Chessie.ErrorHandling.Result`2' is defined in an assembly that is not referenced. You must add a reference to assembly
 'Chessie'.
```
Although in the editor window it does not show any errors.

**Comment by forki** [comment] 2016-10-11 12:56
is that the correct chessie version?

**Comment by isaacabraham** [comment] 2016-10-11 12:59
That's the one that Nuget pulled down. ;-)

**Comment by isaacabraham** [comment] 2016-10-11 13:00
Perhaps there's a minimum required version of Chessie that should be specified in Paket.Core?

**Comment by forki** [comment] 2016-10-11 13:04
I guess that's the root cause. https://www.nuget.org/packages/Paket.Core doesn't specify a version.

brb

**Comment by forki** [comment] 2016-10-11 13:12
please retry

**Comment by isaacabraham** [comment] 2016-10-11 13:31
Same.

**Comment by forki** [comment] 2016-10-11 13:35
against chessie 0.6?

**Comment by isaacabraham** [comment] 2016-10-11 13:41
Correct

**Comment by forki** [comment] 2016-10-11 13:43
wtf

**Comment by forki** [comment] 2016-10-12 07:15
can you zip that sampe and add it here?

**Comment by isaacabraham** [comment] 2016-10-13 08:05
@forki let's review tomorrow / over the weekend together.

**Comment by enricosada** [comment] 2018-01-24 10:46
Closing, nupkg now specify Chessie version

**Closed by enricosada** 2018-01-24 10:46 UTC
