### ISSUE TITLE
paket.dependencies in submodules

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#1854] opened 2016-08-16 07:51 UTC
From @btrepp on gitter:

```
Does paket install ignore nested dependencies?
I have a submodule checked out in lib/submodule/ with its own packet.dependencies etc. 
Im fine with running what I need in there, but when I go to the high level project, 
it seems i need to add references for all the packages the submodule depends on to packet.dependencies 
or i get 
    "Paket failed with : ZZZ was referenced, but it was not found in the packet.lock file in group Main" 
when running packet install. The submodule does depend on ZZZ, but how does paket know this?.
```

I think we could at least stop Paket from going further down we it finds the second Paket.dependencies file

**Comment by forki** [comment] 2016-08-16 08:34
Mhm I can't reprodice. #9df758a shows that we skip files in subfolders if we find paket.dependencies

**Comment by Uriel6575** [comment] 2016-09-11 11:21
Not sure if I have the exact same issue, but I've managed to reproduce it.

You need to create a solution with a separate dependencies file and include some nuget package in there. Then create a project and add this package into project's references file. After that, inside the solution folder create a folder for submodule solution with it's own dependencies file and add some **different** package there. Then create a project in submodule solution with a corresponding references file. **And** add a reference from root project to submodule project. Now you can invoke install command for root solution and see this error.
Somehow github doesn't allow me to attach a zip file with an example solution, so if you need, you can get it here: https://dl.dropboxusercontent.com/u/4951862/SubmoduleTest.zip

**Comment by enricosada** [comment] 2018-01-24 11:07
Closing.

Dupe of https://github.com/fsprojects/Paket/issues/2054

**Closed by enricosada** 2018-01-24 11:07 UTC
