### ISSUE TITLE
`paket install` errors in a folder with `#` in the name

### ISSUE THREAD

**Issue by dsimunic** [fsprojects/Paket#745] opened 2015-04-01 10:46 UTC
When running `paket install` in a folder with `#` in the name (`/Users/user/Projects/Api/F#`), paket fails with "Could not find file":

    paket install
    Paket version 0.38.3.0
    Resolving packages:
     - Http.fs 1.5.1
    Locked version resolutions written to /Users/user/Projects/Api/F#/paket.lock
    Paket failed with:
        Could not find file "/Users/user/Projects/Api/F".

This is paket 0.38.3.0 on a mac with latest mono 3.12.1

Curiously, if the folder is renamed to `F S` (with a space in-between), the error does not appear.

**Comment by forki** [comment] 2015-04-01 10:48
I think this is a duplicate of https://github.com/fsprojects/Paket/issues/669

**Closed by forki** 2015-04-01 10:48 UTC
Labels: duplicate

**Comment by dsimunic** [comment] 2015-04-01 11:01
Thanks. Only checked open issues, so didn't see #669.
