### ISSUE TITLE
Can verbose mode be more and less verbose ?

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket#1559] opened 2016-03-29 17:04 UTC
Some times I try to investigate paket failures and this hard to do, verbose mode on one hand dumps all responses as it receives them and majority of the time this information is overly detailed and just complicates understanding. 

On the other hand it do not log other behaviors that are no network related , so I just stare into not changing screen for couple of minutes.

**Comment by forki** [comment] 2016-03-29 18:38
good idea. now we need to decide what/how we do that

**Comment by tsibelman** [comment] 2016-03-29 18:52
For web traffic for request I think it sufficient to write full urls as paket do now already, for response I think it need to just write OK if it receives http code 200 and if it receives some error codes it best to try parse received exception and to extract just the message with no stack trace.  

For other work it best to write message for every major operation, I less familiar what is going on there.

**Comment by forki** [comment] 2016-03-30 06:10
Please send PR(s)

**Comment by tsibelman** [comment] 2016-03-30 06:20
What time consuming operations paket do outside network ?

**Comment by forki** [comment] 2016-03-30 06:23
The resolver is NP-complete. It can be run into situations where our
heuristic doesn't perform well and has trouble to find a way out of a big
area of conflicts. Then it tests basically all version combinations.

**Comment by tsibelman** [comment] 2016-03-30 06:30
I did not saw high cpu usage during this.

**Comment by forki** [comment] 2016-03-30 07:04
yeah during that phase it's still requesting a lot.

**Comment by enricosada** [comment] 2018-01-24 13:15
closing. Dupe of https://github.com/fsprojects/Paket/issues/2070

**Closed by enricosada** 2018-01-24 13:15 UTC
Labels: enhancement, up-for-grabs
