### ISSUE TITLE
Paket latest version 401 Unauthorized

### ISSUE THREAD

**Issue by dustinmoris** [fsprojects/Paket#1469] opened 2016-02-11 12:45 UTC
When I use the latest version (2.50.2.0) I get an error when updating my packages:

```
Source 'http://teamcity.*****' exception: System.Exception: Could not retrieve data from http://teamcity.*****/odata/Packages(Id='****',Version='1.0.0.0')
 Message: One or more errors occurred.
 Details: The remote server returned an error: (401) Unauthorized.
   at Paket.Utils.getXmlFromUrl@282-6.Invoke(String message)
   at Paket.Utils.getXmlFromUrl@271-5.Invoke(Exception _arg2)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
Paket failed with:
        Couldn't get package details for package **** 1.0.0.0 on http://teamcity.*****.
```

It seems like Paket stops sending the Authorization header:

![image](https://cloud.githubusercontent.com/assets/4580714/12976571/02016b12-d0bd-11e5-84c6-8a6000af5617.png)

![image](https://cloud.githubusercontent.com/assets/4580714/12976596/37f6a96c-d0bd-11e5-9158-581ae92c0803.png)

When I download Paket version 2.36.7 it works.

**Comment by forki** [comment] 2016-02-11 12:51
Can you try to find the last version that still works? Would makes things easier for us to track down

**Comment by dustinmoris** [comment] 2016-02-11 12:53
Oh man :( That's a lot of versions in between...
The question is, am I the only one who is getting this? Because you can see that in the 2nd screenshot the Authorization header is not being sent. Should it not be easy to check in the code where the auth header gets set and what the reason could be for it to be ignored?

**Comment by forki** [comment] 2016-02-11 12:55
Can you try to find the please also try to run "paket update -f" so that we know it's not cache related

**Comment by dustinmoris** [comment] 2016-02-11 12:56
Okay, I'll have a look...

**Comment by forki** [comment] 2016-02-11 13:01
I ask because AFAIK our teamcity still works, so there must be something subtle. @agross how about you?

**Comment by dustinmoris** [comment] 2016-02-11 13:37
As I am trying to narrow it down I came across another issue now. When I revert back to v2.36.7 I get a parse error from a public NuGet packge on NuGet.org, which is completely unrelated to my initial issue. 

I will continue to narrow down the original issue, but it seems to me that the package pulling is extremely unstable. Makes me wonder if there was a good reason to completely reinvent everything instead of using the well tested and working NuGet client for some of the work like getting package information which would be the same for both products. -.-

**Comment by forki** [comment] 2016-02-11 13:45
what package?

**Comment by dustinmoris** [comment] 2016-02-11 13:46
https://www.nuget.org/packages/Darkseid/

**Comment by forki** [comment] 2016-02-11 13:54
facaf22 seems to work. How can I reproduce that? Is the parsing a real error or does only one of the intermediate proctols fail?

**Comment by dustinmoris** [comment] 2016-02-11 14:04
This is how I get the parsing error:

**paket.dependencies**

```
source https://nuget.org/api/v2

nuget Darkseid
```

**paket.lock**

```
NUGET
  remote: https://nuget.org/api/v2
  specs:
    Darkseid (0.2.0)
```

Then I run

```
paket.bootstrapper.exe 2.36.7
paket update Darkseid
```

And I get:

```
Paket version 2.36.7.0
Updating Darkseid in C:\Dev\test\paket.dependencies group Main
Resolving packages for group Main:
 - Darkseid 0.3.0
Paket failed with:
        Couldn't get package details for package Darkseid 0.3.0 on https://nuget.org/api/v2.
```

With verbose on:

```
...
Source 'https://nuget.org/api/v2' exception: System.Exception: unable to parse (, )
   at <StartupCode$Paket-Core>.$VersionRange.failParse@143-1.Invoke(String message)
   at <StartupCode$Paket-Core>.$VersionRange.parseRange@142(FSharpRef`1 prereleases, String text)
   at Paket.VersionRequirement.Parse(String text)
   at Paket.NuGetV2.split@158-1(String d)
   at Paket.NuGetV2.parseODataDetails[a](String nugetURL, PackageName packageName, a version, String raw)
   at Paket.NuGetV2.getDetailsFromNuGetViaOData@226-9.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
Paket failed with:
        Couldn't get package details for package Darkseid 0.3.0 on https://nuget.org/api/v2.
...
```

**Comment by forki** [comment] 2016-02-11 14:06
ah so that's only in older version and already fixed. Yes NuGet.org changed their dependencies format one night...

**Comment by dustinmoris** [comment] 2016-02-11 14:06
It also seems that the original issue which I reported happened after 2.36.7, because when I use the next version 2.37.0 I get the same issue as with the very latest.

I was looking at the changes https://github.com/fsprojects/Paket/compare/2.36.7...2.37.0 and there is quite some stuff that happened there so I need to have a closer look

**Comment by dustinmoris** [comment] 2016-02-11 14:07
okay, makes sense re parsing error

**Comment by domaslasauskas** [comment] 2016-02-11 17:36
The private package source in question is a private ProGet instance, but I don't think it makes a different as long as package source requires authentication.

I've tried debugging this issue. Not sure if that's the cause, but I've tracked missing authentication to [PackageResolver.getCompatibleVersions] (https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/PackageResolver.fs#L319) where `availableVersions` are [resolved from LockFile](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/UpdateProcess.fs#L138) which parses sources with authentication as `None`. However, it's not so obvious where this bug was introduced looking at [2.36.7...2.37.0](https://github.com/fsprojects/Paket/compare/2.36.7...2.37.0) changes.

Should Paket try to apply authentication to such sources at a later stage when downloading the package?

**Comment by forki** [comment] 2016-02-11 17:42
yes getcompatibleversion should only use sources with proper authentication.
We need to find the place where it lost the authentication

**Comment by forki** [comment] 2016-02-11 17:59
is there a way for me to reproduce?

**Comment by forki** [comment] 2016-02-11 18:11
> but I don't think it makes a different as long as package source requires authentication.

Just tried against myget and it works fine.

**Comment by domaslasauskas** [comment] 2016-02-12 11:25
I've started new private ProGet instance, and was able to [reproduce this issue](https://github.com/domaslasauskas/Paket-issue-1469) there.

While NonExistingPackage.* packages don't actually exist in this private package source, it's still possible to reproduce the issue, because Paket update fails with Unauthorized 401 response from server thus reproducing the bug.

You can reproduce the bug by running build.cmd, build.sh, or `paket.exe update nuget Darkseid version 0.3.0`. Hope this helps.

**Comment by dustinmoris** [comment] 2016-02-12 11:31
Thanks @domaslasauskas!

**Comment by forki** [comment] 2016-02-12 11:59
thans for createting a repero. but shouldn't https://github.com/domaslasauskas/Paket-issue-1469/blob/master/paket.dependencies#L2 contain username and pw so that I could theoretically get in?

**Comment by forki** [comment] 2016-02-12 12:31
but If I add this then I think I can reproduce and have an idea of what's going wrong.

**Comment by forki** [comment] 2016-02-12 13:22
ok found the bug. will fix later today

**Comment by forki** [comment] 2016-02-12 13:42
please try with 2.50.6

**Comment by domaslasauskas** [comment] 2016-02-12 14:13
It's fixed now, thanks!

Re: credentials - we don't store credentials in paket.dependencies, they are set using `paket config add-credentials` instead.

**Comment by dustinmoris** [comment] 2016-02-12 14:14
cheers!

**Closed** 2016-02-12 14:14 UTC
