### ISSUE TITLE
NewSdk and MultiTargeting and Conditions

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2596] opened 2017-08-10 01:37 UTC
I need to multitarget ``<TargetFrameworks>netstandard1.6;net40;net35</TargetFrameworks>``.

For net35 / net40, I need to reference FSharp.Core 3.1.
For ns16 I need to reference a higher version, currently I was thinking about just taking 4.2.2.

I tried to use conditions for this: 

```
group NetFx
	nuget FSharp.Core <= 3.1 redirects:force, content:None, CONDITION: NETFX

group NetStandard

	nuget FSharp.Core 4.2.2 redirects:force, content:None, Condition: NETSTANDARD
```

```
group NetStandard

	FSharp.Core

group NetFx

	FSharp.Core
```

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    
    <TargetFrameworks>netstandard1.6;net40;net35</TargetFrameworks>

    <NetStandard Condition=" '$(TargetFramework)' == 'netstandard1.6' ">True</NetStandard>
    <NetFx Condition=" '$(TargetFramework)' == 'net35' ">True</NetFx>
    <NetFx Condition=" '$(TargetFramework)' == 'net40' ">True</NetFx>

  </PropertyGroup>

```

``dotnet restore`` now fails with:

![image](https://user-images.githubusercontent.com/4236651/29150791-11bc3cb2-7d7d-11e7-95d0-f02a2538cfbd.png)

__Q:__ Is what I want even possible?

**Comment by matthid** [comment] 2017-08-10 05:12
First: You need to add a condition to your group.
Second: We don't support conditions on netcore jet

**Comment by 0x53A** [comment] 2017-08-10 08:48
> Second: We don't support conditions on netcore yet

Hm, do you know of another way to solve this? Or should I just use nuget?

**Comment by forki** [comment] 2017-08-10 09:04
@matthid why don't we support such conditions? What is missing?

**Comment by forki** [comment] 2017-08-10 09:20
This is seriously a fucked up situation with fsharp.core.
Apart from the question why we don't have restrictions for netcore yet, why does argu need net35 and net40? It will propagate the issue downstream.

**Comment by 0x53A** [comment] 2017-08-10 09:42
eirik had two requirements for any change: need to target net35 and need to target FSharp.Core <= 3.1

Unfortunately, you can't build against netstandard with FSharp.Core 3.1.

**Comment by forki** [comment] 2017-08-10 09:44
Yes that's completely broken now. /cc @kevinransom



Am 10.08.2017 11:42 vorm. schrieb "Lukas Rieger" <notifications@github.com>:

**Comment by 0x53A** [comment] 2017-08-10 09:45
Hm, I don't think this is the fault of fsc.

FSharp.Core 3.1 just doesn't contain a valid version for netstandard.

**Comment by forki** [comment] 2017-08-10 09:45
One temporary workaround could be to use two project files and build/pack
them both. Afterwards you can use nuget's merge task to merge the nupkgs.
But we should really make the framework restricted work.

Am 10.08.2017 11:44 vorm. schrieb "Steffen Forkmann" <sforkmann@gmail.com>:

**Comment by 0x53A** [comment] 2017-08-10 09:47
> One temporary workaround could be to use two project files and build/pack
them both. Afterwards you can use nuget's merge task to merge the nupkgs.
But we should really make the framework restricted work.

Yes. afaik that's how it is currently done.

But then it may be easier to just use nuget directly and ``<PackageReference Condition="..." ``.

**Comment by forki** [comment] 2017-08-10 09:49
Maybe you could try to help with making the restrictions work by adding some tests? . I don't think it's too much missing.

**Comment by matthid** [comment] 2017-08-10 12:13
I was talking about conditions not restrictions which is a entirely different feature.

Problem wirh restrictions are that we never resolve different versions... We cannot really detect that a package no longer supports a particular framework. so you can never resolve a different fsharp.core without help of the user

**Comment by KevinRansom** [comment] 2017-08-10 22:34
So ... I expected this to work:

````
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netstandard1.6;net40;net35</TargetFrameworks>
    <FSharpCoreImplicitPackageVersion>4.1.17</FSharpCoreImplicitPackageVersion>
    <DisableImplicitSystemValueTupleReference>true</DisableImplicitSystemValueTupleReference>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
````
However it fails with this output:
````
c:\temp\aproj\aproj.fsproj : error NU1202: Package System.ValueTuple 4.3.0 is not compatible with net35 (.NETFramework,Version=v3.5). Package System.ValueTuple 4.3.0 supports:\r
c:\temp\aproj\aproj.fsproj : error NU1202:   - netstandard1.0 (.NETStandard,Version=v1.0)\r
c:\temp\aproj\aproj.fsproj : error NU1202:   - portable-net40+sl4+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile36)
c:\temp\aproj\aproj.fsproj : error NU1202: Package System.ValueTuple 4.3.0 is not compatible with net35 (.NETFramework,Version=v3.5) / win7-x86. Package System.ValueTuple 4.3.0 supports:\r
c:\temp\aproj\aproj.fsproj : error NU1202:   - netstandard1.0 (.NETStandard,Version=v1.0)\r
c:\temp\aproj\aproj.fsproj : error NU1202:   - portable-net40+sl4+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile36)
````

As you can see I specifically disabled the automagic package reference to System.ValueTuple even if it did that should find a much higher version than 4.3.0.  I hypothesize that nuget restore is verifying:
this from the 4.1.17 nuspec against the net35 target

````
      <group>
        <dependency id="System.ValueTuple" version="4.3.0" />
      </group>
````
We don't have that in the 4.1.x nuget package that we build in our build.  I haven't deployed a 4.1.18 nuget package but I could if the community is happy that we make this change.

It will break builds who are reliant on referencing fsharp.core 4.1.17 pulling down the system.valuetuple nuget package.

So ... I tried it out with a local copy of the 4.1.18 version of the package and it worked fine:
````
c:\temp\aproj>dotnet restore
  Restoring packages for c:\temp\aproj\aproj.fsproj...
  Installing FSharp.Core 4.1.18.
  Generating MSBuild file c:\temp\aproj\obj\aproj.fsproj.nuget.g.props.
  Restore completed in 1.6 sec for c:\temp\aproj\aproj.fsproj.
````
Should I publish 4.1.18 without the dependence on System.ValueTuple.dll?

Kevin

**Comment by 0x53A** [comment] 2017-08-11 09:32
@KevinRansom Thanks!

> So ... I tried it out with a local copy of the 4.1.18 version of the package and it worked fine:

Can you please try if ``dotnet pack`` also succeeds?

> Should I publish 4.1.18 without the dependence on System.ValueTuple.dll?

Yes, I think it would be good to have a version of FSharp.Core that can be used to target everything from netfx3.5 to netstandard2.0

----

I did a different test (because I don't have 4.1.18):

```Xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>netstandard1.6;net35;</TargetFrameworks>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    <DisableImplicitSystemValueTupleReference>true</DisableImplicitSystemValueTupleReference>

    <FrameworkPathOverride Condition=" '$(TargetFramework)' == 'net35' ">C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.5</FrameworkPathOverride>
    <!--<FrameworkPathOverride Condition=" '$(TargetFramework)' == 'net35' ">D:\temp\v3.5</FrameworkPathOverride>-->
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" Version="3.0.2" Condition=" '$(TargetFramework)' == 'net35' " />
    <PackageReference Include="FSharp.Core" Version="4.2.2" Condition=" '$(TargetFramework)' != 'net35' " />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>

</Project>
```

Without the explicit ``FrameworkPathOverride`` it complained about not finding the Reference Assemblies.

With the explicit ``FrameworkPathOverride``, it fails with
![image](https://user-images.githubusercontent.com/4236651/29207978-7d68e288-7e88-11e7-81b9-fb547e55b76e.png)

![image](https://user-images.githubusercontent.com/4236651/29207993-8781377a-7e88-11e7-9b91-c322bd619ea3.png)

@KevinRansom can you please test if compiling (and packing!) against net35 works for you?

**Comment by matthid** [comment] 2017-08-27 14:19
I think we could "fix" this is we generate a real "MSbuild" file with the actual `PackageReference` items (and add the conditions like we do as of today) instead of our "new" references file.

**Comment by 0x53A** [comment] 2017-08-27 21:23
I think I would rather implement https://github.com/fsprojects/Paket/issues/2606, so that the user can condition the ``<PaketReference`` inside his main project file.

**Comment by matthid** [comment] 2017-08-27 21:45
Ok go ahead :). I think it might be asking for a lot more trouble than you think (depending on how we implement it - obviously you could just use them as marker and let msbuild ignore them completely)

**Comment by 0x53A** [comment] 2017-08-27 21:54
hm, my idea was to just pass them as commandline parameters to paket here: https://github.com/fsprojects/Paket/compare/master...0x53A:paket-references-xml?expand=1#diff-c17f23be41fa3f5b94dff83d2c955208R24

That means you can use them almost exactly like "PackageReference", including making them conditional, or adding them via some Directory.Build.props, etc.

**Comment by matthid** [comment] 2017-08-27 21:58
I changed that process a bit :)

**Comment by enricosada** [comment] 2018-01-24 16:34
Closing. dupe of https://github.com/fsprojects/Paket/issues/2394

**Closed by enricosada** 2018-01-24 16:34 UTC
Labels: sdk: dotnet/sdk
