### ISSUE TITLE
Source-Only NuGet packages add <Compile Include="..." /> to csproj, resulting in build errors. 

### ISSUE THREAD

**Issue by btodts** [fsprojects/Paket#3269] opened 2018-06-26 09:12 UTC
### Description

Paket Installing a source-only NuGet package adds a Compile element to the csproj file, which leads to build errors in the new dotnet sdk: `Duplicate Compile items were included. The .NET SDK includes Compile items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultCompileItems' property to 'false' if you want to explicitly include them in your project file.`

### Repro steps

1. Step A

Add e.g. [TinyIoC](https://www.nuget.org/packages/TinyIoC/) to your `paket.dependencies` and `paket.references` of your dotnet 1.1+ console application.

2. Step B

Run `paket Install`. 

### Expected behavior

The files in the Content folder of the NuGet package (in TinyIoC's case, `TinyIoC.cs`) are added to the project. Since the dotnet sdk moved the globs to include compile items to the properties of the sdk, it isn't necessary that an element (`<Compile Include="TinyIoC.cs" />`) is added to the cspoj. Expected behavior is therefore that this doesn't happen. (more info: https://aka.ms/sdkimplicititems)

### Actual behavior

It does :) A Compile element is added to the csproj, which causes build errors (see above).

### Known workarounds

The error goes away when you remove the element from the csproj, but it is added again after every `paket Install`, which is unfortunate.

**Comment by btodts** [comment] 2018-07-04 07:39
Ping. Anybody there?

**Comment by forki** [comment] 2018-07-04 07:41
can you please upload a zip with a repro. Maybe I find some time before next vacation

**Comment by btodts** [comment] 2018-07-04 08:29
[PaketRepro.zip](https://github.com/fsprojects/Paket/files/2162409/PaketRepro.zip)
@forki Repro attached.

Steps to reproduce:
1. (just to make sure) Build the project. This should succeed.
2. Run `paket install`: this adds a file `TinyIoC.cs` to the project **and** adds an `ItemGroup` element to the csproj file.
3. Build now breaks because of that `ItemGroup` element (specifically, the `<Compile Include="TinyIoC.cs">` element).

**Comment by forki** [comment] 2018-07-04 09:01
ok fixed in latest alpha

**Closed** 2018-07-04 09:02 UTC

**Comment by btodts** [comment] 2018-07-06 09:29
@forki Unfortunately, files from the NuGet packages aren't copied to the directory anymore now (using paket 5.174.0). You can reproduce this with the zip file I provided earlier.

**Comment by forki** [comment] 2018-07-06 09:32
@btodts to which directory? we now rely fully on the nuget functionality. I thought that was the plan here

**Comment by btodts** [comment] 2018-07-06 09:35
The project folder that contains the `paket.references` file.
For clarification:
**Pre 5.174.0**: files from the NuGet package's Content folder were copied to the project folder during paket install **but** also added an element to the csproj (which caused errors).
**5.174.0**: said files in the Content folder are no longer copied to the project folder

**Comment by forki** [comment] 2018-07-06 09:46
ok, but should't the PackageReference handle this now? how would it wor in vanilla nuget? It makes no sense to me yet

**Comment by forki** [comment] 2018-07-06 10:35
yes, but what do we need to change? how would it work in vanilla nuget?

**Comment by btodts** [comment] 2018-07-06 10:59
Well, upon `paket install`, the csproj file shouldn't be changed when using .NET core 1.0+.
I tried reproducing it with vanilla nuget, but unfortunately I can currently only get it work with the .NET Framework, not .NET core...

**Comment by btodts** [comment] 2018-07-06 11:09
FYI, I've updated the issue I previously posted over @ NuGet to investigate the missing behaviour when using .NET Core: https://github.com/NuGet/Home/issues/7053

**Comment by CumpsD** [comment] 2018-07-30 14:59
@forki I think this change introduced a new bug. After debugging with @btodts we found the following:

In this commit: https://github.com/fsprojects/Paket/commit/4f40b2fa31f8c65ec924cdb1fbaba2e9af38e910 `Map.empty` was introduced, causing no more `Content` to be copied and no more `Content` nodes to be added to a csproj. 

When we revert this to the old syntax, we get the desired functionality again, seeing these are generated inside the csproj:

```xml
    <Content Include="MunicipalityRegistry.Api.Legacy.xml">
      <Paket>True</Paket>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
```

The problem @btodts had was it would generate `<Compile Include=....` nodes for files ending on `.cs`, which the new Core compiler chokes on because it has duplicate Compile nodes. 

This actually comes from: https://github.com/fsprojects/Paket/blob/b3bf2fbf69c5dff17279431966b6cc9287044dbd/src/Paket.Core/PaketConfigFiles/ProjectFile.fs#L1566-L1567

```fsharp
 let determineBuildAction fileName (project:ProjectFile) =
        match (Path.GetExtension fileName).ToLowerInvariant() with
        | ext when Path.GetExtension project.FileName = ext + "proj"
            -> BuildAction.Compile
        | ".fsi" -> BuildAction.Compile
        | ".xaml" -> BuildAction.Page
        | ".ttf" | ".png" | ".ico" | ".jpg" | ".jpeg"| ".bmp" | ".gif"
        | ".wav" | ".mid" | ".midi"| ".wma" | ".mp3" | ".ogg" | ".rma"
        | ".avi" | ".mp4" | ".divx"| ".wmv"  //TODO: and other media types
            -> BuildAction.Resource
        | _ -> BuildAction.Content
```

I think (not sure how to do it), the match on `ext when Path.GetExtension project.FileName = ext + "proj"` should somehow take the toolsversion into account and not add `cs` as a Compile but as a Content.

If that makes any sense? Maybe you can shed a light on how to approach this change? Something along the lines of:

```fsharp
    let determineBuildAction fileName (project:ProjectFile) =
        match (Path.GetExtension fileName).ToLowerInvariant() with
        | ext when Path.GetExtension project.FileName = ext + "proj"
			-> match getToolsVersion project with
                | 15.0 -> BuildAction.Content
                | _ -> BuildAction.Compile
        | ".fsi" -> BuildAction.Compile
        | ".xaml" -> BuildAction.Page
        | ".ttf" | ".png" | ".ico" | ".jpg" | ".jpeg"| ".bmp" | ".gif"
        | ".wav" | ".mid" | ".midi"| ".wma" | ".mp3" | ".ogg" | ".rma"
        | ".avi" | ".mp4" | ".divx"| ".wmv"  //TODO: and other media types
            -> BuildAction.Resource
        | _ -> BuildAction.Content
```

**Comment by CumpsD** [comment] 2018-07-30 15:09
PR coming.... Verified the proposal, fixes the issue and solves the regression

**Comment by CumpsD** [comment] 2018-07-30 15:20
There you go :)
