### ISSUE TITLE
net461 + netstandard issue

### ISSUE THREAD

**Issue by miloszes** [fsprojects/Paket#2779] opened 2017-09-20 09:02 UTC
Hi,

I've created a simple .net standard 2 library containing a one class. When I install it with .net core projects it's linked correctly.
In case I install it into the .net Framework 4.6.1 project the reference package is not linked (when I install it using nuget everything is fine). When I run install in the verbose mode I can see that it uses the ToolsVersion 14. Is it correct that paket uses ToolsVersion 14 when linking .net standard libraries? 

Can anyone help me to determine the problem?

Best regards,
MiloszeS

### Repro steps

Create netstandard 2 library and create a nuget package

1. install it using paket for a .NetFramework 4.6.1

The package won't be linked. 

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

Package is installed with paket.

### Actual behavior

Package is not installed. The logs:

> 

 .paket\paket.exe install --verbose
Paket version 5.97.0
found: D:\Sandbox\Nuget\Net46Console\paket.dependencies
Parsing D:\Sandbox\Nuget\Net46Console\paket.dependencies
Resolving packages for group Main:
   0 packages in resolution.
   1 requirements left
     - NetStandardSharedLibrary,  (from D:\Sandbox\Nuget\Net46Console\paket.dependencies)

  Trying to resolve NetStandardSharedLibrary  (from D:\Sandbox\Nuget\Net46Console\paket.dependencies)
Starting request to 'https://www.nuget.org/api/v2/FindPackagesById()?semVerLevel=2.0.0&id='NetStandardSharedLibrary''
Starting request to 'https://xxx/repository/library-dev/FindPackagesById()?semVerLevel=2.0.0&id='NetStandardSharedLibrary''
Source 'https://xxx/repository/library-dev' yielded (0): [0.0.1 ; 0.0.1.1]
 - Request 'https://xxx/repository/library-dev/FindPackagesById()?semVerLevel=2.0.0&id='NetStandardSharedLibrary'' finished with: [0.0.1 ; 0.0.1.1]
 - Request 'https://xxx/repository/library-dev/Packages?semVerLevel=2.0.0&$filter=Id eq 'NetStandardSharedLibrary'' was cancelled (another one was faster)
Source 'https://www.nuget.org/api/v2' yielded (0): []
 - Request 'https://www.nuget.org/api/v2/FindPackagesById()?semVerLevel=2.0.0&id='NetStandardSharedLibrary'' finished with: []
 - Request 'https://www.nuget.org/api/v2/Packages?semVerLevel=2.0.0&$filter=Id eq 'NetStandardSharedLibrary'' was cancelled (another one was faster)

 - NetStandardSharedLibrary 0.0.1.1
Starting request to 'https://xxx/repository/library-dev/Packages(Id='netstandardsharedlibrary',Version='0.0.1.1')'
Response from https://xxx/repository/library-dev/Packages(Id='netstandardsharedlibrary',Version='0.0.1.1'):

  <entry xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom">
    <id>https://xxx/repository/library-dev/Packages(Id='NetStandardSharedLibrary',Version='0.0.1.1')</id>
    <title type="text">NetStandardSharedLibrary</title>
    <summary type="text">Package Description</summary>
    <updated>2017-09-20T08:37:41.518Z</updated>
    <author>
      <name>NetStandardSharedLibrary</name>
    </author>
    <link rel="edit-media" title="V2FeedPackage" href="Packages(Id='NetStandardSharedLibrary',Version='0.0.1.1')/$value" />
    <link rel="edit" title="V2FeedPackage" href="Packages(Id='NetStandardSharedLibrary',Version='0.0.1.1')" />
    <category term="NuGetGallery.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
    <content type="application/zip" src="https://xxx/repository/library-dev/NetStandardSharedLibrary/0.0.1.1" />
    <m:properties>
      <d:Version>0.0.1.1</d:Version>
      <d:Copyright m:null="true"></d:Copyright>
      <d:Created m:type="Edm.DateTime">2017-09-20T08:37:41.519Z</d:Created>
      <d:Dependencies m:null="true"></d:Dependencies>
      <d:Description>Package Description</d:Description>
      <d:DownloadCount m:type="Edm.Int32">0</d:DownloadCount>
      <d:GalleryDetailsUrl m:null="true"></d:GalleryDetailsUrl>
      <d:IconUrl m:null="true"></d:IconUrl>
      <d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion>
      <d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion>
      <d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease>
      <d:Published m:type="Edm.DateTime">2017-09-20T08:37:41.519Z</d:Published>
      <d:Language m:null="true"></d:Language>
      <d:LicenseUrl m:null="true"></d:LicenseUrl>
      <d:PackageHash>Y3w/4WkCSncJf50vbtOtBhrUgCGlYr4fnnqK2GO9s/9ByQ+UMRwx8RKrpPWBhZ5a6DZ+bMyYtcrj8i5131YOkw==</d:PackageHash>
      <d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
      <d:PackageSize m:type="Edm.Int64">8346</d:PackageSize>
      <d:ProjectUrl m:null="true"></d:ProjectUrl>
      <d:ReportAbuseUrl m:null="true"></d:ReportAbuseUrl>
      <d:ReleaseNotes m:null="true"></d:ReleaseNotes>
      <d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
      <d:Tags m:null="true"></d:Tags>
      <d:Title>NetStandardSharedLibrary</d:Title>
      <d:VersionDownloadCount m:type="Edm.Int32">0</d:VersionDownloadCount>
    </m:properties>
  </entry>

   Found Explored Package  NetStandardSharedLibrary 0.0.1.1
Locked version resolution written to D:\Sandbox\Nuget\Net46Console\paket.lock
Installing into projects:
 - Creating model and downloading packages.
Downloading NetStandardSharedLibrary 0.0.1.1
Downloading directly from DownloadLink: https://xxx/repository/library-dev/NetStandardSharedLibrary/0.0.1.1
Downloading from https://xxx/repository/library-dev/NetStandardSharedLibrary/0.0.1.1 to C:\Users\xxx\.nuget\packages\NetStandardSharedLibrary\0.0.1.1\NetStandardSharedLibrary.0.0.1.1.nupkg
Downloaded NetStandardSharedLibrary 0.0.1.1 from https://xxx/repository/library-dev/NetStandardSharedLibrary/0.0.1.1.
NetStandardSharedLibrary 0.0.1.1 unzipped to D:\Sandbox\Nuget\Net46Console\packages\NetStandardSharedLibrary
 - Net46Console/paket.references -> Net46Console/Net46Console.csproj
Installing to D:\Sandbox\Nuget\Net46Console\Net46Console\Net46Console.csproj with ToolsVersion 14
    - Deleting Paket Reference nodes
Project D:\Sandbox\Nuget\Net46Console\Net46Console\Net46Console.csproj changed
Performance:
 - Resolver: 1 second (1 runs)
    - Runtime: 138 milliseconds
    - Blocked (retrieving package details): 434 milliseconds (1 times)
    - Blocked (retrieving package versions): 973 milliseconds (1 times)
 - Disk IO: 47 milliseconds
 - Average Download Time: 298 milliseconds
 - Number of downloads: 1
 - Average Request Time: 560 milliseconds
 - Number of Requests: 3
 - Runtime: 3 seconds

### Known workarounds

Install with nuget.

**Comment by matthid** [comment] 2017-10-14 16:06
Probably a duplicate of https://github.com/fsprojects/Paket/pull/2391, please follow the PR and the related Issues.

**Comment by matthid** [comment] 2017-10-14 16:07
And https://github.com/fsprojects/Paket/issues/2705

**Closed by matthid** 2017-10-14 16:06 UTC
