### ISSUE TITLE
Support for other GIT repositories

### ISSUE THREAD

**Issue by xgalaxy** [fsprojects/Paket#1229] opened 2015-11-16 19:11 UTC
I'd like to see support for other GIT based repositories. For example, at my work we use GitHub Enterprise and there doesn't appear to be a way to configure paket to use our special GitHub Enterprise URL for specific dependencies. Additionally, supporting places like BitBucket would be helpful as well.

Having the URL to the git repo be an optional specifier on a github entry in the paket dependency file could be one way of solving this.

Additionally, for GitHub Enterprise, credential keys would need to be supported.

**Comment by matneyx** [comment] 2015-11-17 16:16
We're in the same boat.  Our work around has been having our build gems copy a compiled version to our fileshare, and we aim all of our paket.dependencies at that fileshare.  It's not perfect, but it gets us the most recent builds.

**Comment by forki** [comment] 2015-11-17 16:20
this is a duplicate of https://github.com/fsprojects/Paket/issues/284
I already started some tests, but if someone wants to help....

**Closed by forki** 2015-11-17 16:20 UTC
