### ISSUE TITLE
dotnet build unable to locate references

### ISSUE THREAD

**Issue by BlythMeister** [fsprojects/Paket#3507] opened 2019-02-19 13:18 UTC
### Description

Since 5.197.0 when running a dotnet build every paket/nuget reference states it cannot be found

### Repro steps

See attached [PaketRepo.zip](https://github.com/fsprojects/Paket/files/2880101/PaketRepo.zip).
Run run.bat when version = 5.169.2 - works
Run run.bat when version = 5.197.1 - build failure unable to locate json

Also see attached the 2 obj folders [ObjFolderCompare.zip](https://github.com/fsprojects/Paket/files/2880102/ObjFolderCompare.zip)

### Expected behavior

Both versions can build

### Actual behavior

new version does not build

### Known workarounds

Pin to working version

**Comment by forki** [comment] 2019-02-19 13:23
5.197.2 does that one work?

**Comment by BlythMeister** [comment] 2019-02-19 13:40
Yup.  what changed :p

**Comment by BlythMeister** [comment] 2019-02-19 13:40
also...my version numbers in the op were wrong..but i figure you worked out what i meant :D

**Comment by forki** [comment] 2019-02-19 13:41
closing as dupe of https://github.com/fsprojects/Paket/issues/3506

**Closed by forki** 2019-02-19 13:41 UTC

**Comment by BlythMeister** [comment] 2019-02-19 13:42
🤦‍♂️ started raising issue, went into meeting...came back finished raising...someone else raises whilst i'm afk!
