### ISSUE TITLE
Conditional package references

### ISSUE THREAD

**Issue by yevhen** [fsprojects/Paket#2612] opened 2017-08-14 20:03 UTC
In a mixed solution where some of the projects use new VS17 csproj format and target multiple frameworks (net462/nestandard) conditional references are required for some scenarios, such as referencing `System.AppDomain` for netstandard but not when building for net46.

Example:

```xml
<ItemGroup>
  <PackageReference Include="System.AppDomain" Version="2.0.11"
                    Condition="'$(TargetFrameworkIdentifier)' == '.NETStandard'" />
</ItemGroup>
```

Would be great to have this supported in `paket.dependencies` and/or `paket.references`

**Comment by TheAngryByrd** [comment] 2017-08-31 16:21
Similar to https://github.com/fsprojects/Paket/issues/2394

**Comment by enricosada** [comment] 2018-01-24 16:24
Closing as pratically a dupe of #2394 

@yevhen adding your use case to that issue, work will be tracked in #2394

**Closed by enricosada** 2018-01-24 16:24 UTC
Labels: enhancement, msbuild proj, sdk: dotnet/sdk
