### ISSUE TITLE
Magic Mode bootstrapper doesn't respect --force-nuget

### ISSUE THREAD

**Issue by yaakov-h** [fsprojects/Paket#2876] opened 2017-10-31 00:18 UTC
### Description

When using the bootstrapper in magic mode with `--force-nuget` and `--nuget-source=`, it still attempts to access the public NuGet gallery.

### Repro steps

1. Add the following to the top of `paket.dependencies`:

> `version 5.119.0 --force-nuget --nuget=source=http://my-proget-server/nuget/Gallery/ -v`

Where `my-proget-server` is a ProGet server and `Gallery` is the name of a gallery which mirrors the public NuGet gallery.

2. Add `paket.bootstrapper.exe` as `.paket\paket.exe`

On a computer without public internet access:

3. Run `.paket\paket.exe restore`

### Expected behavior

The Bootstrapper downloads the specified version from the ProGet server

### Actual behavior

The Bootstrapper attempts to download the specified version from NuGet, and fails.

```
Checking Paket version (version 5.119.0 requested)...
Version 5.119.0 not found in cache.
Starting download from https://www.nuget.org/api/v2/package/Paket/5.119.0
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at Paket.Bootstrapper.HelperProxies.WebRequestProxy.DownloadFile(String url, String targetLocation)
   at Paket.Bootstrapper.DownloadStrategies.NugetDownloadStrategy.DownloadVersionCore(String latestVersion, String target, PaketHashFile hashfile)
The remote server returned an error: (403) Forbidden. (Nuget - cached)
```

**Comment by forki** [comment] 2017-10-31 06:22
@vbfox

Am 31.10.2017 01:18 schrieb "Yaakov" <notifications@github.com>:

**Comment by vbfox** [comment] 2017-10-31 08:49
Can you assign to me ?

I find weird that it doesn't work we have the exact same config, with proget as server too (Except we use prefer nuget instead of force nuget) but need to dig into it to reprod

**Comment by forki** [comment] 2017-10-31 09:04
No can't since you are not listed there

**Comment by vbfox** [comment] 2017-10-31 13:42
What's the magic incantation to be assignable to issues ?

**Comment by forki** [comment] 2017-10-31 13:47
No idea tbh

Am 31.10.2017 14:43 schrieb "Julien Roncaglia" <notifications@github.com>:

**Comment by yaakov-h** [comment] 2017-10-31 22:16
I think you have to be a Member of the project or organization.

**Comment by yaakov-h** [comment] 2017-11-06 02:18
FWIW, I'm also seeing the exact same behaviour with `--prefer-nuget`.

**Comment by vbfox** [comment] 2017-11-06 08:33
@yaakov-h I tested it and it works as expected.

The sample line in your issue can't work because `--nuget=source` isn't a valid key but if I replace it with `--nuget-source` (And add an additional -v to get verbose mode) I get :

```
Using strategy: Nuget - cached
Checking Paket version (version 5.119.0 requested)...
Target path is C:\Users\jroncagl\AppData\Local\Temp\paket_6F0E7FE14CA35BF651C1D208F8251A7CF4123EDD3E22FD83F57115FBF3E60B69.exe
File doesn't exists, no version information: C:\Users\jroncagl\AppData\Local\Temp\paket_6F0E7FE14CA35BF651C1D208F8251A7CF4123EDD3E22FD83F57115FBF3E60B69.exe
File in target path version: vUNKNOWN
Downloading v5.119.0 ...
[Nuget - cached] DownloadVersion...
Version 5.119.0 not found in cache.
[Nuget] DownloadVersion...
Starting download from http://my-proget-server/nuget/Gallery//package/Paket/5.119.0
System.Net.WebException: The remote name could not be resolved: 'my-proget-server'
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at Paket.Bootstrapper.HelperProxies.WebRequestProxy.DownloadFile(String url, String targetLocation)
   at Paket.Bootstrapper.DownloadStrategies.NugetDownloadStrategy.DownloadVersionCore(String latestVersion, String target, PaketHashFile hashfile)
[Nuget] DownloadVersion took 0,95 second(s) and failed with 'The remote name could not be resolved: 'my-proget-server''.

[Nuget - cached] DownloadVersion took 0,95 second(s) and failed with 'The remote name could not be resolved: 'my-proget-server''.
The remote name could not be resolved: 'my-proget-server' (Nuget - cached)
```

**Comment by yaakov-h** [comment] 2017-11-06 09:23
Haha, that would explain it. I'll have to check tomorrow with the correct command-line argument.

Shouldn't the bootstrapper reject invalid arguments, rather than silently ignoring them?

**Comment by vbfox** [comment] 2017-11-06 09:31
I would be in favor of making it reject invalid arguments but it would be a breaking change at that point @forki  ?

**Comment by yaakov-h** [comment] 2017-11-09 03:05
Checked, and it works as designed/advertised if I actually pass in the correct command-line arguments.

Should I leave this Issue open for the invalid argument handling, or should we move that to a new one?

**Comment by yaakov-h** [comment] 2017-11-12 22:18
Actually, scratch that - I have a strange case now.

Here's the version line from `paket.dependencies`, with a modified hostname:

```
version 5.120.1 --force-nuget --nuget-source=http://proget-server/nuget/Gallery/ -v
```

Here's the captured output - possibly `stderr` only, I'd have to check -  from the build system, using the magic-mode bootstrapper:

```
Execute .paket\paket.exe restore
ExitCode = 1
.paket\paket.exe exited with code 1.

The remote server returned an error: (403) Forbidden. (Github - cached (temporarily ignore updates))
```

It looks like it didn't even attempt NuGet.

**Comment by vbfox** [comment] 2017-11-13 12:55
Can you send a log with 2 times `-v` ?

On my PC with a version in cache :

```
C:\Code\_temp\paket_2876>paket restore
Using strategy: Nuget - cached
Checking Paket version (version 5.120.1 requested)...
Target path is C:\Users\jroncagl\AppData\Local\Temp\paket_2D3B10E74417154E354A58C34EAEC46E83423464D01ABDD8EE3B11A2C5C045D8.exe
File doesn't exists, no version information: C:\Users\jroncagl\AppData\Local\Temp\paket_2D3B10E74417154E354A58C34EAEC46E83423464D01ABDD8EE3B11A2C5C045D8.exe
File in target path version: vUNKNOWN
Downloading v5.120.1 ...
[Nuget - cached] DownloadVersion...
No hashFile file expected, bypassing check.
Copying version 5.120.1 from cache.
C:\Users\jroncagl\AppData\Local\NuGet\Cache\Paket\5.120.1\paket.exe -> C:\Users\jroncagl\AppData\Local\Temp\paket_2D3B10E74417154E354A58C34EAEC46E83423464D01ABDD8EE3B11A2C5C045D8.exe
[Nuget - cached] DownloadVersion took 0,13 second(s) and returned 'void'.
Download took 0,13 second(s)
Done in 0,17 second(s).
Paket Bootstrapping took 0,17 second(s)
```

Second run:

```
C:\Code\_temp\paket_2876>paket restore
Using strategy: Nuget - cached
Checking Paket version (version 5.120.1 requested)...
Target path is C:\Users\jroncagl\AppData\Local\Temp\paket_2D3B10E74417154E354A58C34EAEC46E83423464D01ABDD8EE3B11A2C5C045D8.exe
File in target path version: v5.120.1
Paket.exe 5.120.1 is up to date.
Paket Bootstrapping took 0,1 second(s)
```

Specifying a version not in cache :

```
C:\Code\_temp\paket_2876>paket restore
Using strategy: Nuget - cached
Checking Paket version (version 5.122.0 requested)...
Target path is C:\Users\jroncagl\AppData\Local\Temp\paket_2D3B10E74417154E354A58C34EAEC46E83423464D01ABDD8EE3B11A2C5C045D8.exe
File in target path version: v5.120.1
Downloading v5.122.0 ...
[Nuget - cached] DownloadVersion...
Version 5.122.0 not found in cache.
[Nuget] DownloadVersion...
Starting download from http://proget-server/nuget/Gallery//package/Paket/5.122.0
System.Net.WebException: The remote name could not be resolved: 'proget-server'
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at Paket.Bootstrapper.HelperProxies.WebRequestProxy.DownloadFile(String url, String targetLocation)
   at Paket.Bootstrapper.DownloadStrategies.NugetDownloadStrategy.DownloadVersionCore(String latestVersion, String target, PaketHashFile hashfile)
[Nuget] DownloadVersion took 2,38 second(s) and failed with 'The remote name could not be resolved: 'proget-server''.
[Nuget - cached] DownloadVersion took 2,38 second(s) and failed with 'The remote name could not be resolved: 'proget-server''.
The remote name could not be resolved: 'proget-server' (Nuget - cached)
```

If it does something else, please post a git repository reproducing the issue.

**Comment by yaakov-h** [comment] 2017-11-21 23:03
I can't reproduce all the time, so I've had to resort to cookie-jar debugging, i.e. waiting for it to fail, then seeing who's hand is in the cookie jar.

I have a very strange example here.

My project structure is as follows:

```
.editorconfig
.paket\
    paket.exe (bootstrapper)
NuGet.config (which I don't expect paket to use)
paket.dependencies
paket.lock
src\
    source code here
```    

Here is the first line of my `paket.dependencies` file, verbatim:

```
version 5.122.0 --force-nuget --nuget-source=http://proget.wtg.zone/nuget/Gallery/ -v -v
```

Here is the output from `.paket\paket.exe restore`:

```
The remote server returned an error: (403) Forbidden. (Github - cached (temporarily ignore updates))

```

It's as though the bootstrapper isn't even reading `paket.dependencies`.

**Comment by yaakov-h** [comment] 2017-11-22 00:14
A-ha, I've narrowed it down.

The bootstrapper doesn't use `paket.dependencies`, if `paket.dependencies` is read-only. I use Team Foundation Version Control with an Online Workspace, so all files that are not checked-out are marked as read-only.

```
C:\My\Build\Path>attrib paket.dependencies
A    R       C:\My\Build\Path\paket.dependencies

C:\My\Build\Path>.paket\paket.exe restore
Unable to connect to the remote server (Github - cached (temporarily ignore updates))

C:\My\Build\Path>attrib -R paket.dependencies

C:\My\Build\Path>.paket\paket.exe restore
Using strategy: Nuget - cached
Checking Paket version (version 5.122.0 requested)...
Target path is C:\Users\Yaakov.Smith\AppData\Local\Temp\3\paket_78B0A864FA719CC4EF7372174D393E5EA74F96E71B778EF5A58BC170058E8691.exe
File doesn't exists, no version information: C:\Users\Yaakov.Smith\AppData\Local\Temp\3\paket_78B0A864FA719CC4EF7372174D393E5EA74F96E71B778EF5A58BC170058E8691.exe
File in target path version: vUNKNOWN
Downloading v5.122.0 ...
[Nuget - cached] DownloadVersion...
No hashFile file expected, bypassing check.
Copying version 5.122.0 from cache.
C:\Users\Yaakov.Smith\AppData\Local\NuGet\Cache\Paket\5.122.0\paket.exe -> C:\Users\Yaakov.Smith\AppData\Local\Temp\3\paket_78B0A864FA719CC4EF7372174D393E5EA74F96E71B778EF5A58BC170058E8691.exe
[Nuget - cached] DownloadVersion took 0.02 second(s) and returned 'void'.
Download took 0.02 second(s)
Done in 0.06 second(s).
Paket Bootstrapping took 0.06 second(s)
Paket version 5.122.0
Performance:
 - Runtime: 1 second
Paket failed with
-> UnauthorizedAccessException: Access to the path 'C:\My\Build\Path\src\MyProject\obj\MyProject.csproj.paket.references.cached' is denied.

C:\My\Build\Path>
```

**Comment by yaakov-h** [comment] 2017-11-22 00:26
It appears to me that:

* The bootstrapper uses `IFileSystemProxy.OpenRead` to open `paket.dependencies`
* This is implemented by `Paket.Bootstrapper.HelperProxies.FileSystemProxy.OpenRead`
* `OpenRead` calls `WaitForFileOpen`
* `WaitForFileOpen` tries to open the file with [`FileAccess.ReadWrite`](https://github.com/fsprojects/Paket/blob/master/src/Paket.Bootstrapper/HelperProxies/FileSystemProxy.cs#L49), which of course won't work for a read-only file.

**Comment by vbfox** [comment] 2017-11-27 10:16
Wow, thanks for the analysis, the `WaitForFileOpen` part is a recent change to avoid bad interactions between bootstrapper instances but it seem I fucked up there :)

I'll fix it, thanks again 👍

**Closed** 2017-11-29 08:20 UTC
