### ISSUE TITLE
Forcing lowercase with tolower(Id) yields poor Proget performance during resolution

### ISSUE THREAD

**Issue by Christoba** [fsprojects/Paket#2466] opened 2017-06-26 23:14 UTC
### Description

When resolving packages on a Proget Nuget feed with 150k package versions, the use of tolower(Id) in tryGetAllVersionsFromNugetODataWithFilter breaks performance optimizations around "Id eq 'package'" in Proget. This forces full enumeration of packages in the feed, which is orders of magnitude slower.

See related question posted to http://inedo.com/support/questions/6810

### Repro steps

Please provide the steps required to reproduce the problem

1. paket.dependencies references a package with source as a Proget feed with 100s of thousands of package version

2. Issue a get using Id='<package>', Version='<version>' and compare performance to a paket update on the same package.

### Expected behavior

Paket could provide syntax or a keyword override within paket.dependencies to disable case insensitivity handling like tolower()

**Comment by forki** [comment] 2017-06-27 06:17
Mhm I am not sure why we even do that. The first request for the package name should actually return the correct casing. But maybe that's not the case in one of the other feeds.

**Comment by Christoba** [comment] 2017-06-29 16:49
Is it possible that this could be changed? The behavior I've been seeing implies that the toLower is being used off the bat with nuget.

**Comment by forki** [comment] 2017-06-29 17:38
I assume it is possible. But I can't remember if why we added it. Please send a pull request and we see what it breaks.

**Comment by matthid** [comment] 2017-07-09 20:20
I don't think we don't think we propagate the casing of the first query, only the casing from the `paket.dependencies` file. But what we do is that we already try the faster url.

@Christoba can you check if casing correctly in `paket.dependencies` is a workaround?
Also a logfile would be helpful to see why paket has to fallback to the slower url.

I'm not sure where paket can find the proper casing, the only other call we do is `getversions`, so maybe we could get the info from there?

**Comment by forki** [comment] 2017-07-11 08:25
@Christoba can you please retry with latest?

**Comment by Christoba** [comment] 2017-07-11 19:42
We've seen a definite improvement (we're all using 5.6.6 right now) and resolution is down to seconds. 

Casing is something that I aligned early on (shortly after the ticket was entered) and it didn't seem to have a direct benefit, but this was a couple of weeks back. Thanks for the update!

**Comment by matthid** [comment] 2017-07-20 21:41
Ok I think we should probably add a warning when we use the fallback `ToLower` to tell the user he can improve performance by using proper casing in dependencies file.

**Comment by forki** [comment] 2017-07-21 05:58
Instead of a warning we could look casing up in the lockfile. So only very
first resolution would be slow. Or we could alternatively patch the deps
file.

Am 20.07.2017 23:41 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by matthid** [comment] 2017-07-21 06:34
Yes I agree, but warning is simpler to implement ;)
Patching lock or depsfile can introduce a bunch of new issues and needs a lot of testing. But yes it's the better option long term. 

Long-term we could fixup casing directly while resolving, so warnings will disappear with next install or update (at least that was the thinking when I suggested the warning)

**Comment by matthid** [comment] 2017-07-21 06:35
Or maybe we need to use a query/find API first to find the properly cased Id for each source, no idea.

**Comment by rasmus** [comment] 2017-08-09 05:33
We are also seeing this with our ProGet server. And along with https://github.com/fsprojects/Paket/issues/1777 it makes Paket almost impossible to use at our organisation.

**Comment by forki** [comment] 2017-08-09 05:47
@rasmus do you have correct casing in your dependencies file? I changed it to try the given casing first and only fallback to lower when nothing was found

**Comment by rasmus** [comment] 2017-08-09 05:54
@forki So as a workaround we'll have to specify correct casing for all of our indirect dependencies?

**Comment by forki** [comment] 2017-08-09 05:59
No indirect deps are probed with the casing from the nuspec definitions of the direct deps. So in most cases they should be correct.

**Comment by rasmus** [comment] 2017-08-09 06:14
@forki So the problem is that some package in our chain of dependencies have listed `owin` instead of `Owin`?

**Comment by forki** [comment] 2017-08-09 07:00
This or we have a bug somewhere. But paket should honor casing from deps file and nuspec files/ your proget api.

**Comment by rasmus** [comment] 2017-08-09 07:46
@forki I tried added the line `nuget Owin` our `paket.dependencies` and did a `.paket\paket.exe install -v`. If understand you correctly this should make Paket request `Owin` and not use the `tolower(Id)`. `Owin` has correct casing in the lock file as well for all references.

```
Paket version 5.84.0
found: C:\git\project\paket.dependencies
Parsing C:\git\project\paket.dependencies
Skipping resolver for group Main since it is already up-to-date
C:\git\project\paket.lock is already up-to-date
Installing into projects:
 - Creating model and downloading packages.

[CUT: too many packages]

Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (NormalizedVersion eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (NormalizedVersion eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:00Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
No results, trying again with Version instead of NormalizedVersion.
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:03Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
No results, trying again with NormalizedVersion as Version instead of Version.
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:08Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
GetPackageDetails failed: System.Exception: Couldn't get package details for package Owin 1.0.0 on http://nuget-server/nuget/Default.
   at Paket.Utils.rethrowf@31.Invoke(String msg)
   at Paket.NuGet.getPackageDetails@336-13.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (NormalizedVersion eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (NormalizedVersion eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:12Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
No results, trying again with Version instead of NormalizedVersion.
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:17Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
No results, trying again with NormalizedVersion as Version instead of Version.
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:21Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
Something went wrong while downloading Owin 1.0.0
Message: Could not download Owin 1.0.0.
  ==> Trying again
Downloading Owin 1.0.0
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (NormalizedVersion eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (NormalizedVersion eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:24Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
No results, trying again with Version instead of NormalizedVersion.
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:29Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
No results, trying again with NormalizedVersion as Version instead of Version.
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:32Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
GetPackageDetails failed: System.Exception: Couldn't get package details for package Owin 1.0.0 on http://nuget-server/nuget/Default.
   at Paket.Utils.rethrowf@31.Invoke(String msg)
   at Paket.NuGet.getPackageDetails@336-13.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (NormalizedVersion eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (NormalizedVersion eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:35Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
No results, trying again with Version instead of NormalizedVersion.
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:37Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
No results, trying again with NormalizedVersion as Version instead of Version.
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:42Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
Something went wrong while downloading Owin 1.0.0
Message: Could not download Owin 1.0.0.
  ==> Last trial
Downloading Owin 1.0.0
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (NormalizedVersion eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (NormalizedVersion eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:46Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
No results, trying again with Version instead of NormalizedVersion.
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:49Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
No results, trying again with NormalizedVersion as Version instead of Version.
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:53Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
GetPackageDetails failed: System.Exception: Couldn't get package details for package Owin 1.0.0 on http://nuget-server/nuget/Default.
   at Paket.Utils.rethrowf@31.Invoke(String msg)
   at Paket.NuGet.getPackageDetails@336-13.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (NormalizedVersion eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (NormalizedVersion eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:39:58Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
No results, trying again with Version instead of NormalizedVersion.
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:40:04Z</updated><link rel="self" title="Packages" href="Packages" /></feed>
No results, trying again with NormalizedVersion as Version instead of Version.
Starting request to 'http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0')'
Response from http://nuget-server/nuget/Default/Packages?$filter=(tolower(Id) eq 'owin') and (Version eq '1.0.0'):

<?xml version="1.0" encoding="utf-8"?><feed xml:base="http://nuget-server/nuget/Default/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom"><title type="text">Packages</title><id>http://nuget-server/nuget/Default/Packages()/</id><updated>2017-08-09T07:40:07Z</updated><link rel="self" title="Packages" href="Packages" /></feed>

-> Could not download Owin 1.0.0.
   StackTrace:
        at Paket.NuGet.download@682-47.Invoke(Exception _arg13)
        at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
        at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
        at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
        at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
        at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& )
        at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
        at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
        at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
        at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
        at Paket.InstallProcess.InstallIntoProjects[a](InstallerOptions options, Boolean forceTouch, DependenciesFile dependenciesFile, LockFile lockFile, FSharpList`1 projectsAndReferences, FSharpMap`2 updatedGroups)
        at Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions options)
        at <StartupCode$Paket-Core>.$PublicAPI.Install@186.Invoke(Unit unitVar0)
        at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
        at Paket.Program.main@723-10.Invoke(ParseResults`1 results)
        at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
        at Paket.Program.main$cont@710(ParseResults`1 results, Boolean silent, Boolean fromBootstrapper, Unit unitVar)
        at Paket.Program.main()
-> Couldn't get package details for package Owin 1.0.0 on http://nuget-server/nuget/Default.

Performance:
 - Disk IO: 447 milliseconds
 - Average Request Time: 3 seconds
 - Number of Requests: 18
 - Runtime: 1 minute, 13 seconds
```

**Comment by forki** [comment] 2017-08-09 07:50
Mmm. I think we need to invest this then. I'm currently very short on time since we got a baby. But maybe I find a minute.

**Comment by rasmus** [comment] 2017-08-09 07:54
@forki Congratulations 😄 I understand difficulties of finding time to open source when having kids

**Comment by forki** [comment] 2017-08-09 07:55
Investigate. Damn phone.

**Closed** 2017-08-09 09:42 UTC
Labels: needs-test-case

**Comment by forki** [comment] 2017-08-09 10:00
ok found 5min. can you please retry with latest? It should at least try with correct casing now and the number that is given in the lock file. So if you manually change that to 1.0 then it should at least now work with ProGet.

**Comment by rasmus** [comment] 2017-08-09 10:14
@forki tried it out, but the initial search URL looks like `http://dev-nuget/nuget/Default/Packages?$filter=(Id eq 'nunit') and (NormalizedVersion eq '3.7.1')`. Shouldn't that be `NUnit` (with a capital N and U)? It seems that it will always do a fallback as `nunit != NUnit`

**Comment by forki** [comment] 2017-08-09 10:16
Oups. That's what you get for doing this in 5min. Can you please take a
look at the very last commit. Then you can see the change and just remove
the to lower in that url call and send a PR? Then I will released asap.
Sorry.

Am 09.08.2017 12:14 nachm. schrieb "Rasmus Mikkelsen" <
notifications@github.com>:

**Comment by rasmus** [comment] 2017-08-09 10:17
@forki no problem, it happens 😉

**Comment by forki** [comment] 2017-08-09 12:56
Ok fixed it. Hopefully. Can you please retry

**Comment by rasmus** [comment] 2017-08-09 13:27
@forki Very nice, that fixed the performance problems. Thanks.

**Comment by matthid** [comment] 2017-08-17 16:10
Can you all please retry with  5.86.0-alpha002. Otherwise we might break you on next release.
