### ISSUE TITLE
.cs.pp source code transform files in content folder not been added to projects and transformed

### ISSUE THREAD

**Issue by madhon** [fsprojects/Paket#1139] opened 2015-10-15 14:46 UTC
Ive been using two packages both of which just have a source code file in their content folder which is transformed by putting the projects namespace into the file and adding it into the project.

the first package is liblog, it has the a file called liblog.cs.pp inside a subfolder of the content folder i.e. the following folder contains it

```
    packages\LibLog\content\App_Packages\LibLog.4.2  
```

this should be transformed and added into the project as `app_packages\liblog.4.2\liblog.cs`

the other package is `liteguard.source`
which has the different framework folders under content, each folder containins guard.cs.pp 
this file should also be added to the project with the namespace changed and added as guard.cs at the root of the project

i know you dont do the running of ps1 files as part of adding a package but is it a possiblity of processing .cs.pp files ?

paket.dependencies has

```
    source https://www.nuget.org/api/v2

    nuget LibLog framework: net40
    nuget LiteGuard.Source framework: net40
```

paket.references for the project has

```
    LibLog
    LiteGuard.Source
```

**Comment by forki** [comment] 2015-10-15 14:48
how is this done in nuget?

**Comment by madhon** [comment] 2015-10-15 14:49
its described in the "Source Code Transformations" section at
 https://docs.nuget.org/create/configuration-file-and-source-code-transformations

**Comment by wallymathieu** [comment] 2016-05-08 07:35
Look at:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectManagement/Projects/MSBuildNuGetProject.cs#L64

Then the files:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectManagement/FileModifiers/PreProcessor.cs
and
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/Preprocessor.cs

There needs to be some logic for "compatibleContentFilesGroup", i.e. depending on the targeted framework NuGet may apply different transforms...

**Comment by wallymathieu** [comment] 2016-05-08 07:36
Once either #1139 or #614 is in place, the other issue should be easier to implement.

**Comment by matkoch** [comment] 2016-08-02 11:36
Any estimation when this is going to be implemented? At least having source file transformations would be nice, and as far as I can see, this shouldn't be so difficult to implement.

As soon as you have a reference to the project file, it's basically just parsing `Project | PropertyGroup`... I would be totally okay, with just parsing plain properties (i.e. without condition; actually don't know how NuGet operates on this). So would be sufficient to use `$rootNamespace$` and `$assemblyName$` in `pp` files, which is probably the main use case.

**Comment by forki** [comment] 2016-08-02 11:40
It's marked up-for-grabs...

**Comment by matthid** [comment] 2017-06-15 21:52
Related https://github.com/fsprojects/Paket/pull/2231

**Comment by enricosada** [comment] 2018-01-24 14:08
Closing, dupe of https://github.com/fsprojects/Paket/issues/614

**Closed by enricosada** 2018-01-24 14:08 UTC
Labels: enhancement, nupkg spec, up-for-grabs
