### ISSUE TITLE
2.9.1 breaks Paket.Pack on filesystems with forward slash seperators

### ISSUE THREAD

**Issue by flowsprenger** [fsprojects/Paket#1119] opened 2015-10-08 07:54 UTC
```
tarting Target: Common.NuGet (==> Common.All)
mono  /Users/directory/XXX/.paket/paket.exe pack output bin  version  1.2.7-prerelease releaseNotes  "Prerelease with same content as 1.2.6. Needed for dependency management"
Paket version 2.9.1.0
Unable to parse /Users/directory/XXX/src/AAA/..\BBB\BBB.csproj:
      Could not find file "/Users/directory/XXX/src/AAA/..\BBB\BBB.csproj".
Paket failed with:
	Missing project reference in proj file /Users/directory/XXX/src/AAA/..\BBB\BBB.csproj
Running build failed.
```

maybe related to this change?
https://github.com/fsprojects/Paket/commit/619242496286184f7c9b6750324f6674eded3d5f#diff-e3a967918196c3a7e6442e48a6f3d244R93

**Comment by forki** [comment] 2015-10-08 07:54
Yep sorry. Will fix asap

**Comment by forki** [comment] 2015-10-08 08:07
please test 2.9.2 and let me know if it works. Thanks for reporting

**Comment by flowsprenger** [comment] 2015-10-08 08:28
still happens on 2.9.2 for me

**Comment by forki** [comment] 2015-10-08 08:31
Mhm. I guess there is no way for me to get your repo!?

Will take another look.

**Comment by flowsprenger** [comment] 2015-10-08 08:41
i will try and add you to a repo

**Comment by flowsprenger** [comment] 2015-10-08 08:46
added you now, i hope that its self contained enough for you to run it. you will probably need to run Paket.pack or drop in a stock build.fsx, otherwise i can try and email you a zipped up version

**Comment by forki** [comment] 2015-10-08 09:01
please try 2.9.3 - if it doesn't work I will boot up my mono vm

**Comment by flowsprenger** [comment] 2015-10-08 09:04
unfortunately still failing on 2.9.3

**Comment by forki** [comment] 2015-10-08 09:05
yep. mono vm it is. please downgrade paket for that time.

**Comment by forki** [comment] 2015-10-08 12:55
fixed in 2.9.4

**Closed by forki** 2015-10-08 12:55 UTC
Labels: bug

**Comment by flowsprenger** [comment] 2015-10-08 13:21
confirmed fixed, thanks for looking into it!

**Comment by artarf** [comment] 2015-10-18 09:33
This happens to me on (OS X mono 4.0.4) with version 2.9.4, 2.15.1 and master.

Changing Load() to use normalizePath in ProjectFile.fs fixes the problem.

**Comment by forki** [comment] 2015-10-18 09:38
Could you please send a pull request?

**Comment by artarf** [comment] 2015-10-19 10:19
Is the pull request ok?

**Comment by forki** [comment] 2015-10-19 10:24
mhm. I guess the PR would fix your current issue, but I assume we need to fix the root cause one level up. Can you try to see the stack trace  when that happens? I guess the caller has a bug.

**Comment by artarf** [comment] 2015-10-19 11:56
This is all get when I put `Console.WriteLine(exn.ToString())` in the `with | exn ->` block. I don't know how to get to the root cause.
```
[/work/projects/Bimodule/koe/coremisc/JsonUtils/Web] # mono ../../.paket/paket.exe pack output ../../nugets buildconfig Debug
Paket version 4.40.23020.0
System.IO.FileNotFoundException: Could not find file "/work/projects/Bimodule/koe/coremisc/JsonUtils/Web/..\Utils\Utils.csproj".
File name: '/work/projects/Bimodule/koe/coremisc/JsonUtils/Web/..\Utils\Utils.csproj'
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x00000] in <filename unknown>:0
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share) [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at System.IO.FileInfo.Open (FileMode mode, FileAccess access, FileShare share) [0x00000] in <filename unknown>:0
  at System.IO.FileInfo.OpenRead () [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.IO.FileInfo:OpenRead ()
  at Paket.ProjectFile.Load (System.String fileName) [0x00000] in <filename unknown>:0
Unable to parse /work/projects/Bimodule/koe/coremisc/JsonUtils/Web/..\Utils\Utils.csproj:
      Could not find file "/work/projects/Bimodule/koe/coremisc/JsonUtils/Web/..\Utils\Utils.csproj".
Paket failed with:
	Missing project reference in proj file ..\Utils\Utils.csproj
```

**Comment by forki** [comment] 2015-10-19 12:04
I guess I accept the pr, since it's definitely not a bad thing to have this
there

**Comment by artarf** [comment] 2015-10-19 12:17
Well, I managed to get better stack trace. Looks like the root cause is in Package.Metadata.findDependencies()
```
StackTrace: '   at System.Environment.get_StackTrace()
   at Paket.ProjectFile.Load(System.String fileName)
   at Paket.PackageMetaData+findDependencies@153-1.Invoke(Paket.ProjectReference p)
   at Microsoft.FSharp.Core.OptimizedClosures+Adapt@3259[[System.Tuple`2[[Microsoft.FSharp.Collections.FSharpList`1[[System.Tuple`2[[Paket.TemplateFile, paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null],[Paket.ProjectFile, paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null],[Microsoft.FSharp.Collections.FSharpList`1[[Paket.ProjectFile, paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null]], paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Paket.ProjectReference, paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null],[System.Tuple`2[[Microsoft.FSharp.Collections.FSharpList`1[[System.Tuple`2[[Paket.TemplateFile, paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null],[Paket.ProjectFile, paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null],[Microsoft.FSharp.Collections.FSharpList`1[[Paket.ProjectFile, paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null]], paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Tuple`2 , Paket.ProjectReference )
   at Microsoft.FSharp.Collections.SeqModule.Fold(Microsoft.FSharp.Core.FSharpFunc`2 folder, System.Tuple`2 state, IEnumerable`1 source)
   at Paket.PackageMetaData.findDependencies(Paket.DependenciesFile dependencies, System.String config, Paket.TemplateFile template, Paket.ProjectFile project, Boolean lockDependencies, Microsoft.FSharp.Collections.FSharpMap`2 map)
   at Paket.PackageProcess+allTemplates@99-1.Invoke(System.String _arg2, System.Tuple`2 tupledArg)
   at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt(Microsoft.FSharp.Core.FSharpFunc`3 f, Microsoft.FSharp.Collections.MapTree`2 m)
   at Microsoft.FSharp.Collections.FSharpMap`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Tuple`2[[Paket.TemplateFile, paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null],[Paket.ProjectFile, paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Map(Microsoft.FSharp.Core.FSharpFunc`2 f)
   at Microsoft.FSharp.Collections.MapModule.Map(Microsoft.FSharp.Core.FSharpFunc`2 mapping, Microsoft.FSharp.Collections.FSharpMap`2 table)
   at Paket.PackageProcess.Pack(System.String workingDir, Paket.DependenciesFile dependencies, System.String packageOutputPath, Microsoft.FSharp.Core.FSharpOption`1 buildConfig, Microsoft.FSharp.Core.FSharpOption`1 version, Microsoft.FSharp.Core.FSharpOption`1 releaseNotes, Microsoft.FSharp.Core.FSharpOption`1 templateFile, Boolean lockDependencies)
   at Paket.Dependencies.Pack(System.String outputPath, Microsoft.FSharp.Core.FSharpOption`1 buildConfig, Microsoft.FSharp.Core.FSharpOption`1 version, Microsoft.FSharp.Core.FSharpOption`1 releaseNotes, Microsoft.FSharp.Core.FSharpOption`1 templateFile, Microsoft.FSharp.Core.FSharpOption`1 workingDir, Microsoft.FSharp.Core.FSharpOption`1 lockDependencies)
   at Paket.Program.pack(Nessos.Argu.ParseResults`1 results)
   at Paket.Program+handler@343-20.Invoke(Nessos.Argu.ParseResults`1 results)
   at Paket.Program.processWithValidation(Microsoft.FSharp.Core.FSharpFunc`2 validateF, Microsoft.FSharp.Core.FSharpFunc`2 commandF, Paket.Command command, System.String[] args)
   at Paket.Program+processCommand@61-1[[Paket.Commands+PackArgs, paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null]].Invoke(Paket.Command command, System.String[] args)
   at Microsoft.FSharp.Core.FSharpFunc`2[[Paket.Commands+Command, paket, Version=2.15.1.0, Culture=neutral, PublicKeyToken=null],[System.String[], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeFast(Microsoft.FSharp.Core.FSharpFunc`2 func, Paket.Command arg1, System.String[] arg2)
   at Paket.Program.main$cont@325(Paket.Command command, Microsoft.FSharp.Core.Unit unitVar)
   at Paket.Program.main()
   at <StartupCode$paket>.$Paket.Program.main@()'
```
