### ISSUE TITLE
exactly-this-operator does not seem to work

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2777] opened 2017-09-18 10:40 UTC
### Description

FsPickler 4.0 was just [just released](https://www.nuget.org/packages/FsPickler/4.0.0).

Unfortunately, a few of my other dependencies have a hard check ``< 4.0``:

![image](https://user-images.githubusercontent.com/4236651/30538405-256bf166-9c6e-11e7-9978-3910fe4e7647.png)

![image](https://user-images.githubusercontent.com/4236651/30538418-32329a8a-9c6e-11e7-861a-871b6fac1ef2.png)

My current strategy (lets see if it works) is to just pin everything to their latest versions with ``==``. Unfortunately, this means that ``paket update`` becomes kind of useless.

Instead I would want to be able to specify

```
nuget FsPickler == latest
MBrace.Thespian == latest
Vagabond == latest
...
```

then it should resolve the latest version of each of these packages, ignoring conflicting version ranges.
Transitives should still be resolved normally, I may need to pin some more packages.

**Comment by forki** [comment] 2017-09-18 10:41
O_o

Am 18.09.2017 12:40 schrieb "Lukas Rieger" <notifications@github.com>:

**Comment by 0x53A** [comment] 2017-09-18 10:43
(The alternative would be ~annoy~ kindly ask Eirik to update all dependencies to the latest FsPickler)

**Comment by matthid** [comment] 2017-09-18 11:08
don't try to fool paket ;)

**Comment by 0x53A** [comment] 2017-09-18 11:12
yeah, the ``== latest`` doesn't seem like that great an idea anymore, but I would like to keep this open for the (potential) exactly-this-operator issue, I would expect the deps file above to resolve.

**Comment by sjancke** [comment] 2017-10-26 18:57
@0x53A seeing this also in newer versions, worked the other day with version 5.100.3

**Comment by sjancke** [comment] 2017-10-26 18:59
@matthid what do you mean by "fool paket" here?

**Comment by sjancke** [comment] 2017-10-26 21:36
Investigating this issues further, I have the impression, the problem is related to the number of packagings that require a "conflicting" version.

Stripping down @0x53A sample:
source https://api.nuget.org/v3/index.json

framework: net461

nuget FsPickler == 4.0
nuget FsPickler.Json == 4.0

nuget MBrace.Thespian 1.4.0
#nuget MBrace.Runtime 1.4.0

Works:
`Paket version 5.119.8
Resolving packages for group Main:
 - FsPickler 4.0.0
 - FsPickler.Json 4.0.0
 - MBrace.Thespian is pinned to 1.4.0
 - Argu 3.7.0
 - Vagabond 0.14.0
 - Thespian 0.1.16
 - MBrace.Core 1.4.0
 - MBrace.Runtime 1.4.0
 - Newtonsoft.Json 10.0.3
 - FSharp.Core 4.2.3
 - FSharp.Core 4.2.2
 - Thespian 0.1.15
 - FSharp.Core 4.1.18
 - FSharp.Core 4.1.17
 - Thespian 0.1.14
 - Thespian 0.1.13
 - Thespian 0.1.12-alpha
 - Thespian 0.1.11-alpha
 - FSharp.Core 4.2.1
 - FSharp.Core 4.1.12
     FSharp.Core 4.1.12 was unlisted
 - FSharp.Core 4.1.2
     FSharp.Core 4.1.2 was unlisted
 - FSharp.Core 4.1.0.2
     FSharp.Core 4.1.0.2 was unlisted
 - FSharp.Core 4.1.0
     FSharp.Core 4.1.0 was unlisted
 - FSharp.Core 4.0.1.5
     FSharp.Core 4.0.1.5 was unlisted
 - FSharp.Core 4.0.0.1
 - FSharp.Core 4.0.0
     FSharp.Core 4.0.0 was unlisted
 - FSharp.Core 3.1.2.5
 - FSharp.Core 3.1.2.1
     FSharp.Core 3.1.2.1 was unlisted
 - FSharp.Core 3.1.2
 - Newtonsoft.Json 10.0.2
 - Newtonsoft.Json 10.0.1
 - Newtonsoft.Json 9.0.1
 - Newtonsoft.Json 8.0.3
 - Newtonsoft.Json 8.0.2
 - Newtonsoft.Json 8.0.1
 - Newtonsoft.Json 7.0.1
 - Newtonsoft.Json 6.0.8
 - Newtonsoft.Json 6.0.7
 - Newtonsoft.Json 6.0.6
 - Newtonsoft.Json 6.0.5
 - Argu 3.6.1
 - Mono.Cecil 0.9.6.4
Locked version resolution written to C:\dev\stuff\paket-issues\paket.lock`

Adding another dependency that results in the "same conflict" breaks the exactly-this-operator:
`source https://api.nuget.org/v3/index.json

framework: net461

nuget FsPickler == 4.0
nuget FsPickler.Json == 4.0

nuget MBrace.Thespian 1.4.0
nuget MBrace.Runtime 1.4.0`

`Paket version 5.119.8
Resolving packages for group Main:
 - FsPickler 4.0.0
 - FsPickler.Json 4.0.0
 - MBrace.Runtime is pinned to 1.4.0
 - MBrace.Thespian is pinned to 1.4.0
Performance:
 - Resolver: 2 seconds (1 runs)
    - Runtime: 413 milliseconds
    - Blocked (retrieving package details): 156 milliseconds (4 times)
    - Blocked (retrieving package versions): 1 second (2 times)
    - Not Blocked (retrieving package versions): 2 times
 - Average Request Time: 361 milliseconds
 - Number of Requests: 14
 - Runtime: 4 seconds
Paket failed with
-> There was a version conflict during package resolution.
     Resolved packages:
      - FsPickler 4.0.0
      - FsPickler.Json 4.0.0
      - MBrace.Runtime 1.4.0
      - MBrace.Thespian 1.4.0
     Conflict detected:
      - Dependencies file requested package FsPickler: == 4.0
      - MBrace.Runtime 1.4.0 requested package FsPickler: >= 3.2 < 4.0
      - MBrace.Thespian 1.4.0 requested package FsPickler: >= 3.2 < 4.0
      - FsPickler.Json 4.0.0 requested package FsPickler: 4.0

     Please try to relax some conditions or resolve the conflict manually (see http://fsprojects.github.io/Paket/nuget-d
ependencies.html#Use-exactly-this-version-constraint).`

**Comment by forki** [comment] 2017-10-27 05:25
thanks for the repos.
A fix is in https://github.com/fsprojects/Paket/pull/2867

**Closed** 2017-10-27 06:28 UTC

**Comment by sjancke** [comment] 2017-10-27 07:28
thanks.
