### ISSUE TITLE
Question/Clarification regarding Nuget not having transitive dependencies in FAQ

### ISSUE THREAD

**Issue by hsorbo** [fsprojects/Paket#2617] opened 2017-08-16 00:03 UTC
The FAQ states "NuGet does not separate out the concept of transitive dependencies". It probably is the case using `packages.config`, but by using `PackageReference`, at least by their definition, Nuget have that capability. Is the FAQ outdated? https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution

**Comment by forki** [comment] 2017-08-16 01:14
Yes that part of the FAQ is outdated and only references the old
packages.config. It definitely needs clarification and we would like to
accept pull requests to that part.

The new packages references model in MSBuild definetly allows to draw in
transitives. The difference is that MSBuild has no lock file and therefore
transitive dependencies float. This can lead to the situation that CI and
local PC use different resolutions.

Am 16.08.2017 2:03 vorm. schrieb "Håvard Sørbø" <notifications@github.com>:

**Comment by enricosada** [comment] 2018-01-24 16:21
Closing. dupe of #2736

**Closed by enricosada** 2018-01-24 16:21 UTC
Labels: documentation, enhancement, up-for-grabs
