### ISSUE TITLE
Paket could not resolve package version even though it exists in available versions

### ISSUE THREAD

**Issue by russcam** [fsprojects/Paket#2326] opened 2017-05-10 03:06 UTC
### Description

Within [our windows installers](https://github.com/elastic/windows-installers), we use [MahApps.Metro.Resources package](https://www.nuget.org/packages/MahApps.Metro.Resources/)

In `paket.dependencies`, we have 

```
nuget MahApps.Metro.Resources 0.4.0.0 framework: >= net45
```
but when updating another package (in this case, `Fody`), paket says that it cannot resolve this version of the package, even though it is listed in the available versions.

```
.\.paket\paket.exe update nuget Fody version 1.29.4
Paket version 5.0.0-alpha020
Updating Fody to version 1.29.4 in C:\Users\russ\source\windows-installers\paket.dependencies group Main
Resolving packages for group Main:
 - Fody is pinned to 1.29.4
 - reactiveui is pinned to 6.3.1
 - reactiveui-core is pinned to 6.3.1
 - reactiveui-events is pinned to 6.3.1
 - FluentValidation is pinned to 5.5.0.0
 - YamlDotNet is pinned to 3.8.0
 - Topshelf is pinned to 3.1.4
 - ILMerge is pinned to 2.14.1208
 - Rx-Core is pinned to 2.2.5
 - Rx-Interfaces is pinned to 2.2.5
 - Rx-Linq is pinned to 2.2.5
 - Rx-Main is pinned to 2.2.5
 - Rx-PlatformServices is pinned to 2.2.5
 - Rx-XAML is pinned to 2.2.5
 - Splat is pinned to 1.6.0
 - Costura.Fody is pinned to 1.3.3.0
 - WindowsAPICodePack-Core is pinned to 1.1.1
 - WindowsAPICodePack-Shell is pinned to 1.1.1
 - HtmlTextBlock is pinned to 1.0.1
 - MahApps.Metro is pinned to 1.0.1-ALPHA027
 - MahApps.Metro.Resources is pinned to 0.4.0.0
Paket failed with:
        There was a version conflict during package resolution.
  Resolved packages:
   - Costura.Fody 1.3.3.0
   - FluentValidation 5.5.0.0
   - Fody 1.29.4
   - HtmlTextBlock 1.0.1
   - ilmerge 2.14.1208
   - MahApps.Metro 1.0.1-ALPHA027
   - reactiveui 6.3.1
   - reactiveui-core 6.3.1
   - reactiveui-events 6.3.1
   - Rx-Core 2.2.5
   - Rx-Interfaces 2.2.5
   - Rx-Linq 2.2.5
   - Rx-Main 2.2.5
   - Rx-PlatformServices 2.2.5
   - Rx-Xaml 2.2.5
   - Splat 1.6.0
   - Topshelf 3.1.4
   - WindowsAPICodePack-Core 1.1.1
   - WindowsAPICodePack-Shell 1.1.1
   - YamlDotNet 3.8.0
  Could not resolve package MahApps.Metro.Resources 0.4:
   - Available versions:
     - (0.4, [https://api.nuget.org/v3/index.json])
     - (0.6.1, [https://api.nuget.org/v3/index.json])
     - (0.6.0, [https://api.nuget.org/v3/index.json])
     - (0.5.0, [https://api.nuget.org/v3/index.json])
     - (0.4.0, [https://api.nuget.org/v3/index.json])
     - (0.3.0, [https://api.nuget.org/v3/index.json])
     - (0.2.1, [https://api.nuget.org/v3/index.json])
     - (0.2.0, [https://api.nuget.org/v3/index.json])
     - (0.1.0.1, [https://api.nuget.org/v3/index.json])
     - (0.1.0, [https://api.nuget.org/v3/index.json])

  Please try to relax some conditions or resolve the conflict manually (see http://fsprojects.github.io/Paket/nuget-dependencies.html#Use-exactly-this-version-constraint).
```

[This is fixed by pinning to 0.4.0.0](https://github.com/elastic/windows-installers/commit/5c885ff7a3e4e1cdf309adc76cc79c0583ef5454#diff-b27553841b4413a24ed1b9aff865105bR10)

### Repro steps

Please provide the steps required to reproduce the problem

1. clone https://github.com/elastic/windows-installers

2. checkout commit `0dafe2cea85489a51da534f2bc129f1119349961`

3. run `build.bat` in root to pull all dependencies down and build the project.

4. update `Fody` in paket.dependencies to

    ```
    nuget Fody 1.29.4 content: none
    ```
5. run `.\.paket\paket.exe update nuget Fody version 1.29.4`

### Expected behavior

Fody package is updated.

### Actual behavior

Error shown above

### Known workarounds

Pinning MahApps.Metro.Resources to exactly 0.4 solves the issue.

**Comment by cloudRoutine** [comment] 2017-05-10 17:26
Simpler repro for anyone else working on this
[paket-2326.zip](https://github.com/fsprojects/Paket/files/990694/paket-2326.zip)

**Comment by matthid** [comment] 2017-05-10 22:25
```
source https://api.nuget.org/v3/index.json

nuget MahApps.Metro 1.0.1-ALPHA027 framework: >= net45
nuget MahApps.Metro.Resources 0.4 framework: >= net45
```

is already failing for some reason

**Comment by matthid** [comment] 2017-05-10 22:28
I would guess it's related to https://github.com/fsprojects/Paket/pull/2307 and the alpha version...

**Comment by russcam** [comment] 2017-05-10 22:36
Sounds like it, I'll test with a non-alpha version

**Comment by matthid** [comment] 2017-05-10 22:42
It's really a question if this should work at all. Paket "sees" the `>=1.0.1` dependency in `MahApps.Metro.Resources` as explicit non-alpha dependency therefore it figures that the resolution is invalid...

We need to add a special case to allow alphas where explicitely specified in `paket.dependencies` I guess.

**Comment by matthid** [comment] 2017-05-10 22:51
And its really scary that the integration tests did not catch this change (if it did work before).
I thought I could do a quick fix, but the change will probably be more invasive than I initially thought so this will have to wait some time (if noone else is doing it in the mean time)

**Comment by matthid** [comment] 2017-05-10 23:06
@russcam thanks for using paket alphas btw and reporting bugs 👍

**Comment by forki** [comment] 2017-05-11 07:10
@russcam I can't repro

**Comment by forki** [comment] 2017-05-11 07:12
@cloudRoutine I can't repro with your sample

**Comment by forki** [comment] 2017-05-11 08:33
argh scratch that. I was on wrong branch

**Comment by forki** [comment] 2017-05-11 08:52
now I see StackOverflow on @cloudRoutine's sample:

**Comment by forki** [comment] 2017-05-11 08:54
cray: this only happens inside VS.

**Comment by forki** [comment] 2017-05-11 10:46
ok this is the core:

    source https://api.nuget.org/v3/index.json
    
    nuget MahApps.Metro 1.0.1-ALPHA027 framework: >= net45
    nuget MahApps.Metro.Resources 0.4 framework: >= net45

this can't resolve since MahApps.Metro.Resources 0.4 does not allow alpha of MahApps.Metro.

If you want that then do:

    source https://api.nuget.org/v3/index.json
    
    nuget MahApps.Metro == 1.0.1-ALPHA027 framework: >= net45
    nuget MahApps.Metro.Resources 0.4 framework: >= net45

The real issue here is bad error reporting. When MahApps.Metro.Resources get's resolved the canTakePackage value evaluates to false since deps are incompatible. But we don't report that as conflict. Instead we just report version not found.

**Comment by forki** [comment] 2017-05-11 11:09
I fixed it in https://github.com/fsprojects/Paket/pull/2328 to report this properly:

![image](https://cloud.githubusercontent.com/assets/57396/25946248/8e65ff70-364a-11e7-91e6-be8a97bf02ff.png)

but there are couple of errors open. @cloudRoutine could you please take a look?

**Comment by matthid** [comment] 2017-05-11 16:40
@forki Yes that was my analysis as well. However I was unsure if we should allow alphas in such particular instances (as the user explicitely allowed an alpha version).

In particular there is not even a workaround to tell paket to use alphas. I think

```
source https://api.nuget.org/v3/index.json

nuget MahApps.Metro 1.0.1-ALPHA027 prerelease framework: >= net45
nuget MahApps.Metro.Resources 0.4 framework: >= net45
```

should work. But it isn't. This means we don't use alpha versions in all situations where we should.

**Comment by forki** [comment] 2017-05-12 05:56
No I'm pretty sure the resolution is correct in rejecting this. It's just
the wrong error message

Am 11.05.2017 6:40 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by matthid** [comment] 2017-07-09 12:08
I'm closing this as by design.
Note that my last example is now working:

```
source https://api.nuget.org/v3/index.json

nuget MahApps.Metro 1.0.1-ALPHA027 prerelease framework: >= net45
nuget MahApps.Metro.Resources 0.4 framework: >= net45
```

In general it should be working as soon as you specify all packages which should be allowed to be uses as `prerelease` in the dependency file. Feel free to open another issue if this is not the case.

**Closed by matthid** 2017-07-09 12:08 UTC
