### ISSUE TITLE
Paket: 5.92.0-alpha001 fail to generate correct project.assets.json

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/Paket#2680] opened 2017-08-28 13:27 UTC
I just updating one of my project to use NETStandard 2.0.

When using paket `5.92.0-alpha001`  I got this [project.assets.json](https://gist.github.com/MangelMaxime/699c387bb3e8a672a205daf9df77f373) which is wrong. It does not contains my dependencies.

If I use paket `5.91.0`, then I got [this file](https://gist.github.com/MangelMaxime/45a06e4afb445f61d9b1d59ca6cac773).

As you can see the first file is missing a lot of deps like `Fable.Core`.

Here is my paket.dependencies:

```
framework: netstandard2.0

source https://www.nuget.org/api/v2

nuget Fable.Core prerelease
nuget Fable.Elmish.React
nuget Fable.Elmish.Browser
nuget Fable.Elmish.Debugger
nuget Fable.PowerPack
nuget Fable.React prerelease

clitool dotnet-fable prerelease

group Build
framework: net46

    source https://nuget.org/api/v2
    nuget FSharp.Core  redirects:force, content:none
    nuget FAKE

    github fsharp/FAKE modules/Octokit/Octokit.fsx
```

Paket.references:
```
Fable.Core
Fable.React
```

Please tell me if you need more infos.

**Comment by matthid** [comment] 2017-08-28 13:31
Yes 
 - what is your project layout, ie relative paths of project file, paket.references file, paket.exe, Paket.Restore.Targets and lockfile. Please make sure everything is correct regarding to casing if you are not on windows
- what are the generated *.references files in the `obj/` directory.
- dependencies-/lock- file
- Are there warnings errors emitted by paket in your build process?

**Comment by MangelMaxime** [comment] 2017-08-28 13:50
Hello @matthid you can find the project [here](https://github.com/MangelMaxime/Fable.Elmish.Bulma/tree/8bfb60d01955c2ba1e872a26720f252a2e1891d0).

To summarize I go the following layout:

```
/.paket/paket.exe
/paket.lock
/paket.dependencies
/src/Fulma/paket.reference
/src/Fulma/Fulma.fsproj
```

Here is my [Fulma.fsproj.netstandard2.0.references](https://gist.github.com/MangelMaxime/2886e80db44ecf3572433f3123498b21) file.

And here is my full obj folder: [obj.zip](https://github.com/fsprojects/Paket/files/1256937/obj.zip)


There is no warning output during my build process by paket. [output.txt](https://gist.github.com/MangelMaxime/39c47c8882e61c9349f2a1aec0e5ceab)

**Comment by matthid** [comment] 2017-08-28 13:58
Ah good, will try to reproduce later

**Comment by matthid** [comment] 2017-08-28 16:02
Ok can you tell me for idiots what I need to do :)

Assume I don't have any idea of fable and just cloned your repository, how do I reproduce the bug?

**Comment by matthid** [comment] 2017-08-28 16:12
Problem is all your files look correct, but from your error description it looks like they are never actually read in the build process. Something is wrong there.

**Comment by matthid** [comment] 2017-08-28 16:26
OK I noticed something: Your `Paket.Restore.targets` is not the latest one and `paket install` didn't update it either. Now I have two questions:
 - @forki what else do I need to do apparently something else is required to embed/update the targets file?
 - Apparently I broke compat with older Targets files, thanks for the report, because I expected this to work...

**Comment by matthid** [comment] 2017-08-28 16:35
Ah OK its because I removed the old file when only netstandard20 is there (We discussed that it is safe to assume it only is required for fable compat when using netstandard16). Maybe we need to revisit that for at least a couple of versions... (until we can assume people have updated their targets files?) 

/cc @forki because of compat concerns

**Comment by forki** [comment] 2017-08-28 16:41
I always tried to keep paket backwards compatibility with the old targets
files.
It's not easy,...

Am 28.08.2017 18:35 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by matthid** [comment] 2017-08-28 17:52
Will be fixed with https://github.com/fsprojects/Paket/pull/2684, thanks for reporting and testing the alpha!

**Closed by matthid** 2017-08-28 17:52 UTC

**Comment by MangelMaxime** [comment] 2017-08-28 18:04
Thanks for the quick fix :)

**Comment by MangelMaxime** [comment] 2017-08-29 11:47
I tested with `5.92.0-beta001` and it's working. 👏
