### ISSUE TITLE
Paket gets stuck while resolving packages from Sonatype Nexus 3

### ISSUE THREAD

**Issue by nikoudel** [fsprojects/Paket#2435] opened 2017-06-17 17:49 UTC
### Description

Paket.exe gets stuck under certain conditions. It seems to getting into an infinite loop consuming more and more memory:

![image](https://user-images.githubusercontent.com/1636683/27255050-72db5afe-539e-11e7-8929-c88ffb1b9066.png)

### Repro steps

I have set up own repository just to make sure I can reproduce the problem I'm having in a production environment. To reproduce it:

1. Download version 5.0.0 of paket.exe into e.g. c:\temp\nexus-bug
2. Create paket.dependencies with the following contents

```
source http://91.121.154.55:8081/repository/nuget-hosted/

nuget Small.ExeFile1
nuget Small.ExeFile2
nuget Small.ExeFile3
nuget Small.ExeFile4
nuget Small.ExeFile5
nuget Small.ExeFile6
nuget Small.ExeFile7
nuget Small.ExeFile8
#nuget Small.ExeFile9
#nuget Small.ExeFile10
#nuget Small.ExeFile11
#nuget Small.ExeFile12

nuget Big.ExeFile1
#nuget Big.ExeFile2
#nuget Big.ExeFile3 
```
3. Run paket install like this:

![image](https://user-images.githubusercontent.com/1636683/27255006-4e594700-539d-11e7-98c5-777a1c9cb171.png)

### Expected behavior

Paket should resolve and install all the packages.

### Actual behavior

Package resolution gets stuck at Small.ExeFile7 and never finishes.

It looks like when there is at least one big package and a group of other (small) packages with lots of versions of each package, then paket only handles eight (8) items at most. If there is more than eight, it gets stuck.

### Known workarounds

None.

**Comment by matthid** [comment] 2017-06-17 17:54
Is this a regression?

**Comment by nikoudel** [comment] 2017-06-17 18:06
@matthid I'm not sure. Just started using Paket and got into this issue pretty soon. I had less than eight packages before and less versions of each package, so it worked fine.

**Comment by matthid** [comment] 2017-06-17 18:13
@nikoudel Does `Small.ExeFile8` really exist on the server? It looks like the request to it is never returning (yes it's still a bug in paket that it is blocking on that). Or maybe it's something else, still investigating

**Comment by nikoudel** [comment] 2017-06-17 18:16
Yes, all listed files exist on the server.

**Comment by matthid** [comment] 2017-06-17 18:50
@nikoudel Ok I got the deadlock, now we need to figure out why the server stops responding and on which url... Is there some rate limiting or something similar on this server?

**Comment by matthid** [comment] 2017-06-17 18:52
This also is no regression, it seems 4.8.8 is hanging on this server as well...

**Comment by matthid** [comment] 2017-06-17 18:54
The server either doesn't like multiple parallel requests or several requests in a short period of time....
Not sure what paket could do besides telling you that the server should be fixed (we could add an option to only do a single request at a time and do rate limiting but it will make things quite slow)

**Comment by nikoudel** [comment] 2017-06-17 19:01
The server might be doing some kind of rate limiting. I'm using Sonatype Nexus 3 open-source version so it might be capped intentionally. I'll try to figure out if there was some configuration to tweak somewhere and I'll post here if I find it. Thank you for the investigation!

**Comment by matthid** [comment] 2017-06-17 19:07
Yes please post, we might want to investigate if we can make it run for defaults ...

**Comment by nikoudel** [comment] 2017-06-17 19:31
@matthid There is something strange in the request.log file on the server. The skip counter is just growing but nothing else in the request changes. Looks like paket is not satisfied with the response it's getting and just issues a new request with a bigger skip value...

```
<ip address> - - [17/Jun/2017:19:24:45 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111120&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 44 "Paket"
<ip address> - - [17/Jun/2017:19:24:45 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111160&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 44 "Paket"
<ip address> - - [17/Jun/2017:19:24:45 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111200&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 47 "Paket"
<ip address> - - [17/Jun/2017:19:24:45 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111240&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 43 "Paket"
<ip address> - - [17/Jun/2017:19:24:45 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111280&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 45 "Paket"
<ip address> - - [17/Jun/2017:19:24:46 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111320&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 45 "Paket"
<ip address> - - [17/Jun/2017:19:24:46 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111360&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 45 "Paket"
<ip address> - - [17/Jun/2017:19:24:46 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111400&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 53 "Paket"
<ip address> - - [17/Jun/2017:19:24:46 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111440&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 45 "Paket"
<ip address> - - [17/Jun/2017:19:24:46 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111480&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 45 "Paket"
<ip address> - - [17/Jun/2017:19:24:46 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111520&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 45 "Paket"
<ip address> - - [17/Jun/2017:19:24:46 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111560&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 44 "Paket"
<ip address> - - [17/Jun/2017:19:24:46 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111600&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 45 "Paket"
<ip address> - - [17/Jun/2017:19:24:47 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111640&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 44 "Paket"
<ip address> - - [17/Jun/2017:19:24:47 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111680&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 46 "Paket"
<ip address> - - [17/Jun/2017:19:24:47 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111720&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 64 "Paket"
<ip address> - - [17/Jun/2017:19:24:47 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111760&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 45 "Paket"
<ip address> - - [17/Jun/2017:19:24:47 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111800&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 44 "Paket"
<ip address> - - [17/Jun/2017:19:24:47 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111840&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 46 "Paket"
<ip address> - - [17/Jun/2017:19:24:47 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111880&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 49 "Paket"
<ip address> - - [17/Jun/2017:19:24:48 +0000] "GET /repository/nuget-hosted/Packages()?$skip=111920&$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0 HTTP/1.1" 200 93557 45 "Paket"
```

**Comment by matthid** [comment] 2017-06-17 20:02
Interesting, let me take a look

**Comment by matthid** [comment] 2017-06-17 20:28
Yes I'm seeing it now:

`http://91.121.154.55:8081/repository/nuget-hosted/Packages()?$filter=tolower%28Id%29+eq+%27small.exefile8%27&amp;semVerLevel=2.0.0&amp`

Yields all versions and
```
<link rel="next" href="http://91.121.154.55:8081/repository/nuget-hosted/Packages()?$skip=40&amp;$filter=tolower%28Id%29+eq+%27small.exefile8%27&amp;amp;semVerLevel=2.0.0&amp;amp="/>
```

But if you request that uri it will return the exact same versions, but:
```
<link rel="next" href="http://91.121.154.55:8081/repository/nuget-hosted/Packages()?$skip=80&amp;amp;amp;semVerLevel=2.0.0&amp;amp;$filter=tolower%28Id%29+eq+%27small.exefile8%27&amp;amp;amp="/>
```

As you can see the server is returning always the same result but increments the skip parameter by `40`. Looks pretty broken to me...

**Comment by matthid** [comment] 2017-06-17 20:32
could be something with escaping as well no idea

**Comment by matthid** [comment] 2017-06-17 20:55
Ok #2436 is working on your feed, but the fix feels wrong...
Thanks for your feedback.

Maybe I can ping some people from sonatype /cc @jdillon @DarthHater @mcculls (sorry if I didn't hit the correct guys :) )

**Comment by matthid** [comment] 2017-06-17 21:16
```
$ ../paket/bin/paket.exe install
Paket version 5.0.0
Resolving packages for group Main:
 - Big.ExeFile1 1.0.0
At least one 'next' links (index 0) returned a empty result (noticed on 'http://91.121.154.55:8081/repository/nuget-hosted/Packages?semVerLevel=2.0.0&$filter=tolower(Id) eq 'small.exefile7''): ['http://91.121.154.55:8081/repository/nuget-hosted/Packages()?$filter=tolower%28Id%29+eq+%27small.exefile7%27&semVerLevel=2.0.0&$skip=40']
At least one 'next' links (index 0) returned a empty result (noticed on 'http://91.121.154.55:8081/repository/nuget-hosted/Packages?semVerLevel=2.0.0&$filter=tolower(Id) eq 'small.exefile4''): ['http://91.121.154.55:8081/repository/nuget-hosted/Packages()?$filter=tolower%28Id%29+eq+%27small.exefile4%27&semVerLevel=2.0.0&$skip=40']
At least one 'next' links (index 0) returned a empty result (noticed on 'http://91.121.154.55:8081/repository/nuget-hosted/Packages?semVerLevel=2.0.0&$filter=tolower(Id) eq 'small.exefile6''): ['http://91.121.154.55:8081/repository/nuget-hosted/Packages()?$filter=tolower%28Id%29+eq+%27small.exefile6%27&semVerLevel=2.0.0&$skip=40']
At least one 'next' links (index 0) returned a empty result (noticed on 'http://91.121.154.55:8081/repository/nuget-hosted/Packages?semVerLevel=2.0.0&$filter=tolower(Id) eq 'small.exefile3''): ['http://91.121.154.55:8081/repository/nuget-hosted/Packages()?$filter=tolower%28Id%29+eq+%27small.exefile3%27&semVerLevel=2.0.0&$skip=40']
At least one 'next' links (index 0) returned a empty result (noticed on 'http://91.121.154.55:8081/repository/nuget-hosted/Packages?semVerLevel=2.0.0&$filter=tolower(Id) eq 'small.exefile2''): ['http://91.121.154.55:8081/repository/nuget-hosted/Packages()?$filter=tolower%28Id%29+eq+%27small.exefile2%27&semVerLevel=2.0.0&$skip=40']
At least one 'next' links (index 0) returned a empty result (noticed on 'http://91.121.154.55:8081/repository/nuget-hosted/Packages?semVerLevel=2.0.0&$filter=tolower(Id) eq 'small.exefile1''): ['http://91.121.154.55:8081/repository/nuget-hosted/Packages()?$filter=tolower%28Id%29+eq+%27small.exefile1%27&semVerLevel=2.0.0&$skip=40']
At least one 'next' links (index 0) returned a empty result (noticed on 'http://91.121.154.55:8081/repository/nuget-hosted/Packages?semVerLevel=2.0.0&$filter=tolower(Id) eq 'small.exefile5''): ['http://91.121.154.55:8081/repository/nuget-hosted/Packages()?$filter=tolower%28Id%29+eq+%27small.exefile5%27&semVerLevel=2.0.0&$skip=40']
 - Small.ExeFile1 1.0.50
 - Small.ExeFile2 1.0.50
 - Small.ExeFile3 1.0.50
 - Small.ExeFile4 1.0.50
 - Small.ExeFile5 1.0.50
 - Small.ExeFile6 1.0.50
 - Small.ExeFile7 1.0.50
At least one 'next' links (index 0) returned a empty result (noticed on 'http://91.121.154.55:8081/repository/nuget-hosted/Packages?semVerLevel=2.0.0&$filter=tolower(Id) eq 'small.exefile8''): ['http://91.121.154.55:8081/repository/nuget-hosted/Packages()?$filter=tolower%28Id%29+eq+%27small.exefile8%27&semVerLevel=2.0.0&$skip=40']
 - Small.ExeFile8 1.0.50
Locked version resolution written to C:\PROJ\paket.test\paket.lock
Performance:
 - Resolver: 2 seconds (1 runs)
    - Runtime: 408 milliseconds
    - Blocked (retrieving package details): 1 second (9 times)
    - Blocked (retrieving package versions): 736 milliseconds (2 times)
    - Not Blocked (retrieving package versions): 7 times
 - Disk IO: 77 milliseconds
 - Average Request Time: 713 milliseconds
 - Number of Requests: 32
 - Runtime: 3 seconds
```

So maybe there is in fact something not right with the escaping?

**Comment by nikoudel** [comment] 2017-06-18 09:46
I can confirm that the root cause is in Nexus - after having removed 30 oldest package versions out of 50 (so that only 20 is left) - paket installs all packages without deadlocking.

**Comment by matthid** [comment] 2017-06-18 10:05
@nikoudel So was `1.0.50` actually the newest version or not? It might still be a problem in how Paket makes the requests. It would be nice if one of the SonarType guys could answer. Can you open a Bug/Issue there and link it?

**Comment by nikoudel** [comment] 2017-06-18 10:14
@matthid Yes, 1.0.50 is the newest version. I didn't remove any packages in this test repository though, only in my production environment. Sure, I'll create an issue for SonarType.

**Closed** 2017-06-18 10:15 UTC

**Comment by nikoudel** [comment] 2017-06-18 10:44
Created a Nexus [bug report](https://issues.sonatype.org/browse/NEXUS-13426).

**Comment by matthid** [comment] 2017-06-18 13:30
@nikoudel thanks! Please keep us updated.

**Comment by matthid** [comment] 2017-06-18 15:25
@nikoudel Btw. we released 5.1 which is now working with your sever (but prints a warning).

**Comment by nikoudel** [comment] 2017-06-18 15:34
@matthid Awesome! Thank you for the lightning fast reaction! It's not even monday yet :)

**Comment by sjancke** [comment] 2018-01-02 12:32
@nikoudel we are seeing the same issue with Paket (warnings about the response of Nexus3) and with JetBrains Resharper Extension-Manager. 

The cause in Nexus3 seems to be, that $skip is ignored when using $filter, thus all next-links are broken.

Any updates from your side? Can you please check my comment in nexus jira and possibly update title and body, if it is the same issue?

**Comment by nikoudel** [comment] 2018-01-02 15:22
No updates from my side. I've updated the [Jira ticket](https://issues.sonatype.org/browse/NEXUS-13426).
