### ISSUE TITLE
paket does not accept paths that include Unicode characters

### ISSUE THREAD

**Issue by exercitusvir** [fsprojects/Paket#937] opened 2015-07-23 18:33 UTC
When I build a project that has a Unicode character in its name, I get the following error message in Visual Studio 2013:

> The command ""[solution path]\.paket\paket.exe" restore --references-files "[solution path]\source\[project name with Unicode character]\paket.references"" exited with code 1.

**Comment by forki** [comment] 2015-07-23 18:43
could please give an example? will try to fix that

**Comment by exercitusvir** [comment] 2015-07-23 18:49
The project name included the character "modifier letter half triangular colon" (U+02D1). But you will probably encounter the problem with any Unicode character. I confirmed that this was the problem by temporarily removing the offending character and it worked afterwards.

**Comment by forki** [comment] 2015-07-23 19:07
does this also happen when you run the same command manually from the cmd line?

**Comment by exercitusvir** [comment] 2015-07-23 19:30
The command line does not seem to complain, but the command line does not support Unicode itself (it displays the character as `?`), so I don't know what is actually happening there. But Visual Studio 2013 itself never had any problems with Unicode.

**Comment by forki** [comment] 2015-07-23 19:34
yeah it seems to be an issue with the targets file. I have no idea what to do here ;-(

**Comment by exercitusvir** [comment] 2015-07-24 11:35
Are you sure that paket supports Unicode in paths?

**Comment by forki** [comment] 2015-07-24 11:43
No idea. Never tried such a crazy thing ;-)

**Comment by exercitusvir** [comment] 2015-07-24 12:53
Are you planning to fix this? Supporting Unicode is not that crazy in the 21st century. `System.Globalization.StringInfo` contains all required methods. While `System.String` internally supports Unicode, it does not expose any Unicode-aware methods (e.g. String.length does not return the number of Unicode characters in the string).

**Comment by forki** [comment] 2015-07-24 13:06
> Are you planning to fix this?

I have no idea where it goes wrong, that's why I asked if can reproduce outside of the targets file.

**Comment by exercitusvir** [comment] 2015-07-25 18:00
How can I repro this outside of the targets file and outside of Visual Studio? 
This is easy to repro from within Visual Studio if you just place a Unicode character in a the path. 

If you don't explicitely use ` System.Globalization.StringInfo` on the paths than you probably don't support Unicode, because none of the `System.String` methods do.

**Comment by forki** [comment] 2015-08-05 07:46
I tried to add ^ into the path name and can't even open in VS:

![image](https://cloud.githubusercontent.com/assets/57396/9080723/de9dc7c0-3b56-11e5-8b76-44e124dc3385.png)

![image](https://cloud.githubusercontent.com/assets/57396/9080710/c20d2fa6-3b56-11e5-9da7-ce4de28cebb2.png)

**Comment by forki** [comment] 2015-08-05 07:50
![image](https://cloud.githubusercontent.com/assets/57396/9080760/308b4e22-3b57-11e5-9fc0-9dd336cb6d9a.png)

adding the ^ only to the name of one of the projects seems to work fine.

**Comment by forki** [comment] 2015-10-13 17:22
closing since no repro was given.

**Closed by forki** 2015-10-13 17:22 UTC
Labels: bug, needs-repro
