### ISSUE TITLE
How to consume .NETStandard libs in PCL project?

### ISSUE THREAD

**Issue by tastyeggs** [fsprojects/Paket#2763] opened 2017-09-14 07:49 UTC
I have a PCL Library, haven't yet moved to the .NETStandard World. However it seems like half the packages my project references publish against the .netstandard moniker, the rest using a various combination of platform monikers (a+b+c..)

I can't get quite a few of my references to work out of the box, even though .NETStandard1.0 libs can technically work on my PCL project.

Is there a nice way of handling this? What I'm doing is managing these references manually in the .csproj file, using `<Paket>False</Paket>`. Surely there must be a better way?

**Comment by enricosada** [comment] 2018-01-24 15:33
Afaik, PCL cannot import netstandard1.0 deps.
but a netstandard project can include PCL deps.

Closing, by design of .NET versioning.

@tastyeggs please open an issue in https://github.com/dotnet/standard/issues to check if is not correct this behaviour, and please reopen if is not correct

**Closed by enricosada** 2018-01-24 15:33 UTC
