### ISSUE TITLE
Paket.Restore.targets seems to break intellisense

### ISSUE THREAD

**Issue by aggieben** [fsprojects/Paket#2866] opened 2017-10-26 15:58 UTC
### Description

I have a project structure like this:
```
Sln\Sln.sln
Sln\src\Test.Proj1\Test.Proj1.fsproj
Sln\src\Test.Proj2\Test.Proj2.fsproj
```

Proj1 is a library.  It has no references to anything other than `FSharp.Core`.  It was created with `dotnet new classlib -lang F#`, and targets `net461`.

Proj2 is an app, also created with `dotnet new console -lang F#`.  It has a `ProjectReference` to `..\..\Test.Proj1\Test.Proj1.fsproj`, and similarly targets `net461`.

My `dotnet --info`:
```
C:\Users\ben\proj\scratch\test-ionide\20171026-paket
λ  dotnet --info
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

`dotnet restore` on the solution works, as does `dotnet build`.  However, when I open the project in Ionide, the intellisense features fail, and the following is shown in the editor:

![image](https://user-images.githubusercontent.com/1321/32062850-4e2fe342-ba3b-11e7-9e63-80c2c5e19e4d.png)

Similarly, MSBuild 15.4.8.50001 builds the projects with no problem.  But Visual Studio 2017 (15.4.1 with Visual F# 4.1) intellisense fails, showing this in the editor:

![image](https://user-images.githubusercontent.com/1321/32062939-902d432a-ba3b-11e7-93dc-04b8275f2a16.png)

### Repro steps

Please provide the steps required to reproduce the problem

1. `mkdir 20171026-paket`; `mkdir 20171026-paket\src`; `mkdir 20171026-paket\src\Test.Proj1`; `mkdir 201721026-paket\src\Test.Proj2`

2. `cd 20171026-paket`, `dotnet new sln`

2. `cd src\Test.Proj``, `dotnet new classlib -lang F#`

3. `cd ..\Test.Proj2`, `dotnet new console -lang F#`

4. `cd ..\..\`, `dotnet sln add src\Test.Proj1\Test.Proj1.fsproj`, `dotnet sln add src\Test.Proj2\Test.Proj2.fsproj`

5. Edit both project files and change `<TargetFramework>...</TargetFramework>` to `<TargetFramework>net461</TargetFramework>`

6. Edit `Test.Proj2.fsproj` with these lines:
```
<ItemGroup>
  <ProjectReference Include="..\..\Test.Proj1\Test.Proj1.fsproj" />
</ItemGroup>
```

6. Edit `Test.Proj2\Test.Proj2.fs` to refer to something in `Test.Proj1`.  I used the following to keep it simple:
```F#
// Learn more about F# at http://fsharp.org

[<EntryPoint>]
let main argv =
    argv |> ignore
    printfn "%A from F#!" <| Test.Proj1.Say.hello "Ben"
    0 // return an integer exit code
```

6. From solution dir, run `dotnet restore; dotnet build` and note successful build.

7. Open solution dir in Code+Ionide; observe successful load 

8. Download Paket bootstrapper like so (using PowerShell; `iwr` is equivalent to `curl`): `
iwr https://github.com/fsprojects/Paket/releases/download/5.119.8/paket.bootstrapper.exe -OutFile .paket\paket.bootstrapper.exe`

9. Run boostrapper.

10.  Run `.paket\paket.exe convert-from-nuget`; observe that the `Paket.Restore.targets` file is created in `.paket\`, and also that the `<Import Project="..\..\.paket\Paket.Restore.targets" />` line is inserted into both `Test.Proj1.fsproj` and `Test.Proj2.fsproj`.  

11. Close Code.

12.  From solution dir, run `dotnet restore; dotnet build`.  Observe successful build.

13.  Open solution folder in Code, open the `Test.Proj2.fs` file; wait for language service to respond; observe intellisense errors in editor as shown in description.

*Bonus Steps*

14. Comment out `<Import Project="..\..\.paket\Paket.Restore.targets" />` lines in both project files.

15.  Close Code

16.  From solution dir run `dotnet restore; dotnet build`.  Observe successful build.

17.  Open in Code; wait for language service response; observe intellisense failure.  I don't know how to explain this part because paket should be out of the picture.

[intellisense-failure.zip](https://github.com/fsprojects/Paket/files/1419120/intellisense-failure.zip)

### Expected behavior

Intellisense in both Code+Ionide and Visual F# should work in the presence of the `Paket.Restore.targets` import.

Here is the `DEBUG` output from the F# language service:
```
[10:38:06 DEBUG] RES (011) <- {project} in 904 ms: Kind={"error"}
Data={"Code":1,"Message":"MSBuild failed with exitCode 1 Working Directory: 'd:\\Users\\ben\\proj\\scratch\\test-ionide\\20171026-paket\\src\\Test.Proj2' Exe Path: 'dotnet' Args: 'msbuild d:\\Users\\ben\\proj\\scratch\\test-ionide\\20171026-paket\\src\\Test.Proj2\\Test.Proj2.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=C:\\Users\\ben\\AppData\\Local\\Temp\\tmpB86E.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=C:\\Users\\ben\\AppData\\Local\\Temp\\tmpB87F.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=C:\\Users\\ben\\AppData\\Local\\Temp\\tmpB880.tmp.GetProperties.txt /nologo /verbosity:quiet'\r\nLog: \r\nwriting helper target file in 'd:\\Users\\ben\\proj\\scratch\\test-ionide\\20171026-paket\\src\\Test.Proj2\\obj\\Test.Proj2.fsproj.proj-info.targets'\r\nC:\\Program Files\\dotnet\\sdk\\2.0.2\\Sdks\\Microsoft.NET.Sdk\\build\\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\\Users\\ben\\proj\\scratch\\test-ionide\\20171026-paket\\src\\Test.Proj2\\obj\\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.1/win7-x86'. Ensure that restore has run and that you have included 'net461' in the TargetFrameworks for your project. You may also need to include 'win7-x86' in your project's RuntimeIdentifiers. [d:\\Users\\ben\\proj\\scratch\\test-ionide\\20171026-paket\\src\\Test.Proj2\\Test.Proj2.fsproj]\r\n\r\n","AdditionalData":{}}
[10:38:06 ERROR] Project loading failed, MSBuild failed with exitCode 1 Working Directory: 'd:\Users\ben\proj\scratch\test-ionide\20171026-paket\src\Test.Proj2' Exe Path: 'dotnet' Args: 'msbuild d:\Users\ben\proj\scratch\test-ionide\20171026-paket\src\Test.Proj2\Test.Proj2.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=C:\Users\ben\AppData\Local\Temp\tmpB86E.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=C:\Users\ben\AppData\Local\Temp\tmpB87F.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=C:\Users\ben\AppData\Local\Temp\tmpB880.tmp.GetProperties.txt /nologo /verbosity:quiet'
Log: 
writing helper target file in 'd:\Users\ben\proj\scratch\test-ionide\20171026-paket\src\Test.Proj2\obj\Test.Proj2.fsproj.proj-info.targets'
C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\Users\ben\proj\scratch\test-ionide\20171026-paket\src\Test.Proj2\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.1/win7-x86'. Ensure that restore has run and that you have included 'net461' in the TargetFrameworks for your project. You may also need to include 'win7-x86' in your project's RuntimeIdentifiers. [d:\Users\ben\proj\scratch\test-ionide\20171026-paket\src\Test.Proj2\Test.Proj2.fsproj]
```

### Actual behavior

Intellisense fails in products that otherwise function properly.

### Known workarounds

None.

**Comment by forki** [comment] 2017-10-27 05:44
@Krzysztof-Cieslak @enricosada I don't think this is a paket issue, or is it?

**Comment by aggieben** [comment] 2017-10-27 14:24
I wasn't 100% sure this was paket, but it seemed like my best guess because it was the variable that determined whether this behavior manifested or not (i.e., this only happened with paket projects).  What confuses me is that the behavior lingers after removing paket from a project.

**Comment by TheAngryByrd** [comment] 2017-10-27 20:18
I can't reproduce in mono with that zip for what it's worth.

**Comment by enricosada** [comment] 2018-01-24 15:00
@aggieben please do in vscode

```
F# : Clear cache
dotnet restore //from cli
Reload window
```

should do.

If doesnt work, open an issue in https://github.com/ionide/ionide-vscode-fsharp/issues we canc ontinue there, it's not a paket issue. And mention me too in that issue (i'll continue there)

Closing.

**Closed by enricosada** 2018-01-24 15:00 UTC
Labels: sdk: dotnet/sdk
