### ISSUE TITLE
Paket install on dotnet core causes crashing build  

### ISSUE THREAD

**Issue by tomzo** [fsprojects/Paket#2341] opened 2017-05-17 08:01 UTC
### Description

Paket `5.0.0` is supposed to work well with dotnet core.
Even in simplest scenario with just one project and one reference in `paket.references`, `paket install` generates project references which cause internal error in dotnet sdk (see logs lower).

#### Environment

I am using 
 * Paket version 5.0.0-beta003 
 * official `microsoft/dotnet:1.0.5-sdk` docker image
 * on top of which I installed mono 4.6

### Repro steps

1. Clone this [simple project](https://github.com/tomzo/bug-paket-core) `git clone https://github.com/tomzo/bug-paket-core.git`
2. Run `paket install`
3. `dotnet restore`
4. `dotnet build` - will fail

### Expected behavior

`dotnet build` should pass.
It does before paket changes references in csproj. It also worked in older versions of paket.

### Actual behavior

`dotnet build` results in:
```
ide@8c9d9e9bb9ac:/ide/work/bug-paket-core$ dotnet build
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.targets(40,3): warning MSB4011: "/usr/share/dotnet/sdk/1.0.4/Microsoft.CSharp.targets" cannot be imported again. It was already imported at "/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj (28,3)". This is most likely a build authoring error. This subsequent import will be ignored. 
/usr/share/dotnet/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.targets(40,3): warning MSB4011: "/usr/share/dotnet/sdk/1.0.4/Microsoft.CSharp.targets" cannot be imported again. It was already imported at "/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj (28,3)". This is most likely a build authoring error. This subsequent import will be ignored. 
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018: The "ResolveAssemblyReference" task failed unexpectedly. [/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Unexpected CopyLocal flag. [/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018:    at Microsoft.Build.Tasks.CopyLocalStateUtility.IsCopyLocal(CopyLocalState state) [/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.LogResults(ReferenceTable dependencyTable, DependentAssembly[] idealAssemblyRemappings, AssemblyNameReference[] idealAssemblyRemappingsIdentities, ArrayList generalResolutionExceptions) [/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader) [/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute() [/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]

Build FAILED.
```

### Known workarounds

Use older paket `<5.0.0`

**Comment by forki** [comment] 2017-05-17 08:21
I'm on bad Internet but the error message seems to indicate that you still
have PackageReferences in the csproj. Can you please remove these and
reference packages only via Paket.references? /cc @cloudroutine

Am 17.05.2017 10:01 vorm. schrieb "Tomasz Sętkowski" <
notifications@github.com>:

Description

Paket 5.0.0 is supposed to work well with dotnet core.
Even in simplest scenario with just one project and one reference in
paket.references, paket install generates project references which cause
internal error in dotnet sdk (see logs lower).
Environment

I am using

   - Paket version 5.0.0-beta003
   - official microsoft/dotnet:1.0.5-sdk docker image
   - on top of which I installed mono 4.6

Repro steps

   1. Clone this simple project <https://github.com/tomzo/bug-paket-core> git
   clone https://github.com/tomzo/bug-paket-core.git
   2. Run paket install
   3. dotnet restore
   4. dotnet build - will fail

Expected behavior

dotnet build should pass.
It does before paket changes references in csproj. It also worked in older
versions of paket.
Actual behavior

dotnet build results in:

ide@8c9d9e9bb9ac:/ide/work/bug-paket-core$ dotnet build
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.targets(40,3):
warning MSB4011:
"/usr/share/dotnet/sdk/1.0.4/Microsoft.CSharp.targets" cannot be
imported again. It was already imported at
"/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj (28,3)". This
is most likely a build authoring error. This subsequent import will be
ignored.
/usr/share/dotnet/sdk/1.0.4/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.targets(40,3):
warning MSB4011:
"/usr/share/dotnet/sdk/1.0.4/Microsoft.CSharp.targets" cannot be
imported again. It was already imported at
"/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj (28,3)". This
is most likely a build authoring error. This subsequent import will be
ignored.
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5):
error MSB4018: The "ResolveAssemblyReference" task failed
unexpectedly. [/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5):
error MSB4018: Microsoft.Build.Shared.InternalErrorException: MSB0001:
Internal MSBuild Error: Unexpected CopyLocal flag.
[/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5):
error MSB4018:    at
Microsoft.Build.Tasks.CopyLocalStateUtility.IsCopyLocal(CopyLocalState
state) [/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5):
error MSB4018:    at
Microsoft.Build.Tasks.ResolveAssemblyReference.LogResults(ReferenceTable
dependencyTable, DependentAssembly[] idealAssemblyRemappings,
AssemblyNameReference[] idealAssemblyRemappingsIdentities, ArrayList
generalResolutionExceptions)
[/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5):
error MSB4018:    at
Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists
fileExists, DirectoryExists directoryExists, GetDirectories
getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata
getAssemblyMetadata, GetLastWriteTime getLastWriteTime,
GetAssemblyRuntimeVersion getRuntimeVersion, GetAssemblyPathInGac
getAssemblyPathInGac, IsWinMDFile isWinMDFile,
ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader)
[/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5):
error MSB4018:    at
Microsoft.Build.Tasks.ResolveAssemblyReference.Execute()
[/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5):
error MSB4018:    at
Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
[/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5):
error MSB4018:    at
Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()
[/ide/work/bug-paket-core/ExampleLib/ExampleLib.csproj]

Build FAILED.

Known workarounds

Use older paket <5.0.0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2341>, or mute the thread

**Comment by tomzo** [comment] 2017-05-17 08:31
Hi @forki 
All references are generated by paket only. There are no ` PackageReferences` in the csproj.
 I just removed all references and ran `paket install`. Definitely paket creates the faulty one.

**Comment by forki** [comment] 2017-05-17 08:40
Ok. Thanks will take a look next week when I'm back from vacation. Thanks
for creating a repro.

Am 17.05.2017 10:31 vorm. schrieb "Tomasz Sętkowski" <
notifications@github.com>:

Hi @forki <https://github.com/forki>
All references are generated by paket only. There are no PackageReferences
in the csproj.
I just removed all references and ran paket install. Definitely paket
creates the faulty one.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/2341#issuecomment-302022864>,
or mute the thread

**Comment by tomzo** [comment] 2017-05-28 17:54
I just tried running the example with `5.0.0-beta008` and build still fails, with
```
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018: The "ResolveAssemblyReference" task failed unexpectedly. [/ide/work/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Unexpected CopyLocal flag. [/ide/work/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018:    at Microsoft.Build.Tasks.CopyLocalStateUtility.IsCopyLocal(CopyLocalState state) [/ide/work/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.LogResults(ReferenceTable dependencyTable, DependentAssembly[] idealAssemblyRemappings, AssemblyNameReference[] idealAssemblyRemappingsIdentities, ArrayList generalResolutionExceptions) [/ide/work/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader) [/ide/work/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute() [/ide/work/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/ide/work/ExampleLib/ExampleLib.csproj]
/usr/share/dotnet/sdk/1.0.4/Microsoft.Common.CurrentVersion.targets(1964,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [/ide/work/ExampleLib/ExampleLib.csproj]
    2 Warning(s)
    1 Error(s)
```

@forki did you get a chance to look at this?

**Comment by forki** [comment] 2017-06-14 13:19
ok two things.
a) you have toolsversion 12 but sdk - this confused paket (fixed in rc010)
b) I removed the wrong entries from the csproj and sent you PR

sorry for delay

**Closed by forki** 2017-06-14 13:19 UTC

**Comment by tomzo** [comment] 2017-06-14 21:33
Thanks for the fix.
I have toolsversion 12 and sdk because the original project is built both on mono with xbuild and on dotnet core, I needed to find common ground for both to work.
