### ISSUE TITLE
paket.exe config add-token creates a redundant "packages" folder in the current directory

### ISSUE THREAD

**Issue by adamralph** [fsprojects/Paket#1951] opened 2016-10-10 06:31 UTC
### Description

See title.
### Repro steps
1. Add Paket version 3.21.4.0 to PATH.
2. `mkdir test`
3. `cd test`
4. `paket config add-token "https://www.nuget.org" <api-key>`
### Expected behavior

A packages folder is not created inside the `test` folder.
### Actual behavior

A packages folder is created inside the `test` folder.
### Known workarounds

Delete the folder.

**Comment by jbaehr** [comment] 2016-12-02 15:02
I get the same behavior using v3.30.2 when using `paket config add-credentials https://.....`
This is especially annoying when the current working directory is read-only. In that case `paket config` fails completely.

**Known workaround**
ensure the current working directory is writable.

**Comment by ruhullahshah** [comment] 2017-09-21 13:22
We had the same issue in our environment and after cross checking with Paket-5.99.1, the issue is fixed. The issue is reproducible in Paket-4.8.4, so the fix was merged between Paket-(4.8.4, 5.99.1]

**Comment by enricosada** [comment] 2018-01-24 10:48
> We had the same issue in our environment and after cross checking with Paket-5.99.1, the issue is fixed

Closing, fixed version >= 5.9..1

**Closed by enricosada** 2018-01-24 10:48 UTC
Labels: credentials, enhancement, up-for-grabs
