### ISSUE TITLE
Pack a subset of projects under the solution

### ISSUE THREAD

**Issue by mcai4gl2** [fsprojects/Paket#1671] opened 2016-05-09 11:43 UTC
Hi, 

I am working on a big legacy solution and I would like to build and package only a subset of projects using packet. Currently, pack command looks for all projects and stops when any projects' built dll cannot be found. 

Is there a way to restrict pack to look for only a subset of projects?

Thanks

**Comment by enricosada** [comment] 2018-01-24 11:38
Closing, dupe of https://github.com/fsprojects/Paket/issues/2054

**Closed by enricosada** 2018-01-24 11:38 UTC
