### ISSUE TITLE
storage: none option is breaking azure kudu deploy

### ISSUE THREAD

**Issue by kunjee17** [fsprojects/Paket#2836] opened 2017-10-10 15:38 UTC
### Description

storage: none option is breaking azure kudu deploy

### Repro steps

Please provide the steps required to reproduce the problem

Keep the option storage none and allow azure to run build on azure web site

### Expected behavior

It should work as it is. Able to compile it.

### Actual behavior

Currently build is failing. On cloud.

### Known workarounds
There is no known workaround. Other than opting out from storage none option.

**Comment by forki** [comment] 2017-10-10 16:13
That option is only for dotnet core stuff

Am 10.10.2017 17:38 schrieb "Kunjan" <notifications@github.com>:

**Comment by matthid** [comment] 2017-10-10 16:18
> build is failing

Not exactly the kind of information that helps us to fix the problem...
At least we need the output or more detailed error infos

Additionally, you cannot assume that we know what azure kudu deploy even is so at the very least we need a step by step guide (if you cannot provide more error details) + example project

To me it is not very clear if the build runs fine in another environment (like locally), but I guess it is?

**Comment by forki** [comment] 2017-10-10 16:20
@matthid kudu is that very azure centric deploy system that I have very
strong opinions against ;-) but @isaac_abraham says it's not that bad

Am 10.10.2017 18:18 schrieb "Matthias Dittrich" <notifications@github.com>:

**Comment by kunjee17** [comment] 2017-10-10 16:57
@matthid sorry for less info. But blame @forki :P . In most of the cases he knows stuff. Build was failing because package file is pointed to my local nuget folder. And that is not there on azure and that is failing the build.

@forki Oh didn't knew that it is for dotnet core. I am mostly using it for all local experiments so my project folder stays small. But again thanks. I removed it and it is working

On side note what are other good deployment options? As kudu is quite good (and so called devops in disguise). 
I am not sure about Doker part, it do have bigger starting hurdles at least for me. 

Please close the issue if you like. :)

**Comment by forki** [comment] 2017-10-10 17:02
Oh if it's for dotnet core then please provide more details. What's the
concrete error? Running it with -v will give stacktrace. Things like that

Am 10.10.2017 18:57 schrieb "Kunjan" <notifications@github.com>:

**Comment by kunjee17** [comment] 2017-10-10 17:04
@forki I am running full framework as of now. So, closing it. But when and if I move to dotnet core will surely let you know. kudu works with dotnet core. But I doubt storage none option will work. If you like I can give it a try around next weekend.

**Comment by forki** [comment] 2017-10-10 17:11
Yes please

Am 10.10.2017 19:04 schrieb "Kunjan" <notifications@github.com>:

**Comment by kunjee17** [comment] 2017-10-10 17:12
@forki surely. I ll give a shot. Will let you know after that. Keeping the issue open till that time.

**Comment by matthid** [comment] 2017-10-10 18:18
> Build was failing because package file is pointed to my local nuget folder.

Ok, please note that there is nothing fundamentally blocking `storage: none` for full framework. It just has not been done yet. The only thing to do is that paket somehow needs to "hook-in" (for example via a "generated" targets file) the path to the concrete nuget cache and needs to use a placeholder variable everywhere. This part has been decided to be up-for-grabs (as we expect people to move to the new sdk project format anyway) - it is not too difficult but quite a bit of work.
Another problem here might be proper visual studio support (especially if you target older version).

So yes moving forward is the easiest solution to use `storage:none` as of today.

**Comment by matthid** [comment] 2017-10-10 18:20
So as of now I'd say this issue is a duplicate of https://github.com/fsprojects/Paket/issues/2728

**Comment by matthid** [comment] 2017-10-10 18:22
An even simpler "solution" would be to change the project file update logic to make use of an environment variable and just expect users to set that properly.

**Comment by kunjee17** [comment] 2017-11-01 08:29
@forki seems it will work for dotnet core. because of new fsproj file. They don't store path of dependencies. And as shown in SAFE stack, I feel docker option is way better than kudu deployment. You can close this issue if you like.

**Comment by forki** [comment] 2017-11-01 08:36
Yes kudu deployment is weird. Dockery is the way to go.

Am 01.11.2017 09:29 schrieb "Kunjan" <notifications@github.com>:

**Comment by enricosada** [comment] 2018-01-23 16:23
> You can close this issue if you like.

Closing.

**Closed by enricosada** 2018-01-23 16:23 UTC
Labels: up-for-grabs
